package ai.xzkj.recruitment.resumes;

import ai.xzkj.recruitment.auth.SystemUser;
import ai.xzkj.recruitment.candidates.CandidateJobContact;
import jakarta.persistence.*;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;
import java.time.Instant;
import java.util.UUID;

@Entity @Table(name="resume_intakes") public class ResumeIntake {
 static final int MAX_ANALYSIS_ATTEMPTS=3; private static final long MAX_ANALYSIS_RETRY_DELAY_SECONDS=120;
 static final int MAX_DOCUMENT_PROCESSING_ATTEMPTS=5; private static final long MAX_DOCUMENT_PROCESSING_RETRY_DELAY_SECONDS=300;
 @Id private UUID id;@ManyToOne(fetch=FetchType.LAZY,optional=false)@JoinColumn(name="contact_id")private CandidateJobContact contact;@Enumerated(EnumType.STRING)@Column(nullable=false,length=24)private ResumeIntakeSource source;@JdbcTypeCode(SqlTypes.CHAR)@Column(name="resume_digest",nullable=false,length=64,columnDefinition="CHAR(64)")private String resumeDigest;@Column(name="display_label",nullable=false,length=120)private String displayLabel;@Enumerated(EnumType.STRING)@Column(nullable=false,length=24)private ResumeIntakeStatus status;@Column(name="received_at",nullable=false)private Instant receivedAt;@ManyToOne(fetch=FetchType.LAZY)@JoinColumn(name="reviewed_by")private SystemUser reviewedBy;@Column(name="reviewed_at")private Instant reviewedAt;@Column(name="review_note",length=500)private String reviewNote;@Column(name="created_at",nullable=false)private Instant createdAt;@Column(name="updated_at",nullable=false)private Instant updatedAt;
 @Column(name="processing_status",nullable=false,length=32)private String processingStatus="RECEIVED";@Column(name="document_type",length=24)private String documentType;@Column(name="malware_scanned",nullable=false)private boolean malwareScanned;@JdbcTypeCode(SqlTypes.CHAR)@Column(name="extracted_text_digest",length=64,columnDefinition="CHAR(64)")private String extractedTextDigest;@Column(name="failure_code",length=80)private String failureCode;@Column(name="failure_reason",length=300)private String failureReason;@Column(name="processed_at")private Instant processedAt;
 @Column(name="processing_attempts",nullable=false)private int processingAttempts;@Column(name="processing_next_attempt_at")private Instant processingNextAttemptAt;@Column(name="processing_lease_until")private Instant processingLeaseUntil;@Column(name="processing_queued_at")private Instant processingQueuedAt;@Column(name="processing_last_error",length=300)private String processingLastError;
 @JdbcTypeCode(SqlTypes.VARBINARY)@Column(name="source_pdf",columnDefinition="bytea")private byte[] sourcePdf;
 @Column(name="extracted_text",columnDefinition="text")private String extractedText;
 @JdbcTypeCode(SqlTypes.CHAR)@Column(name="source_event_digest",length=64,columnDefinition="CHAR(64)")private String sourceEventDigest;
 @Column(name="source_action_task_id")private UUID sourceActionTaskId;
 @Column(name="analysis_status",nullable=false,length=32)private String analysisStatus="NOT_REQUESTED";@Column(name="analysis_failure_code",length=80)private String analysisFailureCode;@Column(name="analysis_failure_reason",length=300)private String analysisFailureReason;@Column(name="analysis_completed_at")private Instant analysisCompletedAt;
 @Column(name="analysis_queue_status",nullable=false,length=24)private String analysisQueueStatus="NONE";@Column(name="analysis_queue_attempts",nullable=false)private int analysisQueueAttempts;@Column(name="analysis_queue_next_attempt_at")private Instant analysisQueueNextAttemptAt;@Column(name="analysis_queue_lease_until")private Instant analysisQueueLeaseUntil;@Column(name="analysis_queue_queued_at")private Instant analysisQueueQueuedAt;@Column(name="analysis_queue_last_error",length=300)private String analysisQueueLastError;
 protected ResumeIntake(){} ResumeIntake(CandidateJobContact contact,ResumeIntakeSource source,String digest,String label,Instant received){id=UUID.randomUUID();this.contact=contact;this.source=source;resumeDigest=digest;displayLabel=label;status=ResumeIntakeStatus.PENDING_REVIEW;receivedAt=received;createdAt=Instant.now();updatedAt=createdAt;}
 void review(ResumeIntakeStatus decision,String note,SystemUser reviewer,Instant now){status=decision;reviewNote=note;reviewedBy=reviewer;reviewedAt=now;updatedAt=now;} @PreUpdate void preUpdate(){updatedAt=Instant.now();}
 void autoApproveForAi(Instant now){status=ResumeIntakeStatus.APPROVED_FOR_AI;reviewNote="系统已完成文件安全检查和文本提取，自动进入 AI 分析";reviewedBy=null;reviewedAt=now;updatedAt=now;}
 void processing(){processingStatus="PROCESSING";failureCode=null;failureReason=null;}
 void queueDocumentProcessing(Instant now){processingStatus="QUEUED";processingAttempts=0;processingNextAttemptAt=now;processingLeaseUntil=null;processingQueuedAt=now;processingLastError=null;failureCode=null;failureReason=null;processedAt=null;updatedAt=now;}
 boolean claimDocumentProcessing(Instant now){if(processingAttempts>=MAX_DOCUMENT_PROCESSING_ATTEMPTS){processingFailed("RESUME_PROCESSING_RETRY_EXHAUSTED",processingLastError==null?"简历后台处理重试次数已达上限":processingLastError,now);return false;}processingStatus="PROCESSING";processingAttempts++;processingLeaseUntil=now.plusSeconds(180);processingNextAttemptAt=null;processingLastError=null;failureCode=null;failureReason=null;updatedAt=now;return true;}
 void attachSourceEvent(String digest){sourceEventDigest=digest;}
 public void attachSourceActionTask(UUID id){sourceActionTaskId=id;}
 void readyForAi(String type,String textDigest,boolean scanned,Instant now){processingStatus="READY_FOR_AI";documentType=type;extractedTextDigest=textDigest;malwareScanned=scanned;failureCode=null;failureReason=null;processedAt=now;processingLeaseUntil=null;processingNextAttemptAt=null;processingLastError=null;updatedAt=now;}
 void storeSourcePdf(byte[] content){sourcePdf=content == null ? null : content.clone();}
 void clearSourcePdf(){sourcePdf=null;updatedAt=Instant.now();}
 void storeExtractedText(String text){extractedText=text == null ? null : text; updatedAt=Instant.now();}
 void clearExtractedText(){extractedText=null;updatedAt=Instant.now();}
 public byte[] getSourcePdf(){return sourcePdf == null ? null : sourcePdf.clone();}
 public String getExtractedText(){return extractedText;}
 boolean retryDocumentProcessing(String reason,Instant now){if(processingAttempts>=MAX_DOCUMENT_PROCESSING_ATTEMPTS){processingFailed("RESUME_PROCESSING_RETRY_EXHAUSTED",reason,now);return false;}processingStatus="RETRY_WAIT";processingLastError=bounded(reason);processingNextAttemptAt=now.plusSeconds(Math.min(MAX_DOCUMENT_PROCESSING_RETRY_DELAY_SECONDS,10L*(1L<<Math.max(0,processingAttempts-1))));processingLeaseUntil=null;failureCode=null;failureReason=null;updatedAt=now;return true;}
 void recoverDocumentProcessingLease(Instant now){if("PROCESSING".equals(processingStatus)&&processingLeaseUntil!=null&&!processingLeaseUntil.isAfter(now)){processingStatus="QUEUED";processingNextAttemptAt=now;processingLeaseUntil=null;updatedAt=now;}}
 void processingFailed(String code,String reason,Instant now){processingStatus="FAILED";failureCode=code;failureReason=reason;processedAt=now;processingLeaseUntil=null;processingNextAttemptAt=null;processingLastError=bounded(reason);updatedAt=now;}
 void analysisStarted(){analysisStatus="ANALYZING";analysisFailureCode=null;analysisFailureReason=null;analysisCompletedAt=null;}
 void analysisSucceeded(Instant now){analysisStatus="SUCCEEDED";analysisFailureCode=null;analysisFailureReason=null;analysisCompletedAt=now;}
 void analysisUnavailable(String status,String code,String reason,Instant now){analysisStatus=status;analysisFailureCode=code;analysisFailureReason=reason;analysisCompletedAt=now;}
 void copyAnalysisStateFrom(ResumeIntake analyzed){
  if(analyzed==null)return;
  analysisStatus=analyzed.analysisStatus;analysisFailureCode=analyzed.analysisFailureCode;
  analysisFailureReason=analyzed.analysisFailureReason;analysisCompletedAt=analyzed.analysisCompletedAt;
  updatedAt=Instant.now();
 }
 void queueAnalysis(Instant now){if("SUCCEEDED".equals(analysisQueueStatus)||"PROCESSING".equals(analysisQueueStatus))return;if("FAILED".equals(analysisQueueStatus)||"NONE".equals(analysisQueueStatus))analysisQueueAttempts=0;analysisQueueStatus="QUEUED";analysisQueueNextAttemptAt=now;analysisQueueQueuedAt=now;analysisQueueLeaseUntil=null;analysisQueueLastError=null;updatedAt=now;}
 boolean claimAnalysis(Instant now){if(analysisQueueAttempts>=MAX_ANALYSIS_ATTEMPTS){failAnalysisQueue("AI 分析重试次数已达上限",now);return false;}analysisQueueStatus="PROCESSING";analysisQueueAttempts++;analysisQueueLeaseUntil=now.plusSeconds(180);analysisQueueNextAttemptAt=null;updatedAt=now;return true;}
 void deferAnalysisForReplyPriority(Instant now){analysisQueueStatus="QUEUED";analysisQueueAttempts=Math.max(0,analysisQueueAttempts-1);analysisQueueNextAttemptAt=now.plusSeconds(5);analysisQueueLeaseUntil=null;updatedAt=now;}
 void completeAnalysisQueue(Instant now){analysisQueueStatus="SUCCEEDED";analysisQueueLeaseUntil=null;analysisQueueNextAttemptAt=null;analysisQueueLastError=null;updatedAt=now;}
 boolean retryAnalysisQueue(String reason,Instant now){if(analysisQueueAttempts>=MAX_ANALYSIS_ATTEMPTS){failAnalysisQueue(reason,now);return false;}analysisQueueStatus="RETRY_WAIT";analysisQueueLastError=bounded(reason);long delay=Math.min(MAX_ANALYSIS_RETRY_DELAY_SECONDS,10L*(1L<<Math.max(0,analysisQueueAttempts-1)));analysisQueueNextAttemptAt=now.plusSeconds(delay);analysisQueueLeaseUntil=null;updatedAt=now;return true;}
 void failAnalysisQueue(String reason,Instant now){analysisQueueStatus="FAILED";analysisQueueLastError=bounded(reason);analysisQueueLeaseUntil=null;analysisQueueNextAttemptAt=null;updatedAt=now;}
 void recoverAnalysisLease(Instant now){if("PROCESSING".equals(analysisQueueStatus)&&analysisQueueLeaseUntil!=null&&!analysisQueueLeaseUntil.isAfter(now)){analysisQueueStatus="QUEUED";analysisQueueNextAttemptAt=now;analysisQueueLeaseUntil=null;updatedAt=now;}}
 private String bounded(String value){String clean=value==null?"AI 分析未完成":value.replace('\n',' ').replace('\r',' ').trim();return clean.substring(0,Math.min(300,clean.length()));}
 public UUID getId(){return id;}public CandidateJobContact getContact(){return contact;}public ResumeIntakeSource getSource(){return source;}public String getResumeDigest(){return resumeDigest;}public String getSourceEventDigest(){return sourceEventDigest;}public UUID getSourceActionTaskId(){return sourceActionTaskId;}public String getDisplayLabel(){return displayLabel;}public ResumeIntakeStatus getStatus(){return status;}public String getProcessingStatus(){return processingStatus;}public String getDocumentType(){return documentType;}public boolean isMalwareScanned(){return malwareScanned;}public String getExtractedTextDigest(){return extractedTextDigest;}public String getFailureCode(){return failureCode;}public String getFailureReason(){return failureReason;}public Instant getProcessedAt(){return processedAt;}public int getProcessingAttempts(){return processingAttempts;}public Instant getProcessingNextAttemptAt(){return processingNextAttemptAt;}public Instant getProcessingLeaseUntil(){return processingLeaseUntil;}public Instant getProcessingQueuedAt(){return processingQueuedAt;}public String getProcessingLastError(){return processingLastError;}public String getAnalysisStatus(){return analysisStatus;}public String getAnalysisFailureCode(){return analysisFailureCode;}public String getAnalysisFailureReason(){return analysisFailureReason;}public Instant getAnalysisCompletedAt(){return analysisCompletedAt;}public String getAnalysisQueueStatus(){return analysisQueueStatus;}public int getAnalysisQueueAttempts(){return analysisQueueAttempts;}public Instant getAnalysisQueueNextAttemptAt(){return analysisQueueNextAttemptAt;}public Instant getAnalysisQueueLeaseUntil(){return analysisQueueLeaseUntil;}public Instant getAnalysisQueueQueuedAt(){return analysisQueueQueuedAt;}public String getAnalysisQueueLastError(){return analysisQueueLastError;}public Instant getReceivedAt(){return receivedAt;}public SystemUser getReviewedBy(){return reviewedBy;}public Instant getReviewedAt(){return reviewedAt;}public String getReviewNote(){return reviewNote;}public Instant getCreatedAt(){return createdAt;}
}
