package ai.xzkj.recruitment.resumes;
import ai.xzkj.recruitment.audit.AuditService;import ai.xzkj.recruitment.auth.*;import ai.xzkj.recruitment.candidates.*;import ai.xzkj.recruitment.common.ApiException;import ai.xzkj.recruitment.organization.Company;import org.springframework.http.HttpStatus;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.nio.charset.StandardCharsets;import java.security.MessageDigest;import java.time.*;import java.util.*;
@Service public class ResumeIntakeService{
 private final ResumeIntakeRepository intakes;private final CandidateJobContactRepository contacts;private final CurrentUserService users;private final AuditService audit;public ResumeIntakeService(ResumeIntakeRepository i,CandidateJobContactRepository c,CurrentUserService u,AuditService a){intakes=i;contacts=c;users=u;audit=a;}
 @Transactional(readOnly=true)public List<ResumeIntakeResponse> list(){SystemUser u=users.requireCurrentUser();return intakes.findAllByOrderByReceivedAtDesc().stream().filter(i->canAccess(i.getContact().getCandidate().getCompany().getId(),u)).map(ResumeIntakeResponse::from).toList();}
 @Transactional public ResumeIntakeResponse create(UUID contactId,ResumeIntakeCreateRequest request){SystemUser u=users.requireCurrentUser();CandidateJobContact c=requireContact(contactId,u);String digest=hash(clean(request.reference(),120));ResumeIntake existing=intakes.findByContactIdAndResumeDigest(contactId,digest).orElse(null);if(existing!=null)return ResumeIntakeResponse.from(existing);ResumeIntake intake=intakes.save(new ResumeIntake(c,ResumeIntakeSource.MANUAL,digest,clean(request.displayLabel(),120),validReceivedAt(request.receivedAt())));audit.success("REGISTER_RESUME_INTAKE","RESUME_INTAKE",intake.getId(),"简历摘要 "+digest.substring(0,12),"登记内部简历事件；不保存原始文件、路径或参考值");return ResumeIntakeResponse.from(intake);}
 @Transactional public ResumeIntakeResponse review(UUID id,ResumeIntakeReviewRequest request){SystemUser u=users.requireCurrentUser();ResumeIntake intake=intakes.findWithDetailsById(id).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"RESUME_INTAKE_NOT_FOUND","简历登记不存在"));requireAccess(intake.getContact().getCandidate().getCompany().getId(),u);if(request.decision()==ResumeIntakeStatus.PENDING_REVIEW)throw new ApiException(HttpStatus.BAD_REQUEST,"RESUME_REVIEW_DECISION_REQUIRED","请批准进入 AI 分析或拒绝该简历登记");intake.review(request.decision(),cleanOptional(request.note(),500),u,Instant.now());audit.success("REVIEW_RESUME_INTAKE","RESUME_INTAKE",intake.getId(),"简历摘要 "+intake.getResumeDigest().substring(0,12),"简历登记人工结论："+request.decision().name());return ResumeIntakeResponse.from(intake);}
 private CandidateJobContact requireContact(UUID id,SystemUser u){CandidateJobContact c=contacts.findWithDetailsById(id).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"CANDIDATE_CONTACT_NOT_FOUND","候选人职位关系不存在"));requireAccess(c.getCandidate().getCompany().getId(),u);return c;}private void requireAccess(UUID id,SystemUser u){if(!canAccess(id,u))throw new ApiException(HttpStatus.FORBIDDEN,"COMPANY_SCOPE_FORBIDDEN","当前账号无权访问该企业数据");}private boolean canAccess(UUID id,SystemUser u){return u.getRole()==UserRole.SYSTEM_ADMIN||u.getCompanyScopes().stream().map(Company::getId).anyMatch(id::equals);}private Instant validReceivedAt(Instant value){Instant now=Instant.now();if(value==null)return now;if(value.isAfter(now.plusSeconds(300))||value.isBefore(now.minus(Duration.ofDays(365))))throw new ApiException(HttpStatus.BAD_REQUEST,"RESUME_TIME_INVALID","简历接收时间必须在最近一年内且不能晚于当前时间");return value;}private String clean(String v,int max){if(v==null||v.isBlank())throw new ApiException(HttpStatus.BAD_REQUEST,"RESUME_VALUE_REQUIRED","简历登记信息不能为空");String c=v.trim();if(c.length()>max)throw new ApiException(HttpStatus.BAD_REQUEST,"RESUME_VALUE_TOO_LONG","简历登记信息过长");return c;}private String cleanOptional(String v,int max){return v==null||v.isBlank()?null:clean(v,max);}private String hash(String v){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(v.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException("SHA-256 unavailable",e);}}
}
