package ai.xzkj.recruitment.localconnector;

import org.junit.jupiter.api.Test;
import java.time.Instant;import java.util.UUID;
import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

class InboundAiReplyTaskTest{
 @Test void modelQualitySkipCanBeRevalidatedImmediatelyButNormalSilenceWaits(){Instant now=Instant.parse("2026-09-12T08:00:00Z");InboundAiReplyTask quality=new InboundAiReplyTask(UUID.randomUUID(),UUID.randomUUID(),UUID.randomUUID(),"a".repeat(64),"b".repeat(64),"薪资多少",now);quality.start(now);quality.complete(new InboundJobReplyService.Decision(false,"SALARY",.9,null,"AI 回复未通过独立意图校验：未覆盖 SALARY"),now.plusSeconds(1));assertThat(quality.isReplayableFailure(now.plusSeconds(2),java.time.Duration.ofMinutes(30))).isTrue();assertThat(quality.requeueWithFreshInput("薪资多少",null,now.plusSeconds(2))).isTrue();assertThat(quality.isReplayableFailure()).isFalse();InboundAiReplyTask silence=new InboundAiReplyTask(UUID.randomUUID(),UUID.randomUUID(),UUID.randomUUID(),"c".repeat(64),"d".repeat(64),"谢谢",now);silence.start(now);silence.complete(new InboundJobReplyService.Decision(false,"SOCIAL_THANKS",.9,null,"正常静默：自然结束"),now.plusSeconds(1));assertThat(silence.isReplayableFailure(now.plusSeconds(60),java.time.Duration.ofMinutes(30))).isFalse();assertThat(silence.isReplayableFailure(now.plusSeconds(1801),java.time.Duration.ofMinutes(30))).isTrue();}
 @Test void expectedSilenceIsNotAnHrReviewFailure(){Instant now=Instant.parse("2026-09-07T05:00:00Z");InboundAiReplyTask task=new InboundAiReplyTask(UUID.randomUUID(),UUID.randomUUID(),UUID.randomUUID(),"a".repeat(64),"b".repeat(64),"好的",now);task.start(now);task.complete(new InboundJobReplyService.Decision(false,"SOCIAL_ACKNOWLEDGEMENT",.96,null,"正常静默：候选人仅确认收到"),now.plusSeconds(1));assertThat(task.getSendStatus()).isEqualTo("SKIPPED");assertThat(task.isExpectedSilence()).isTrue();}
 @Test void normalSilenceRequiresTenSecondsBeforeReplay(){Instant now=Instant.parse("2026-09-07T05:00:00Z");InboundAiReplyTask task=new InboundAiReplyTask(UUID.randomUUID(),UUID.randomUUID(),UUID.randomUUID(),"a".repeat(64),"b".repeat(64),"谢谢",now);task.start(now);task.complete(new InboundJobReplyService.Decision(false,"SOCIAL_THANKS",.96,null,"正常静默：自然结束"),now.plusSeconds(1));assertThat(task.isReplayableFailure(now.plusSeconds(10),java.time.Duration.ofSeconds(10))).isFalse();assertThat(task.isReplayableFailure(now.plusSeconds(11),java.time.Duration.ofSeconds(10))).isTrue();}
 @Test void replaysOnlyActualCancellationsFromLegacyInterviewCoordination(){Instant now=Instant.parse("2026-09-13T12:00:00Z");InboundAiReplyTask cancellation=new InboundAiReplyTask(UUID.randomUUID(),UUID.randomUUID(),UUID.randomUUID(),"a".repeat(64),"b".repeat(64),"非常抱歉，因临时有事，无法按照定时间参加面试。",now);cancellation.start(now);cancellation.complete(new InboundJobReplyService.Decision(false,"INTERVIEW_COORDINATION",.95,null,"疑似正在确认或变更面试时间，已停止自动回复并转 HR 跟进"),now.plusSeconds(1));assertThat(cancellation.isReplayableFailure()).isTrue();InboundAiReplyTask scheduling=new InboundAiReplyTask(UUID.randomUUID(),UUID.randomUUID(),UUID.randomUUID(),"c".repeat(64),"d".repeat(64),"能安排面试吗",now);scheduling.start(now);scheduling.complete(new InboundJobReplyService.Decision(false,"INTERVIEW_COORDINATION",.95,null,"疑似正在确认或变更面试时间，已停止自动回复并转 HR 跟进"),now.plusSeconds(1));assertThat(scheduling.isReplayableFailure()).isFalse();}
 @Test void genericManualReviewInterviewQuestionIsNotAddedToReplayInventory(){Instant now=Instant.parse("2026-09-13T12:00:00Z");InboundAiReplyTask task=new InboundAiReplyTask(UUID.randomUUID(),UUID.randomUUID(),UUID.randomUUID(),"a".repeat(64),"b".repeat(64),"你好，什么时候方便过去面试呢",now);task.start(now);task.complete(new InboundJobReplyService.Decision(false,"OTHER_RECRUITMENT",.8,null,"AI 判断该消息需要人工复核，未自动回复"),now.plusSeconds(1));assertThat(task.isReplayableFailure()).isFalse();}
 @Test void supersededProcessingTaskCannotReturnToReadyAfterModelCompletes(){Instant now=Instant.parse("2026-09-07T05:00:00Z");InboundAiReplyTask task=new InboundAiReplyTask(UUID.randomUUID(),UUID.randomUUID(),UUID.randomUUID(),"a".repeat(64),"b".repeat(64),"旧消息",now);task.start(now.plusSeconds(1));task.supersede("候选人已发送新消息",now.plusSeconds(2));task.complete(new InboundJobReplyService.Decision(true,"GREETING",.95,"旧回复","已校验"),now.plusSeconds(3));assertThat(task.getStatus()).isEqualTo("COMPLETED");assertThat(task.getSendStatus()).isEqualTo("SKIPPED");assertThat(task.decision().replyAllowed()).isFalse();assertThat(task.getReplyContent()).isNull();}
 @Test void retainsCandidateTextAfterCompletionAndKeepsDecision(){Instant now=Instant.parse("2026-09-07T05:00:00Z");InboundAiReplyTask task=new InboundAiReplyTask(UUID.randomUUID(),UUID.randomUUID(),UUID.randomUUID(),"a".repeat(64),"b".repeat(64),"候选人的岗位问题",now);task.start(now.plusSeconds(1));task.complete(new InboundJobReplyService.Decision(true,"LOCATION",0.96,"工作地点为广州。","事实校验通过"),now.plusSeconds(2));assertThat(task.getStatus()).isEqualTo("COMPLETED");assertThat(task.getMessageText()).isEqualTo("候选人的岗位问题");assertThat(task.decision().replyAllowed()).isTrue();assertThat(task.decision().category()).isEqualTo("LOCATION");}
 @Test void returnsStaleProcessingTaskToQueue(){Instant now=Instant.parse("2026-09-07T05:00:00Z");InboundAiReplyTask task=new InboundAiReplyTask(UUID.randomUUID(),UUID.randomUUID(),UUID.randomUUID(),"a".repeat(64),"b".repeat(64),"问题",now);task.start(now);task.recoverIfStale(now.plusSeconds(181));assertThat(task.getStatus()).isEqualTo("QUEUED");}
 @Test void requeuesWithoutConsumingAttemptWhenModelCapacityTimesOut(){Instant now=Instant.parse("2026-09-07T05:00:00Z");InboundAiReplyTask task=new InboundAiReplyTask(UUID.randomUUID(),UUID.randomUUID(),UUID.randomUUID(),"a".repeat(64),"b".repeat(64),"问题",now);task.start(now);task.requeueAfterModelCapacity(now.plusSeconds(10));assertThat(task.getStatus()).isEqualTo("QUEUED");assertThat(task.getAttemptCount()).isZero();assertThat(task.getNextAttemptAt()).isEqualTo(now.plusSeconds(10));}
 @Test void waitsWithCandidateTextUntilRetryIsDue(){Instant now=Instant.parse("2026-09-07T05:00:00Z");InboundAiReplyTask task=new InboundAiReplyTask(UUID.randomUUID(),UUID.randomUUID(),UUID.randomUUID(),"a".repeat(64),"b".repeat(64),"问题",now);task.start(now);assertThat(task.retry("TIMEOUT","超时",now.plusSeconds(1))).isTrue();assertThat(task.getStatus()).isEqualTo("RETRY_WAIT");assertThat(task.getMessageText()).isEqualTo("问题");task.releaseRetry(now.plusSeconds(5));assertThat(task.getStatus()).isEqualTo("RETRY_WAIT");task.releaseRetry(now.plusSeconds(6));assertThat(task.getStatus()).isEqualTo("QUEUED");}
 @Test void stopsAfterThreeAttemptsAndRetainsCandidateText(){Instant now=Instant.parse("2026-09-07T05:00:00Z");InboundAiReplyTask task=new InboundAiReplyTask(UUID.randomUUID(),UUID.randomUUID(),UUID.randomUUID(),"a".repeat(64),"b".repeat(64),"问题",now);for(int attempt=1;attempt<=3;attempt++){task.start(now.plusSeconds(attempt));boolean retrying=task.retry("TIMEOUT","第 "+attempt+" 次超时",now.plusSeconds(attempt));if(attempt<3){assertThat(retrying).isTrue();task.releaseRetry(task.getNextAttemptAt());}else assertThat(retrying).isFalse();}assertThat(task.getStatus()).isEqualTo("FAILED");assertThat(task.getMessageText()).isEqualTo("问题");assertThat(task.getAttemptCount()).isEqualTo(3);}
 @Test void nonRetryableFailureRetainsItsErrorCode(){Instant now=Instant.parse("2026-09-07T05:00:00Z");InboundAiReplyTask task=new InboundAiReplyTask(UUID.randomUUID(),UUID.randomUUID(),UUID.randomUUID(),"a".repeat(64),"b".repeat(64),"问题",now);task.start(now.plusSeconds(1));task.fail("INBOUND_REPLY_AI_AUTH_FAILED","上游 HTTP 401：认证失败",now.plusSeconds(2));assertThat(task.getStatus()).isEqualTo("FAILED");assertThat(task.getLastErrorCode()).isEqualTo("INBOUND_REPLY_AI_AUTH_FAILED");assertThat(task.getSendStatus()).isEqualTo("SKIPPED");}
 @Test void safelyRequeuesOnlyOnceWithFreshText(){Instant now=Instant.parse("2026-09-07T05:00:00Z");InboundAiReplyTask task=new InboundAiReplyTask(UUID.randomUUID(),UUID.randomUUID(),UUID.randomUUID(),"a".repeat(64),"b".repeat(64),"旧消息",now);task.start(now.plusSeconds(1));task.fail("INBOUND_REPLY_AI_REQUEST_FAILED","上游认证失败",now.plusSeconds(2));assertThat(task.requeueWithFreshInput("当前最新消息","候选人：您好",now.plusSeconds(3))).isTrue();assertThat(task.getStatus()).isEqualTo("QUEUED");assertThat(task.getSendStatus()).isEqualTo("PENDING");assertThat(task.getMessageText()).isEqualTo("当前最新消息");assertThat(task.getConversationContext()).isEqualTo("候选人：您好");assertThat(task.getAttemptCount()).isZero();assertThat(task.getSafeReplayCount()).isEqualTo(1);assertThat(task.getLastErrorCode()).isNull();assertThat(task.getCompletedAt()).isNull();task.start(now.plusSeconds(4));task.fail("AI_OUTPUT_INVALID","仍不合规",now.plusSeconds(5));assertThat(task.requeueWithFreshInput("当前最新消息",null,now.plusSeconds(6))).isFalse();}
 @Test void refusesReplayWhenFailureIsNotRetryableOrInputIsBlank(){Instant now=Instant.parse("2026-09-07T05:00:00Z");InboundAiReplyTask auth=new InboundAiReplyTask(UUID.randomUUID(),UUID.randomUUID(),UUID.randomUUID(),"a".repeat(64),"b".repeat(64),"问题",now);auth.start(now);auth.fail("INBOUND_REPLY_AI_AUTH_FAILED","认证失败",now.plusSeconds(1));assertThat(auth.requeueWithFreshInput("新消息",null,now.plusSeconds(2))).isFalse();assertThat(auth.getStatus()).isEqualTo("FAILED");InboundAiReplyTask invalid=new InboundAiReplyTask(UUID.randomUUID(),UUID.randomUUID(),UUID.randomUUID(),"a".repeat(64),"b".repeat(64),"问题",now);invalid.start(now);invalid.fail("AI_OUTPUT_INVALID","输出不合规",now.plusSeconds(1));assertThat(invalid.requeueWithFreshInput(" ",null,now.plusSeconds(2))).isFalse();assertThat(invalid.getStatus()).isEqualTo("FAILED");}
 @Test void sendLeaseCanOnlyBeClaimedAndCompletedOnce(){Instant now=Instant.parse("2026-09-07T05:00:00Z");UUID device=UUID.randomUUID();InboundAiReplyTask task=new InboundAiReplyTask(UUID.randomUUID(),UUID.randomUUID(),UUID.randomUUID(),"a".repeat(64),"b".repeat(64),"问题",now);task.start(now);task.complete(new InboundJobReplyService.Decision(true,"LOCATION",.98,"工作地点为广州。","已校验"),now.plusSeconds(1));assertThat(task.getSendStatus()).isEqualTo("READY");assertThat(task.claimSend(device,"c".repeat(64),"d".repeat(64),now.plusSeconds(2))).isTrue();assertThat(task.claimSend(device,"e".repeat(64),"f".repeat(64),now.plusSeconds(3))).isFalse();assertThat(task.receiptSend(device,"SUCCEEDED","d".repeat(64),"e".repeat(64),"f".repeat(64),"已确认",now.plusSeconds(4))).isTrue();assertThat(task.receiptSend(device,"SUCCEEDED","d".repeat(64),"e".repeat(64),"f".repeat(64),"已确认",now.plusSeconds(5))).isFalse();assertThat(task.getSendStatus()).isEqualTo("SUCCEEDED");assertThatThrownBy(()->task.receiptSend(device,"UNKNOWN","d".repeat(64),"a".repeat(64),"b".repeat(64),"冲突",now.plusSeconds(6))).isInstanceOf(IllegalStateException.class);}
 @Test void expiredSendLeaseBecomesUnknownAndCannotBeRetried(){Instant now=Instant.parse("2026-09-07T05:00:00Z");InboundAiReplyTask task=new InboundAiReplyTask(UUID.randomUUID(),UUID.randomUUID(),UUID.randomUUID(),"a".repeat(64),"b".repeat(64),"问题",now);task.start(now);task.complete(new InboundJobReplyService.Decision(true,"GREETING",.95,"您好，当前岗位正在招聘。","已校验"),now.plusSeconds(1));task.claimSend(UUID.randomUUID(),"c".repeat(64),"d".repeat(64),now.plusSeconds(2));assertThat(task.getSendLeaseUntil()).isEqualTo(now.plusSeconds(2+InboundAiReplyTask.SEND_LEASE_SECONDS));task.expireSendLease(now.plusSeconds(48));assertThat(task.getSendStatus()).isEqualTo("UNKNOWN");assertThat(task.claimSend(UUID.randomUUID(),"e".repeat(64),"f".repeat(64),now.plusSeconds(49))).isFalse();}
 @Test void definiteSendFailureCanBeRevalidatedButUnknownCannot(){Instant now=Instant.parse("2026-09-07T05:00:00Z");UUID device=UUID.randomUUID();InboundAiReplyTask failed=new InboundAiReplyTask(UUID.randomUUID(),UUID.randomUUID(),UUID.randomUUID(),"a".repeat(64),"b".repeat(64),"您好",now);failed.start(now);failed.complete(new InboundJobReplyService.Decision(true,"GREETING",.95,"您好，可以聊聊。","已校验"),now.plusSeconds(1));failed.claimSend(device,"c".repeat(64),"d".repeat(64),now.plusSeconds(2));failed.receiptSend(device,"FAILED","d".repeat(64),"d".repeat(64),"e".repeat(64),"页面明确未发送",now.plusSeconds(3));assertThat(failed.isReplayableFailure()).isTrue();InboundAiReplyTask unknown=new InboundAiReplyTask(UUID.randomUUID(),UUID.randomUUID(),UUID.randomUUID(),"f".repeat(64),"1".repeat(64),"您好",now);unknown.start(now);unknown.complete(new InboundJobReplyService.Decision(true,"GREETING",.95,"您好，可以聊聊。","已校验"),now.plusSeconds(1));unknown.claimSend(device,"2".repeat(64),"3".repeat(64),now.plusSeconds(2));unknown.expireSendLease(now.plusSeconds(48));assertThat(unknown.isReplayableFailure()).isFalse();}
 @Test void marksAValidatedPartialReplyForHrFollowUp(){Instant now=Instant.parse("2026-09-07T05:00:00Z");InboundAiReplyTask task=new InboundAiReplyTask(UUID.randomUUID(),UUID.randomUUID(),UUID.randomUUID(),"a".repeat(64),"b".repeat(64),"问题",now);task.start(now);task.complete(new InboundJobReplyService.Decision(true,"LOCATION",.95,"地点在广州，排班需要招聘人员确认。","已部分回答，仍需 HR 补充：OTHER_RECRUITMENT"),now.plusSeconds(1));assertThat(task.isPartialReply()).isTrue();}
 @Test void shadowEvaluationKeepsCandidateReplyWithoutMakingItSendable(){Instant now=Instant.parse("2026-09-07T05:00:00Z");InboundAiReplyTask task=new InboundAiReplyTask(UUID.randomUUID(),UUID.randomUUID(),UUID.randomUUID(),"a".repeat(64),"b".repeat(64),"工资多少",now);task.start(now);task.complete(new InboundJobReplyService.Decision(true,"SALARY",.97,"薪资范围是 8-13K。","事实校验通过").asShadowEvaluation(),now.plusSeconds(1));assertThat(task.getSendStatus()).isEqualTo("SKIPPED");assertThat(task.isShadowEvaluation()).isTrue();assertThat(task.wasReplyApproved()).isTrue();assertThat(task.getReplyContent()).isEqualTo("薪资范围是 8-13K。");}
}
