package ai.xzkj.recruitment.localconnector;

import org.junit.jupiter.api.Test;
import java.time.Instant;import java.util.UUID;
import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

class InboundAiReplyTaskTest{
 @Test void expectedSilenceIsNotAnHrReviewFailure(){Instant now=Instant.parse("2026-09-07T05:00:00Z");InboundAiReplyTask task=new InboundAiReplyTask(UUID.randomUUID(),UUID.randomUUID(),UUID.randomUUID(),"a".repeat(64),"b".repeat(64),"好的",now);task.start(now);task.complete(new InboundJobReplyService.Decision(false,"SOCIAL_ACKNOWLEDGEMENT",.96,null,"正常静默：候选人仅确认收到"),now.plusSeconds(1));assertThat(task.getSendStatus()).isEqualTo("SKIPPED");assertThat(task.isExpectedSilence()).isTrue();}
 @Test void supersededProcessingTaskCannotReturnToReadyAfterModelCompletes(){Instant now=Instant.parse("2026-09-07T05:00:00Z");InboundAiReplyTask task=new InboundAiReplyTask(UUID.randomUUID(),UUID.randomUUID(),UUID.randomUUID(),"a".repeat(64),"b".repeat(64),"旧消息",now);task.start(now.plusSeconds(1));task.supersede("候选人已发送新消息",now.plusSeconds(2));task.complete(new InboundJobReplyService.Decision(true,"GREETING",.95,"旧回复","已校验"),now.plusSeconds(3));assertThat(task.getStatus()).isEqualTo("COMPLETED");assertThat(task.getSendStatus()).isEqualTo("SKIPPED");assertThat(task.decision().replyAllowed()).isFalse();assertThat(task.getReplyContent()).isNull();}
 @Test void clearsCandidateTextAfterCompletionAndKeepsDecision(){Instant now=Instant.parse("2026-09-07T05:00:00Z");InboundAiReplyTask task=new InboundAiReplyTask(UUID.randomUUID(),UUID.randomUUID(),UUID.randomUUID(),"a".repeat(64),"b".repeat(64),"候选人的岗位问题",now);task.start(now.plusSeconds(1));task.complete(new InboundJobReplyService.Decision(true,"LOCATION",0.96,"工作地点为广州。","事实校验通过"),now.plusSeconds(2));assertThat(task.getStatus()).isEqualTo("COMPLETED");assertThat(task.getMessageText()).isNull();assertThat(task.decision().replyAllowed()).isTrue();assertThat(task.decision().category()).isEqualTo("LOCATION");}
 @Test void returnsStaleProcessingTaskToQueue(){Instant now=Instant.parse("2026-09-07T05:00:00Z");InboundAiReplyTask task=new InboundAiReplyTask(UUID.randomUUID(),UUID.randomUUID(),UUID.randomUUID(),"a".repeat(64),"b".repeat(64),"问题",now);task.start(now);task.recoverIfStale(now.plusSeconds(181));assertThat(task.getStatus()).isEqualTo("QUEUED");}
 @Test void waitsWithCandidateTextUntilRetryIsDue(){Instant now=Instant.parse("2026-09-07T05:00:00Z");InboundAiReplyTask task=new InboundAiReplyTask(UUID.randomUUID(),UUID.randomUUID(),UUID.randomUUID(),"a".repeat(64),"b".repeat(64),"问题",now);task.start(now);assertThat(task.retry("TIMEOUT","超时",now.plusSeconds(1))).isTrue();assertThat(task.getStatus()).isEqualTo("RETRY_WAIT");assertThat(task.getMessageText()).isEqualTo("问题");task.releaseRetry(now.plusSeconds(5));assertThat(task.getStatus()).isEqualTo("RETRY_WAIT");task.releaseRetry(now.plusSeconds(6));assertThat(task.getStatus()).isEqualTo("QUEUED");}
 @Test void stopsAfterThreeAttemptsAndClearsCandidateText(){Instant now=Instant.parse("2026-09-07T05:00:00Z");InboundAiReplyTask task=new InboundAiReplyTask(UUID.randomUUID(),UUID.randomUUID(),UUID.randomUUID(),"a".repeat(64),"b".repeat(64),"问题",now);for(int attempt=1;attempt<=3;attempt++){task.start(now.plusSeconds(attempt));boolean retrying=task.retry("TIMEOUT","第 "+attempt+" 次超时",now.plusSeconds(attempt));if(attempt<3){assertThat(retrying).isTrue();task.releaseRetry(task.getNextAttemptAt());}else assertThat(retrying).isFalse();}assertThat(task.getStatus()).isEqualTo("FAILED");assertThat(task.getMessageText()).isNull();assertThat(task.getAttemptCount()).isEqualTo(3);}
 @Test void sendLeaseCanOnlyBeClaimedAndCompletedOnce(){Instant now=Instant.parse("2026-09-07T05:00:00Z");UUID device=UUID.randomUUID();InboundAiReplyTask task=new InboundAiReplyTask(UUID.randomUUID(),UUID.randomUUID(),UUID.randomUUID(),"a".repeat(64),"b".repeat(64),"问题",now);task.start(now);task.complete(new InboundJobReplyService.Decision(true,"LOCATION",.98,"工作地点为广州。","已校验"),now.plusSeconds(1));assertThat(task.getSendStatus()).isEqualTo("READY");assertThat(task.claimSend(device,"c".repeat(64),"d".repeat(64),now.plusSeconds(2))).isTrue();assertThat(task.claimSend(device,"e".repeat(64),"f".repeat(64),now.plusSeconds(3))).isFalse();assertThat(task.receiptSend(device,"SUCCEEDED","d".repeat(64),"e".repeat(64),"f".repeat(64),"已确认",now.plusSeconds(4))).isTrue();assertThat(task.receiptSend(device,"SUCCEEDED","d".repeat(64),"e".repeat(64),"f".repeat(64),"已确认",now.plusSeconds(5))).isFalse();assertThat(task.getSendStatus()).isEqualTo("SUCCEEDED");assertThatThrownBy(()->task.receiptSend(device,"UNKNOWN","d".repeat(64),"a".repeat(64),"b".repeat(64),"冲突",now.plusSeconds(6))).isInstanceOf(IllegalStateException.class);}
 @Test void expiredSendLeaseBecomesUnknownAndCannotBeRetried(){Instant now=Instant.parse("2026-09-07T05:00:00Z");InboundAiReplyTask task=new InboundAiReplyTask(UUID.randomUUID(),UUID.randomUUID(),UUID.randomUUID(),"a".repeat(64),"b".repeat(64),"问题",now);task.start(now);task.complete(new InboundJobReplyService.Decision(true,"GREETING",.95,"您好，当前岗位正在招聘。","已校验"),now.plusSeconds(1));task.claimSend(UUID.randomUUID(),"c".repeat(64),"d".repeat(64),now.plusSeconds(2));task.expireSendLease(now.plusSeconds(33));assertThat(task.getSendStatus()).isEqualTo("UNKNOWN");assertThat(task.claimSend(UUID.randomUUID(),"e".repeat(64),"f".repeat(64),now.plusSeconds(34))).isFalse();}
 @Test void marksAValidatedPartialReplyForHrFollowUp(){Instant now=Instant.parse("2026-09-07T05:00:00Z");InboundAiReplyTask task=new InboundAiReplyTask(UUID.randomUUID(),UUID.randomUUID(),UUID.randomUUID(),"a".repeat(64),"b".repeat(64),"问题",now);task.start(now);task.complete(new InboundJobReplyService.Decision(true,"LOCATION",.95,"地点在广州，排班需要招聘人员确认。","已部分回答，仍需 HR 补充：OTHER_RECRUITMENT"),now.plusSeconds(1));assertThat(task.isPartialReply()).isTrue();}
 @Test void shadowEvaluationKeepsCandidateReplyWithoutMakingItSendable(){Instant now=Instant.parse("2026-09-07T05:00:00Z");InboundAiReplyTask task=new InboundAiReplyTask(UUID.randomUUID(),UUID.randomUUID(),UUID.randomUUID(),"a".repeat(64),"b".repeat(64),"工资多少",now);task.start(now);task.complete(new InboundJobReplyService.Decision(true,"SALARY",.97,"薪资范围是 8-13K。","事实校验通过").asShadowEvaluation(),now.plusSeconds(1));assertThat(task.getSendStatus()).isEqualTo("SKIPPED");assertThat(task.isShadowEvaluation()).isTrue();assertThat(task.wasReplyApproved()).isTrue();assertThat(task.getReplyContent()).isEqualTo("薪资范围是 8-13K。");}
}
