package ai.xzkj.recruitment.browsercompanion;

import ai.xzkj.recruitment.audit.AuditService;import ai.xzkj.recruitment.auth.*;import ai.xzkj.recruitment.autoreply.*;import ai.xzkj.recruitment.boss.*;import ai.xzkj.recruitment.candidates.*;import ai.xzkj.recruitment.common.ApiException;import ai.xzkj.recruitment.organization.Company;import org.springframework.beans.factory.annotation.Value;import org.springframework.http.HttpStatus;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
import java.nio.charset.StandardCharsets;import java.security.*;import java.time.*;import java.util.*;

@Service public class BrowserCompanionService{
 private final BrowserDeviceRepository devices;private final BrowserPairingCodeRepository pairings;private final BrowserConversationBindingRepository bindings;private final BrowserSendClaimRepository claims;private final AutoReplyPolicyRepository policies;private final BossAccountRepository accounts;private final CandidateJobContactRepository contacts;private final ConversationMessageRepository messages;private final CurrentUserService users;private final AuditService audit;private final boolean monitorOnly;private final SecureRandom random=new SecureRandom();
 public BrowserCompanionService(BrowserDeviceRepository d,BrowserPairingCodeRepository p,BrowserConversationBindingRepository b,BrowserSendClaimRepository claims,AutoReplyPolicyRepository policies,BossAccountRepository a,CandidateJobContactRepository c,ConversationMessageRepository m,CurrentUserService u,AuditService audit,@Value("${app.browser.monitor-only:true}")boolean monitorOnly){devices=d;pairings=p;bindings=b;this.claims=claims;this.policies=policies;accounts=a;contacts=c;messages=m;users=u;this.audit=audit;this.monitorOnly=monitorOnly;}

 @Transactional public PairingResponse createPairing(UUID accountId){SystemUser user=users.requireCurrentUser();BossAccount account=requireAccount(accountId,user);String token=token();BrowserPairingCode code=pairings.save(new BrowserPairingCode(account,hash(token),user));audit.success("CREATE_BROWSER_PAIRING","BOSS_ACCOUNT",accountId,account.getDisplayName(),"创建 10 分钟有效的浏览器设备配对令牌，令牌正文不入库");return new PairingResponse(token,code.getExpiresAt(),accountId,account.getDisplayName());}
 @Transactional public DeviceCredentialsResponse pair(PairDeviceRequest request){BrowserPairingCode code=pairings.findByTokenHash(hash(request.pairingToken().trim())).orElseThrow(()->bad("PAIRING_TOKEN_INVALID","配对令牌无效"));if(!code.usable(Instant.now()))throw bad("PAIRING_TOKEN_EXPIRED","配对令牌已使用或过期");devices.findFirstByBossAccountIdAndStatus(code.getAccount().getId(),"ACTIVE").ifPresent(d->{d.revoke();devices.flush();});String raw=token();BrowserDevice device=devices.save(new BrowserDevice(code.getAccount(),clean(request.deviceName(),100),hash(raw),code.getCreatedBy()));code.use();audit.systemSuccess("PAIR_BROWSER_DEVICE","BOSS_ACCOUNT",code.getAccount().getId(),code.getAccount().getDisplayName(),"浏览器设备已配对，设备令牌正文不入库");return new DeviceCredentialsResponse(device.getId(),raw,code.getAccount().getId(),code.getAccount().getDisplayName());}
 @Transactional(readOnly=true) public List<DeviceResponse> list(){SystemUser user=users.requireCurrentUser();return devices.findAllByOrderByCreatedAtDesc().stream().filter(d->canAccess(d.getBossAccount().getCompany().getId(),user)).map(DeviceResponse::from).toList();}
 @Transactional public void revoke(UUID id){SystemUser user=requireManager();BrowserDevice device=devices.findById(id).orElseThrow(()->bad("DEVICE_NOT_FOUND","浏览器设备不存在"));requireAccess(device.getBossAccount().getCompany().getId(),user);device.revoke();audit.success("REVOKE_BROWSER_DEVICE","BROWSER_DEVICE",id,device.getDisplayName(),"撤销浏览器设备令牌");}
 @Transactional public BindingResponse bind(UUID accountId,BindConversationRequest request){SystemUser user=requireManager();BossAccount account=requireAccount(accountId,user);CandidateJobContact contact=contacts.findWithDetailsById(request.contactId()).orElseThrow(()->bad("CONTACT_NOT_FOUND","候选人职位关系不存在"));if(!contact.getBossAccount().getId().equals(accountId))throw bad("ACCOUNT_CONTACT_MISMATCH","会话只能绑定到同一 BOSS 账号的候选人");String key=hash(request.externalChatId().trim());BrowserConversationBinding existing=bindings.findByAccountIdAndExternalChatKey(accountId,key).orElse(null);if(existing!=null&&!existing.getContact().getId().equals(contact.getId()))throw bad("CHAT_ALREADY_BOUND","该网页会话已绑定其他候选人");if(existing!=null)return BindingResponse.from(existing);if(bindings.existsByContactId(contact.getId()))throw bad("CONTACT_ALREADY_BOUND","该候选人已绑定网页会话");BrowserConversationBinding binding=bindings.save(new BrowserConversationBinding(account,contact,key,cleanOptional(request.displayHint(),120),user));audit.success("BIND_BROWSER_CONVERSATION","CANDIDATE_CONTACT",contact.getId(),account.getDisplayName(),"绑定脱敏网页会话键，不记录原始会话 ID");return BindingResponse.from(binding);}
 @Transactional public DeviceResponse heartbeat(String authorization,HeartbeatRequest request){BrowserDevice device=authenticate(authorization);device.heartbeat(request.state(),cleanOptional(request.reason(),300));return DeviceResponse.from(device);}
 @Transactional public BrowserRuntimePolicyResponse runtimePolicy(String authorization){BrowserDevice device=authenticate(authorization);Instant now=Instant.now();AutoReplyPolicy p=policies.findByBossAccountId(device.getBossAccount().getId()).orElse(null);if(p==null)return new BrowserRuntimePolicyResponse(false,false,AwayMode.IN_OFFICE.name(),null,false,120,20,0,180,"09:00","21:00","Asia/Shanghai",AutoReplyService.DEFAULT_TEMPLATE,now,null,null);p.prepareQuota(LocalDate.now(ZoneId.of(p.getTimezone())));return new BrowserRuntimePolicyResponse(true,p.isAwayActive(now),p.getAwayMode().name(),p.getAwayEndsAt(),!monitorOnly&&p.isAutoSendEnabled(),p.getResponseTimeoutMinutes(),p.getDailyLimit(),p.getSentToday(),p.getMinimumIntervalSeconds(),p.getSendingWindowStart().toString(),p.getSendingWindowEnd().toString(),p.getTimezone(),p.getReplyTemplate(),now,p.getLastSentAt(),p.getPausedUntil());}
 @Transactional public SyncMessageResponse sync(String authorization,SyncMessageRequest request){BrowserDevice device=authenticate(authorization);Instant now=Instant.now();if(request.createdAt().isAfter(now.plusSeconds(300))||request.createdAt().isBefore(now.minus(Duration.ofDays(30))))throw bad("MESSAGE_TIME_INVALID","网页消息时间必须在最近 30 天内且不能晚于当前时间");String chatKey=hash(request.externalChatId().trim());BrowserConversationBinding binding=bindings.findByAccountIdAndExternalChatKey(device.getBossAccount().getId(),chatKey).orElse(null);if(binding==null)return new SyncMessageResponse(false,false,null,null,"REQUIRES_BINDING");CandidateJobContact contact=binding.getContact();Optional<ConversationMessage> replay=messages.findByContactIdAndExternalMessageId(contact.getId(),request.externalMessageId().trim());if(replay.isPresent())return new SyncMessageResponse(true,true,contact.getId(),replay.get().getId(),"IGNORED_REPLAY");boolean inbound=request.direction().equals("INBOUND");String content=cleanOptional(request.content(),3000);if(content==null)content="[浏览器伴随端未同步消息正文]";ConversationMessage message=messages.save(new ConversationMessage(contact,request.externalMessageId().trim(),inbound?MessageDirection.INBOUND:MessageDirection.OUTBOUND,inbound?MessageSenderType.CANDIDATE:MessageSenderType.HR,inbound?MessageDeliveryStatus.RECEIVED:MessageDeliveryStatus.SENT,content,null,null,null,request.createdAt()));if(!inbound)contact.markContacting();audit.systemSuccess("SYNC_BROWSER_MESSAGE","CANDIDATE_CONTACT",contact.getId(),device.getBossAccount().getDisplayName(),"同步网页"+(inbound?"来信":"HR 外发")+"，不记录消息正文");return new SyncMessageResponse(false,true,contact.getId(),message.getId(),inbound?"INBOUND_STORED":"OUTBOUND_STORED");}
 @Transactional public SendClaimResponse claim(String authorization,CreateSendClaimRequest request){
  BrowserDevice device=authenticate(authorization);Instant now=Instant.now();
  if(monitorOnly)return denied("MONITOR_ONLY",null);
  BrowserConversationBinding binding=bindings.findByAccountIdAndExternalChatKey(device.getBossAccount().getId(),hash(request.externalChatId().trim())).orElse(null);
  if(binding==null)return denied("REQUIRES_BINDING",null);
  CandidateJobContact contact=binding.getContact();if(contact.isHumanTakenOver())return denied("HUMAN_TAKEN_OVER",null);
  ConversationMessage inbound=messages.findByContactIdAndExternalMessageId(contact.getId(),request.inboundExternalMessageId().trim()).orElse(null);
  if(inbound==null||inbound.getDirection()!=MessageDirection.INBOUND)return denied("INBOUND_NOT_SYNCED",null);
  ConversationMessage latest=messages.findFirstByContactIdOrderByCreatedAtDescIdDesc(contact.getId()).orElse(null);
  if(latest==null||!latest.getId().equals(inbound.getId()))return denied("NOT_LATEST_INBOUND",null);
  BrowserSendClaim existing=claims.findByInboundMessageId(inbound.getId()).orElse(null);
  if(existing!=null)return new SendClaimResponse(false,"ALREADY_CLAIMED",existing.getId(),existing.getLeaseUntil(),0,0);
  AutoReplyPolicy found=policies.findByBossAccountId(device.getBossAccount().getId()).orElse(null);if(found==null)return denied("POLICY_NOT_CONFIGURED",null);
  AutoReplyPolicy policy=policies.findLockedById(found.getId()).orElseThrow();ZoneId zone=ZoneId.of(policy.getTimezone());policy.prepareQuota(LocalDate.now(zone));
  existing=claims.findByInboundMessageId(inbound.getId()).orElse(null);if(existing!=null)return new SendClaimResponse(false,"ALREADY_CLAIMED",existing.getId(),existing.getLeaseUntil(),policy.getSentToday(),policy.getDailyLimit());
  if(!policy.isAwayActive(now))return denied("AWAY_MODE_INACTIVE",policy);
  if(!policy.isAutoSendEnabled())return denied("AUTOMATIC_SEND_DISABLED",policy);
  if(!policy.canSend(now))return denied("POLICY_PAUSED",policy);
  if(policy.getSentToday()>=policy.getDailyLimit())return denied("DAILY_LIMIT_REACHED",policy);
  if(!policy.intervalElapsed(now))return denied("MINIMUM_INTERVAL",policy);
  if(!insideWindow(now.atZone(zone).toLocalTime(),policy.getSendingWindowStart(),policy.getSendingWindowEnd()))return denied("OUTSIDE_WINDOW",policy);
  if(inbound.getCreatedAt().plus(Duration.ofMinutes(policy.getResponseTimeoutMinutes())).isAfter(now))return denied("NOT_TIMED_OUT",policy);
  BrowserSendClaim claim=claims.save(new BrowserSendClaim(device,binding,inbound,request.replyDigest().toLowerCase(Locale.ROOT),now));
  audit.systemSuccess("CLAIM_BROWSER_SEND","CANDIDATE_CONTACT",contact.getId(),device.getBossAccount().getDisplayName(),"为超时来信预留一次网页回复权");
  return new SendClaimResponse(true,"SEND",claim.getId(),claim.getLeaseUntil(),policy.getSentToday(),policy.getDailyLimit());
 }
 @Transactional public SendReceiptResponse receipt(String authorization,UUID id,SendReceiptRequest request){
  BrowserDevice device=authenticate(authorization);BrowserSendClaim claim=claims.findByIdAndDeviceId(id,device.getId()).orElseThrow(()->bad("SEND_CLAIM_NOT_FOUND","发送预留不存在"));
  AutoReplyPolicy found=policies.findByBossAccountId(device.getBossAccount().getId()).orElseThrow(()->bad("POLICY_NOT_CONFIGURED","自动回复策略未配置"));AutoReplyPolicy policy=policies.findLockedById(found.getId()).orElseThrow();Instant now=Instant.now();policy.prepareQuota(LocalDate.now(ZoneId.of(policy.getTimezone())));
  if(!claim.getStatus().equals("CLAIMED"))return new SendReceiptResponse(claim.getStatus(),policy.getSentToday(),policy.getLastSentAt(),policy.getPausedUntil());
  if(request.status().equals("SENT")){
   String external=cleanOptional(request.externalOutboundMessageId(),120);if(external==null)throw bad("OUTBOUND_MESSAGE_ID_REQUIRED","确认发送成功时必须提供网页消息 ID");
   CandidateJobContact contact=claim.getBinding().getContact();ConversationMessage outbound=messages.findByContactIdAndExternalMessageId(contact.getId(),external).orElseGet(()->messages.save(new ConversationMessage(contact,external,MessageDirection.OUTBOUND,MessageSenderType.HR,MessageDeliveryStatus.SENT,"[浏览器伴随端已确认发送]",null,null,null,now)));
   claim.sent(outbound,now);policy.sent(now);contact.markContacting();audit.systemSuccess("CONFIRM_BROWSER_SEND","CANDIDATE_CONTACT",contact.getId(),device.getBossAccount().getDisplayName(),"网页 DOM 已确认外发成功");
  }else{claim.unknown(now);policy.failed(now);audit.systemSuccess("UNKNOWN_BROWSER_SEND","BROWSER_SEND_CLAIM",id,device.getDisplayName(),"发送结果无法从 DOM 确认，禁止自动重试");}
  return new SendReceiptResponse(claim.getStatus(),policy.getSentToday(),policy.getLastSentAt(),policy.getPausedUntil());
 }
 @Transactional(readOnly=true) public BrowserDevice authenticate(String header){if(header==null||!header.startsWith("Device "))throw unauthorized();String raw=header.substring(7).trim();if(raw.length()<20)throw unauthorized();return devices.findByTokenHashAndStatus(hash(raw),"ACTIVE").orElseThrow(this::unauthorized);}
 private BossAccount requireAccount(UUID id,SystemUser user){BossAccount a=accounts.findWithDetailsById(id).orElseThrow(()->bad("BOSS_ACCOUNT_NOT_FOUND","BOSS 账号不存在"));requireAccess(a.getCompany().getId(),user);return a;}private SystemUser requireManager(){SystemUser u=users.requireCurrentUser();if(u.getRole()==UserRole.RECRUITER)throw new ApiException(HttpStatus.FORBIDDEN,"FORBIDDEN","当前账号没有浏览器设备管理权限");return u;}private void requireAccess(UUID c,SystemUser u){if(!canAccess(c,u))throw new ApiException(HttpStatus.FORBIDDEN,"COMPANY_SCOPE_FORBIDDEN","当前账号无权访问该企业数据");}private boolean canAccess(UUID c,SystemUser u){return u.getRole()==UserRole.SYSTEM_ADMIN||u.getCompanyScopes().stream().map(Company::getId).anyMatch(c::equals);}private ApiException bad(String code,String msg){return new ApiException(HttpStatus.BAD_REQUEST,code,msg);}private ApiException unauthorized(){return new ApiException(HttpStatus.UNAUTHORIZED,"DEVICE_UNAUTHORIZED","浏览器设备令牌无效或已撤销");}
 private String token(){byte[] bytes=new byte[32];random.nextBytes(bytes);return Base64.getUrlEncoder().withoutPadding().encodeToString(bytes);}private String hash(String v){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(v.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}private String clean(String v,int max){String c=v.trim();return c.length()<=max?c:c.substring(0,max);}private String cleanOptional(String v,int max){if(v==null||v.isBlank())return null;return clean(v,max);}
 private SendClaimResponse denied(String action,AutoReplyPolicy p){return new SendClaimResponse(false,action,null,null,p==null?0:p.getSentToday(),p==null?0:p.getDailyLimit());}
 private boolean insideWindow(LocalTime now,LocalTime start,LocalTime end){return start.isBefore(end)?(!now.isBefore(start)&&now.isBefore(end)):(!now.isBefore(start)||now.isBefore(end));}
}
