package ai.xzkj.recruitment.browsercompanion;
import ai.xzkj.recruitment.auth.SystemUser;import ai.xzkj.recruitment.boss.BossAccount;import jakarta.persistence.*;import java.time.Instant;import java.util.UUID;
@Entity @Table(name="browser_unread_observations") public class BrowserUnreadObservation{
 @Id private UUID id;@ManyToOne(fetch=FetchType.LAZY,optional=false)@JoinColumn(name="browser_device_id")private BrowserDevice device;@ManyToOne(fetch=FetchType.LAZY,optional=false)@JoinColumn(name="boss_account_id")private BossAccount account;@Column(name="chat_digest",nullable=false,length=64)private String chatDigest;@Column(name="preview_digest",length=64)private String previewDigest;@Column(name="job_digest",length=64)private String jobDigest;@Column(name="observed_job_title",length=120)private String observedJobTitle;@Column(name="time_digest",length=64)private String timeDigest;@Column(name="unread_count",nullable=false)private int unreadCount;@Column(nullable=false)private boolean unread;@Column(name="draft_mode",length=24)private String draftMode;@Column(name="draft_content",columnDefinition="TEXT")private String draftContent;@Column(name="draft_reason",length=200)private String draftReason;@Column(name="draft_generated_at")private Instant draftGeneratedAt;@Column(name="eligibility_status",nullable=false,length=32)private String eligibilityStatus="OBSERVING";@Column(name="latest_message_digest",length=64)private String latestMessageDigest;@Column(name="latest_direction",length=16)private String latestDirection;@Column(name="latest_message_at")private Instant latestMessageAt;@Column(name="detail_verified_at")private Instant detailVerifiedAt;@Column(name="review_status",nullable=false,length=24)private String reviewStatus="PENDING";@Column(name="reviewed_content",columnDefinition="TEXT")private String reviewedContent;@ManyToOne(fetch=FetchType.LAZY)@JoinColumn(name="reviewed_by")private SystemUser reviewedBy;@Column(name="reviewed_at")private Instant reviewedAt;@Column(name="review_note",length=300)private String reviewNote;@Column(name="fill_status",nullable=false,length=24)private String fillStatus="NONE";@Column(name="fill_claim_id")private UUID fillClaimId;@ManyToOne(fetch=FetchType.LAZY)@JoinColumn(name="fill_device_id")private BrowserDevice fillDevice;@Column(name="fill_lease_until")private Instant fillLeaseUntil;@Column(name="filled_at")private Instant filledAt;@Column(name="resolution_status",nullable=false,length=32)private String resolutionStatus="UNRESOLVED";@Column(name="resolved_at")private Instant resolvedAt;@Column(name="first_seen_at",nullable=false)private Instant firstSeenAt;@Column(name="last_seen_at",nullable=false)private Instant lastSeenAt;@Column(name="updated_at",nullable=false)private Instant updatedAt;
 protected BrowserUnreadObservation(){}BrowserUnreadObservation(BrowserDevice d,String chat,Instant first,Instant now){id=UUID.randomUUID();device=d;account=d.getBossAccount();chatDigest=chat;firstSeenAt=first;lastSeenAt=now;updatedAt=now;unread=false;}
 void observe(UnreadObservationEntry e,Instant now){previewDigest=e.previewDigest();jobDigest=e.jobDigest();observedJobTitle=clean(e.jobTitle());timeDigest=e.timeDigest();unreadCount=e.unreadCount();if(unreadCount>0&&!unread)startNewCycle(now);unread=unreadCount>0;if(e.firstSeenAt()!=null&&e.firstSeenAt().isBefore(firstSeenAt))firstSeenAt=e.firstSeenAt();lastSeenAt=e.lastSeenAt()==null?now:e.lastSeenAt();updatedAt=now;}
 void prepareDraft(String mode,String content,String reason,Instant now){draftMode=mode;draftContent=content;draftReason=reason;draftGeneratedAt=now;}
 void verifyDetail(String messageDigest,String direction,Instant messageAt,boolean selectedUnread,Instant now){latestMessageDigest=messageDigest;latestDirection=direction;latestMessageAt=messageAt;detailVerifiedAt=now;if("OUTBOUND".equals(direction)){unread=false;eligibilityStatus="HR_REPLIED";resolutionStatus="FILLED".equals(fillStatus)?"HR_SENT_AFTER_DRAFT":"HR_REPLIED";resolvedAt=now;if("CLAIMED".equals(fillStatus)){fillStatus="UNKNOWN";fillLeaseUntil=null;}else if("READY".equals(fillStatus))fillStatus="NONE";}else eligibilityStatus="OBSERVING";updatedAt=now;}
 void evaluate(Instant now,int timeoutMinutes,boolean awayActive){if(!unread){eligibilityStatus="HR_HANDLED";return;}if(!"PENDING".equals(reviewStatus)){eligibilityStatus=switch(reviewStatus){case"APPROVED"->"APPROVED_DRAFT";case"REJECTED"->"REJECTED";default->"HUMAN_TAKEOVER";};return;}if(!awayActive){eligibilityStatus="AWAY_INACTIVE";return;}if(detailVerifiedAt==null||detailVerifiedAt.isBefore(now.minusSeconds(180))){eligibilityStatus="DETAIL_REQUIRED";return;}if(!"INBOUND".equals(latestDirection)){eligibilityStatus="HR_REPLIED";return;}eligibilityStatus=firstSeenAt.plusSeconds(timeoutMinutes*60L).isAfter(now)?"OBSERVING":"READY_FOR_REVIEW";}
 void review(String decision,String content,String note,SystemUser user,Instant now){reviewStatus=decision;reviewedContent="APPROVED".equals(decision)?content:null;reviewNote=note;reviewedBy=user;reviewedAt=now;eligibilityStatus=switch(decision){case"APPROVED"->"APPROVED_DRAFT";case"REJECTED"->"REJECTED";default->"HUMAN_TAKEOVER";};fillStatus="APPROVED".equals(decision)?"READY":"NONE";fillClaimId=null;fillDevice=null;fillLeaseUntil=null;updatedAt=now;}
 boolean claimFill(BrowserDevice device,Instant now){if(!"READY".equals(fillStatus)&&!("CLAIMED".equals(fillStatus)&&fillLeaseUntil!=null&&!fillLeaseUntil.isAfter(now)))return false;fillStatus="CLAIMED";fillClaimId=UUID.randomUUID();fillDevice=device;fillLeaseUntil=now.plusSeconds(120);updatedAt=now;return true;}
 void finishFill(String result,Instant now){fillStatus="FILLED".equals(result)?"FILLED":"UNKNOWN";filledAt="FILLED".equals(result)?now:null;fillLeaseUntil=null;updatedAt=now;}
 boolean expireFill(Instant now){if(!"CLAIMED".equals(fillStatus)||fillLeaseUntil==null||fillLeaseUntil.isAfter(now))return false;fillStatus="UNKNOWN";fillLeaseUntil=null;updatedAt=now;return true;}
 private void startNewCycle(Instant now){unread=false;firstSeenAt=now;eligibilityStatus="OBSERVING";latestMessageDigest=null;latestDirection=null;latestMessageAt=null;detailVerifiedAt=null;reviewStatus="PENDING";reviewedContent=null;reviewedBy=null;reviewedAt=null;reviewNote=null;fillStatus="NONE";fillClaimId=null;fillDevice=null;fillLeaseUntil=null;filledAt=null;resolutionStatus="UNRESOLVED";resolvedAt=null;}
 private String clean(String value){if(value==null||value.isBlank())return null;String v=value.trim();return v.length()<=120?v:v.substring(0,120);}
 public UUID getId(){return id;}public BossAccount getAccount(){return account;}public String getChatDigest(){return chatDigest;}public String getPreviewDigest(){return previewDigest;}public String getJobDigest(){return jobDigest;}public String getObservedJobTitle(){return observedJobTitle;}public int getUnreadCount(){return unreadCount;}public boolean isUnread(){return unread;}public String getDraftMode(){return draftMode;}public String getDraftContent(){return draftContent;}public String getDraftReason(){return draftReason;}public Instant getDraftGeneratedAt(){return draftGeneratedAt;}public String getEligibilityStatus(){return eligibilityStatus;}public String getLatestMessageDigest(){return latestMessageDigest;}public String getLatestDirection(){return latestDirection;}public Instant getLatestMessageAt(){return latestMessageAt;}public Instant getDetailVerifiedAt(){return detailVerifiedAt;}public String getReviewStatus(){return reviewStatus;}public String getReviewedContent(){return reviewedContent;}public String getReviewNote(){return reviewNote;}public Instant getReviewedAt(){return reviewedAt;}public String getFillStatus(){return fillStatus;}public UUID getFillClaimId(){return fillClaimId;}public BrowserDevice getFillDevice(){return fillDevice;}public Instant getFillLeaseUntil(){return fillLeaseUntil;}public Instant getFilledAt(){return filledAt;}public String getResolutionStatus(){return resolutionStatus;}public Instant getResolvedAt(){return resolvedAt;}public Instant getFirstSeenAt(){return firstSeenAt;}public Instant getLastSeenAt(){return lastSeenAt;}
}
