package ai.xzkj.recruitment.browsercompanion;
import ai.xzkj.recruitment.boss.BossAccount;import jakarta.persistence.*;import java.time.Instant;import java.util.UUID;
@Entity @Table(name="browser_unread_observations") public class BrowserUnreadObservation{
 @Id private UUID id;@ManyToOne(fetch=FetchType.LAZY,optional=false)@JoinColumn(name="browser_device_id")private BrowserDevice device;@ManyToOne(fetch=FetchType.LAZY,optional=false)@JoinColumn(name="boss_account_id")private BossAccount account;@Column(name="chat_digest",nullable=false,length=64)private String chatDigest;@Column(name="preview_digest",length=64)private String previewDigest;@Column(name="job_digest",length=64)private String jobDigest;@Column(name="observed_job_title",length=120)private String observedJobTitle;@Column(name="time_digest",length=64)private String timeDigest;@Column(name="unread_count",nullable=false)private int unreadCount;@Column(nullable=false)private boolean unread;@Column(name="draft_mode",length=24)private String draftMode;@Column(name="draft_content",columnDefinition="TEXT")private String draftContent;@Column(name="draft_reason",length=200)private String draftReason;@Column(name="draft_generated_at")private Instant draftGeneratedAt;@Column(name="first_seen_at",nullable=false)private Instant firstSeenAt;@Column(name="last_seen_at",nullable=false)private Instant lastSeenAt;@Column(name="updated_at",nullable=false)private Instant updatedAt;
 protected BrowserUnreadObservation(){}BrowserUnreadObservation(BrowserDevice d,String chat,Instant first,Instant now){id=UUID.randomUUID();device=d;account=d.getBossAccount();chatDigest=chat;firstSeenAt=first;lastSeenAt=now;updatedAt=now;unread=true;}
 void observe(UnreadObservationEntry e,Instant now){previewDigest=e.previewDigest();jobDigest=e.jobDigest();observedJobTitle=clean(e.jobTitle());timeDigest=e.timeDigest();unreadCount=e.unreadCount();unread=unreadCount>0;if(e.firstSeenAt()!=null&&e.firstSeenAt().isBefore(firstSeenAt))firstSeenAt=e.firstSeenAt();lastSeenAt=e.lastSeenAt()==null?now:e.lastSeenAt();updatedAt=now;}
 void prepareDraft(String mode,String content,String reason,Instant now){draftMode=mode;draftContent=content;draftReason=reason;draftGeneratedAt=now;}
 private String clean(String value){if(value==null||value.isBlank())return null;String v=value.trim();return v.length()<=120?v:v.substring(0,120);}
 public UUID getId(){return id;}public BossAccount getAccount(){return account;}public String getChatDigest(){return chatDigest;}public String getPreviewDigest(){return previewDigest;}public String getJobDigest(){return jobDigest;}public String getObservedJobTitle(){return observedJobTitle;}public int getUnreadCount(){return unreadCount;}public boolean isUnread(){return unread;}public String getDraftMode(){return draftMode;}public String getDraftContent(){return draftContent;}public String getDraftReason(){return draftReason;}public Instant getDraftGeneratedAt(){return draftGeneratedAt;}public Instant getFirstSeenAt(){return firstSeenAt;}public Instant getLastSeenAt(){return lastSeenAt;}
}
