import {beforeEach,describe,expect,it,vi} from 'vitest'
import {apiClient} from '../api/client'
import {logisticsAuthorizationApi} from './logisticsAuthorizationApi'

vi.mock('../api/client',()=>({ApiError:class ApiError extends Error{},apiClient:{request:vi.fn()}}))

const authorization={id:'11111111-1111-4111-8111-111111111111',category:'PLATFORM',providerCode:'CHUDA',providerName:'触达物流',accountLabel:'华南发货账号',integrationMode:'DIRECT_CREDENTIALS',credentialConfigured:true,credentialType:'ENCRYPTED',contactName:null,note:null,status:'PENDING',createdByDisplayName:'ERP Tester',version:0,createdAt:'2026-08-11T00:00:00Z',updatedAt:'2026-08-11T00:00:00Z'}
const channel={id:'22222222-2222-4222-8222-222222222222',authorizationId:authorization.id,providerCode:'CHUDA',providerName:'触达物流',accountLabel:'华南发货账号',accountStatus:'ACTIVE',channelCode:'US-LINE',channelName:'美国专线',enabled:false,providerAvailable:true,effectiveEnabled:false,version:0,lastSyncedAt:'2026-08-11T00:01:00Z',updatedAt:'2026-08-11T00:01:00Z'}

describe('logisticsAuthorizationApi',()=>{
 beforeEach(()=>vi.mocked(apiClient.request).mockReset())

 it('gets one authorization for the dedicated channel workspace',async()=>{vi.mocked(apiClient.request).mockResolvedValue(authorization);expect((await logisticsAuthorizationApi.get(authorization.id)).accountLabel).toBe('华南发货账号');expect(apiClient.request).toHaveBeenCalledWith(`/api/v1/logistics/authorizations/${authorization.id}`,expect.any(Object))})

 it('sends direct credentials unchanged and maps the redacted response',async()=>{vi.mocked(apiClient.request).mockResolvedValue(authorization);const result=await logisticsAuthorizationApi.create({category:'PLATFORM',providerCode:'CHUDA',providerName:'触达物流',accountLabel:'华南发货账号',integrationMode:'DIRECT_CREDENTIALS',credentials:{username:'user',password:' secret with spaces '}});expect(result.credentialType).toBe('ENCRYPTED');expect(apiClient.request).toHaveBeenCalledWith('/api/v1/logistics/authorizations',expect.objectContaining({method:'POST',body:expect.objectContaining({credentials:{username:'user',password:' secret with spaces '}})}))})

 it('maps a connection probe without accepting secret-shaped response fields',async()=>{vi.mocked(apiClient.request).mockResolvedValue({authorization,status:'NOT_CONFIGURED',message:'账号信息已安全保存。'});const result=await logisticsAuthorizationApi.probe(authorization.id,0);expect(result.status).toBe('NOT_CONFIGURED');expect(result.authorization.providerCode).toBe('CHUDA');expect(apiClient.request).toHaveBeenCalledWith(`/api/v1/logistics/authorizations/${authorization.id}/probe`,expect.objectContaining({method:'POST',body:{version:0}}))})

 it('replaces credentials without accepting them back from the server',async()=>{vi.mocked(apiClient.request).mockResolvedValue({...authorization,version:1});const result=await logisticsAuthorizationApi.replaceCredentials(authorization.id,0,{username:'web@example.com',password:' new secret '});expect(result.version).toBe(1);expect(apiClient.request).toHaveBeenCalledWith(`/api/v1/logistics/authorizations/${authorization.id}/credentials`,expect.objectContaining({method:'PUT',body:{version:0,credentials:{username:'web@example.com',password:' new secret '}}}))})

 it('renames a freight account without sending credentials',async()=>{vi.mocked(apiClient.request).mockResolvedValue({...authorization,accountLabel:'美西仓账号',version:1});const result=await logisticsAuthorizationApi.rename(authorization.id,0,'美西仓账号');expect(result.accountLabel).toBe('美西仓账号');expect(apiClient.request).toHaveBeenCalledWith(`/api/v1/logistics/authorizations/${authorization.id}/name`,expect.objectContaining({method:'PUT',body:{version:0,accountLabel:'美西仓账号'}}))})

 it('disables, enables, and unbinds an account through explicit lifecycle endpoints',async()=>{vi.mocked(apiClient.request).mockResolvedValueOnce({...authorization,status:'ARCHIVED',version:1}).mockResolvedValueOnce({...authorization,status:'PENDING',version:2}).mockResolvedValueOnce({id:authorization.id});expect((await logisticsAuthorizationApi.disable(authorization.id,0)).status).toBe('ARCHIVED');expect((await logisticsAuthorizationApi.enable(authorization.id,1)).status).toBe('PENDING');expect(await logisticsAuthorizationApi.unbind(authorization.id,2)).toEqual({id:authorization.id});expect(apiClient.request).toHaveBeenNthCalledWith(1,`/api/v1/logistics/authorizations/${authorization.id}/archive`,expect.objectContaining({method:'POST',body:{version:0}}));expect(apiClient.request).toHaveBeenNthCalledWith(2,`/api/v1/logistics/authorizations/${authorization.id}/enable`,expect.objectContaining({method:'POST',body:{version:1}}));expect(apiClient.request).toHaveBeenNthCalledWith(3,`/api/v1/logistics/authorizations/${authorization.id}/unbind`,expect.objectContaining({method:'POST',body:{version:2}}))})

 it('lists and explicitly enables provider channels',async()=>{vi.mocked(apiClient.request).mockResolvedValueOnce({items:[channel]}).mockResolvedValueOnce({...channel,enabled:true,effectiveEnabled:true,version:1});expect(await logisticsAuthorizationApi.listChannels(authorization.id)).toEqual([expect.objectContaining({channelName:'美国专线',effectiveEnabled:false})]);expect((await logisticsAuthorizationApi.enableChannel(authorization.id,channel.id,0)).effectiveEnabled).toBe(true);expect(apiClient.request).toHaveBeenNthCalledWith(1,`/api/v1/logistics/authorizations/${authorization.id}/channels`,expect.any(Object));expect(apiClient.request).toHaveBeenNthCalledWith(2,`/api/v1/logistics/authorizations/${authorization.id}/channels/${channel.id}/enable`,expect.objectContaining({method:'POST',body:{version:0}}))})

 it('rejects a response that omits the provider identity',async()=>{const{providerCode,...invalid}=authorization;vi.mocked(apiClient.request).mockResolvedValue({items:[invalid],page:0,size:25,totalElements:1,totalPages:1});await expect(logisticsAuthorizationApi.list({category:'PLATFORM',page:0,pageSize:25})).rejects.toThrow('Invalid logistics authorization response')})

 it('lists platform-managed provider names',async()=>{vi.mocked(apiClient.request).mockResolvedValue({items:[{providerCode:'CHUDA',providerName:'触达国际物流'}]});expect(await logisticsAuthorizationApi.listProviders()).toEqual([{providerCode:'CHUDA',providerName:'触达国际物流'}]);expect(apiClient.request).toHaveBeenCalledWith('/api/v1/logistics/authorizations/providers',expect.any(Object))})

 it('accepts both Shandianhou protocol variants from the provider catalog',async()=>{vi.mocked(apiClient.request).mockResolvedValue({items:[{providerCode:'SHANDIANHOU_XIAOBAO',providerName:'闪电猴（小包）'},{providerCode:'SHANDIANHOU_SHANGPAI',providerName:'闪电猴（商派）'}]});expect(await logisticsAuthorizationApi.listProviders()).toEqual([{providerCode:'SHANDIANHOU_XIAOBAO',providerName:'闪电猴（小包）'},{providerCode:'SHANDIANHOU_SHANGPAI',providerName:'闪电猴（商派）'}])})
})
