import { ApiError, apiClient } from '../api/client'

const BASE = '/api/v1/logistics/authorizations'
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i
export type AuthorizationCategory = 'PLATFORM'|'SELF_FULFILLED'|'FIRST_MILE'|'OVERSEAS'|'CLOUD_FACTORY'|'CUSTOM'
export type AuthorizationStatus = 'ACTIVE'|'PENDING'|'ARCHIVED'
export type IntegrationMode = 'MANUAL'|'CREDENTIAL_REFERENCE'|'DIRECT_CREDENTIALS'
export type ProviderCode = 'CHUDA'|'DAYUNJIA'|'BIAOJU'|'BAIDU_YIXIA'|'HUALEI'|'TONGXI'|'JIAYUN_SHENGTU'|'SHANDIANHOU_XIAOBAO'|'SHANDIANHOU_SHANGPAI'|'YUNEXPRESS'|'CUSTOM'
export type DirectCredentialsInput = {username:string;password:string;key?:string}
export type LogisticsProvider = {providerCode:ProviderCode;providerName:string}
export type LogisticsAuthorization = {id:string;category:AuthorizationCategory;providerCode:ProviderCode;providerName:string;accountLabel:string;integrationMode:IntegrationMode;credentialConfigured:boolean;credentialType?:'VAULT'|'CREDENTIAL'|'ENCRYPTED';contactName?:string;note?:string;status:AuthorizationStatus;createdByDisplayName:string;version:number;createdAt:string;updatedAt:string}
export type LogisticsAuthorizationChannel = {id:string;authorizationId:string;providerCode:ProviderCode;providerName:string;accountLabel:string;accountStatus:AuthorizationStatus;channelCode:string;channelName:string;enabled:boolean;providerAvailable:boolean;effectiveEnabled:boolean;version:number;lastSyncedAt:string;updatedAt:string}
export type LogisticsAuthorizationPage = {items:LogisticsAuthorization[];page:number;size:number;totalElements:number;totalPages:number}
export type LogisticsAuthorizationInput = {category:AuthorizationCategory;providerCode:ProviderCode;providerName:string;accountLabel:string;integrationMode:IntegrationMode;credentialReference?:string;credentials?:DirectCredentialsInput;contactName?:string;note?:string}
export type LogisticsProbeResult = {authorization:LogisticsAuthorization;status:'CONNECTED'|'NOT_CONFIGURED'|'REJECTED'|'UNAVAILABLE';message:string}
type Wire=Record<string,unknown>
function invalid(field:string):never{throw new ApiError('Invalid logistics authorization response',{status:502,code:'invalid_response',details:{field}})}
function record(value:unknown,field:string):Wire{if(!value||typeof value!=='object'||Array.isArray(value))invalid(field);return value as Wire}
function exact(value:Wire,fields:readonly string[],field:string){if(Object.keys(value).some(key=>!fields.includes(key))||fields.some(key=>!(key in value)))invalid(`${field}.shape`)}
function text(value:unknown,field:string){if(typeof value!=='string'||!value.trim())invalid(field);return value}
function optional(value:unknown,field:string){return value===null?undefined:text(value,field)}
function integer(value:unknown,field:string){if(typeof value!=='number'||!Number.isSafeInteger(value)||value<0)invalid(field);return value}
function bool(value:unknown,field:string){if(typeof value!=='boolean')invalid(field);return value}
const categories:AuthorizationCategory[]=['PLATFORM','SELF_FULFILLED','FIRST_MILE','OVERSEAS','CLOUD_FACTORY','CUSTOM']
const providerCodes:ReadonlyArray<ProviderCode>=['CHUDA','DAYUNJIA','BIAOJU','BAIDU_YIXIA','HUALEI','TONGXI','JIAYUN_SHENGTU','SHANDIANHOU_XIAOBAO','SHANDIANHOU_SHANGPAI','YUNEXPRESS','CUSTOM']
function item(value:unknown):LogisticsAuthorization{const w=record(value,'authorization');const fields=['id','category','providerCode','providerName','accountLabel','integrationMode','credentialConfigured','credentialType','contactName','note','status','createdByDisplayName','version','createdAt','updatedAt'];exact(w,fields,'authorization');const id=text(w.id,'authorization.id');if(!UUID.test(id))invalid('authorization.id');if(!categories.includes(w.category as AuthorizationCategory))invalid('authorization.category');if(!providerCodes.includes(w.providerCode as ProviderCode))invalid('authorization.providerCode');if(w.integrationMode!=='MANUAL'&&w.integrationMode!=='CREDENTIAL_REFERENCE'&&w.integrationMode!=='DIRECT_CREDENTIALS')invalid('authorization.integrationMode');if(w.status!=='ACTIVE'&&w.status!=='PENDING'&&w.status!=='ARCHIVED')invalid('authorization.status');if(typeof w.credentialConfigured!=='boolean')invalid('authorization.credentialConfigured');const credentialType=optional(w.credentialType,'authorization.credentialType');if(credentialType&&credentialType!=='VAULT'&&credentialType!=='CREDENTIAL'&&credentialType!=='ENCRYPTED')invalid('authorization.credentialType');const createdAt=text(w.createdAt,'authorization.createdAt'),updatedAt=text(w.updatedAt,'authorization.updatedAt');if(Number.isNaN(Date.parse(createdAt))||Number.isNaN(Date.parse(updatedAt)))invalid('authorization.time');return{id,category:w.category as AuthorizationCategory,providerCode:w.providerCode as ProviderCode,providerName:text(w.providerName,'authorization.providerName'),accountLabel:text(w.accountLabel,'authorization.accountLabel'),integrationMode:w.integrationMode,credentialConfigured:w.credentialConfigured,credentialType:credentialType as 'VAULT'|'CREDENTIAL'|'ENCRYPTED'|undefined,contactName:optional(w.contactName,'authorization.contactName'),note:optional(w.note,'authorization.note'),status:w.status,createdByDisplayName:text(w.createdByDisplayName,'authorization.createdByDisplayName'),version:integer(w.version,'authorization.version'),createdAt,updatedAt}}
function page(value:unknown):LogisticsAuthorizationPage{const w=record(value,'page');exact(w,['items','page','size','totalElements','totalPages'],'page');if(!Array.isArray(w.items))invalid('page.items');const result={items:w.items.map(item),page:integer(w.page,'page.page'),size:integer(w.size,'page.size'),totalElements:integer(w.totalElements,'page.totalElements'),totalPages:integer(w.totalPages,'page.totalPages')};if(result.size<1||result.items.length>result.size)invalid('page.size');return result}
function requestId(){return`logistics-authorization.${crypto.randomUUID()}`}
function probeResult(value:unknown):LogisticsProbeResult{const w=record(value,'probe');exact(w,['authorization','status','message'],'probe');if(w.status!=='CONNECTED'&&w.status!=='NOT_CONFIGURED'&&w.status!=='REJECTED'&&w.status!=='UNAVAILABLE')invalid('probe.status');return{authorization:item(w.authorization),status:w.status,message:text(w.message,'probe.message')}}
function unbindResult(value:unknown){const w=record(value,'unbind');exact(w,['id'],'unbind');const id=text(w.id,'unbind.id');if(!UUID.test(id))invalid('unbind.id');return{id}}
function channel(value:unknown):LogisticsAuthorizationChannel{const w=record(value,'channel');exact(w,['id','authorizationId','providerCode','providerName','accountLabel','accountStatus','channelCode','channelName','enabled','providerAvailable','effectiveEnabled','version','lastSyncedAt','updatedAt'],'channel');const id=text(w.id,'channel.id'),authorizationId=text(w.authorizationId,'channel.authorizationId');if(!UUID.test(id)||!UUID.test(authorizationId))invalid('channel.id');if(!providerCodes.includes(w.providerCode as ProviderCode))invalid('channel.providerCode');if(w.accountStatus!=='ACTIVE'&&w.accountStatus!=='PENDING'&&w.accountStatus!=='ARCHIVED')invalid('channel.accountStatus');const lastSyncedAt=text(w.lastSyncedAt,'channel.lastSyncedAt'),updatedAt=text(w.updatedAt,'channel.updatedAt');if(Number.isNaN(Date.parse(lastSyncedAt))||Number.isNaN(Date.parse(updatedAt)))invalid('channel.time');return{id,authorizationId,providerCode:w.providerCode as ProviderCode,providerName:text(w.providerName,'channel.providerName'),accountLabel:text(w.accountLabel,'channel.accountLabel'),accountStatus:w.accountStatus,channelCode:text(w.channelCode,'channel.channelCode'),channelName:text(w.channelName,'channel.channelName'),enabled:bool(w.enabled,'channel.enabled'),providerAvailable:bool(w.providerAvailable,'channel.providerAvailable'),effectiveEnabled:bool(w.effectiveEnabled,'channel.effectiveEnabled'),version:integer(w.version,'channel.version'),lastSyncedAt,updatedAt}}
function channels(value:unknown){const w=record(value,'channels');exact(w,['items'],'channels');if(!Array.isArray(w.items))invalid('channels.items');return w.items.map(channel)}
function provider(value:unknown):LogisticsProvider{const w=record(value,'provider');exact(w,['providerCode','providerName'],'provider');if(!providerCodes.includes(w.providerCode as ProviderCode))invalid('provider.providerCode');return{providerCode:w.providerCode as ProviderCode,providerName:text(w.providerName,'provider.providerName')}}
function providers(value:unknown){const w=record(value,'providers');exact(w,['items'],'providers');if(!Array.isArray(w.items))invalid('providers.items');return w.items.map(provider)}
export const logisticsAuthorizationApi={
 async listProviders(signal?:AbortSignal){return providers(await apiClient.request<unknown>(`${BASE}/providers`,{signal}))},
 async get(id:string,signal?:AbortSignal){return item(await apiClient.request<unknown>(`${BASE}/${id}`,{signal}))},
 async list(input:{category:AuthorizationCategory;name?:string;status?:AuthorizationStatus;page:number;pageSize:number;signal?:AbortSignal}){const p=new URLSearchParams({category:input.category,page:String(input.page),pageSize:String(input.pageSize)});if(input.name)p.set('name',input.name);if(input.status)p.set('status',input.status);return page(await apiClient.request<unknown>(`${BASE}?${p}`,{signal:input.signal}))},
 async create(input:LogisticsAuthorizationInput){return item(await apiClient.request<unknown>(BASE,{method:'POST',headers:{'X-Request-Id':requestId()},body:input}))},
 async rename(id:string,version:number,accountLabel:string){return item(await apiClient.request<unknown>(`${BASE}/${id}/name`,{method:'PUT',headers:{'X-Request-Id':requestId()},body:{version,accountLabel}}))},
 async replaceCredentials(id:string,version:number,credentials:DirectCredentialsInput){return item(await apiClient.request<unknown>(`${BASE}/${id}/credentials`,{method:'PUT',headers:{'X-Request-Id':requestId()},body:{version,credentials}}))},
 async probe(id:string,version:number){return probeResult(await apiClient.request<unknown>(`${BASE}/${id}/probe`,{method:'POST',headers:{'X-Request-Id':requestId()},body:{version}}))},
 async disable(id:string,version:number){return item(await apiClient.request<unknown>(`${BASE}/${id}/archive`,{method:'POST',headers:{'X-Request-Id':requestId()},body:{version}}))},
 async enable(id:string,version:number){return item(await apiClient.request<unknown>(`${BASE}/${id}/enable`,{method:'POST',headers:{'X-Request-Id':requestId()},body:{version}}))},
 async unbind(id:string,version:number){return unbindResult(await apiClient.request<unknown>(`${BASE}/${id}/unbind`,{method:'POST',headers:{'X-Request-Id':requestId()},body:{version}}))},
 async listChannels(id:string,signal?:AbortSignal){return channels(await apiClient.request<unknown>(`${BASE}/${id}/channels`,{signal}))},
 async listEnabledChannels(signal?:AbortSignal){return channels(await apiClient.request<unknown>(`${BASE}/enabled-channels`,{signal}))},
 async enableChannel(authorizationId:string,channelId:string,version:number){return channel(await apiClient.request<unknown>(`${BASE}/${authorizationId}/channels/${channelId}/enable`,{method:'POST',headers:{'X-Request-Id':requestId()},body:{version}}))},
 async disableChannel(authorizationId:string,channelId:string,version:number){return channel(await apiClient.request<unknown>(`${BASE}/${authorizationId}/channels/${channelId}/disable`,{method:'POST',headers:{'X-Request-Id':requestId()},body:{version}}))},
}
