// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {appcore} from '../models';
import {records} from '../models';

export function AddKnowledgeFromConversation(arg1:appcore.Conversation,arg2:string,arg3:string,arg4:string):Promise<appcore.ActionResult>;

export function AddShopProductCard(arg1:appcore.Shop,arg2:appcore.ProductCard):Promise<appcore.ActionResult>;

export function AttachOpenShop(arg1:appcore.Shop):Promise<appcore.ActionResult>;

export function Bootstrap():Promise<appcore.BootstrapState>;

export function BringSourcePageToFront(arg1:appcore.Conversation):Promise<appcore.ActionResult>;

export function CancelRead():Promise<appcore.ActionResult>;

export function ClassifyConversationRecord(arg1:appcore.Conversation):Promise<appcore.ActionResult>;

export function CompleteMailAuthorization(arg1:string):Promise<appcore.ActionResult>;

export function CompleteOutlookAuthorization(arg1:string):Promise<appcore.ActionResult>;

export function DeleteKnowledge(arg1:string):Promise<appcore.ActionResult>;

export function DeleteShopProductCard(arg1:appcore.Shop,arg2:string):Promise<appcore.ActionResult>;

export function DisableKnowledge(arg1:string):Promise<appcore.ActionResult>;

export function DisableShopMailAPI(arg1:string,arg2:boolean):Promise<appcore.ActionResult>;

export function ExportHandledRecords(arg1:string,arg2:string,arg3:string):Promise<appcore.ActionResult>;

export function ExportKnowledge(arg1:string):Promise<appcore.ActionResult>;

export function GenerateAIReply(arg1:appcore.Conversation):Promise<appcore.ActionResult>;

export function GetLogs(arg1:number):Promise<string>;

export function GetSettings():Promise<appcore.Settings>;

export function GetShopConversations(arg1:appcore.Shop):Promise<appcore.ActionResult>;

export function HideToTray():Promise<appcore.ActionResult>;

export function ImportKnowledge(arg1:string):Promise<appcore.ActionResult>;

export function ImportMailProxyBindings(arg1:string):Promise<appcore.ActionResult>;

export function ListKnowledge(arg1:boolean):Promise<appcore.ActionResult>;

export function ListRecordCategories():Promise<appcore.ActionResult>;

export function ListShops():Promise<appcore.ActionResult>;

export function MarkConversationHandled(arg1:appcore.Conversation):Promise<appcore.ActionResult>;

export function MarkHandled(arg1:string):Promise<appcore.ActionResult>;

export function OpenConversationLink(arg1:appcore.Conversation,arg2:string):Promise<appcore.ActionResult>;

export function OpenLogDirectory():Promise<appcore.ActionResult>;

export function OpenSourcePage(arg1:appcore.Conversation):Promise<appcore.ActionResult>;

export function PauseRead():Promise<appcore.ActionResult>;

export function ProbeAISettings():Promise<appcore.ActionResult>;

export function ProbeEmail():Promise<appcore.ActionResult>;

export function QuitApp():Promise<appcore.ActionResult>;

export function ReadAllOpenShops():Promise<appcore.ActionResult>;

export function ReadAllOpenShopsMailDefault():Promise<appcore.ActionResult>;

export function ReadAllOpenShopsMailViaAPI():Promise<appcore.ActionResult>;

export function ReadAllOpenShopsViaWeb():Promise<appcore.ActionResult>;

export function ReadAllShops():Promise<appcore.ActionResult>;

export function ReadAllShopsMailDefault():Promise<appcore.ActionResult>;

export function ReadAllShopsMailViaAPI():Promise<appcore.ActionResult>;

export function ReadAllShopsViaWeb():Promise<appcore.ActionResult>;

export function ReadLocalAsset(arg1:string):Promise<appcore.ActionResult>;

export function ReadShopInbox(arg1:appcore.Shop):Promise<appcore.ActionResult>;

export function ReadShopMailViaAPI(arg1:string,arg2:Record<string, any>):Promise<appcore.ActionResult>;

export function ReadShopMailViaWeb(arg1:string):Promise<appcore.ActionResult>;

export function ResumeRead():Promise<appcore.ActionResult>;

export function RuntimeInfo():Promise<appcore.ActionResult>;

export function SaveCuiqiuAuthorization(arg1:string,arg2:string,arg3:string,arg4:string):Promise<appcore.ActionResult>;

export function SaveRecordCategories(arg1:Array<records.CategoryOption>):Promise<appcore.ActionResult>;

export function SaveSettings(arg1:appcore.Settings):Promise<appcore.ActionResult>;

export function SaveShopServiceEmail(arg1:string,arg2:string):Promise<appcore.ActionResult>;

export function SelectKnowledgeExportFile():Promise<appcore.ActionResult>;

export function SelectKnowledgeImportFile():Promise<appcore.ActionResult>;

export function SelectMailProxyImportFile():Promise<appcore.ActionResult>;

export function SelectRecordExportFile(arg1:string,arg2:string):Promise<appcore.ActionResult>;

export function SendReply(arg1:appcore.Conversation,arg2:string):Promise<appcore.ActionResult>;

export function SetBackgroundMode(arg1:boolean):Promise<appcore.ActionResult>;

export function ShowMainWindow():Promise<appcore.ActionResult>;

export function StartGmailAuthorization(arg1:string):Promise<appcore.ActionResult>;

export function StartMailAuthorization(arg1:string):Promise<appcore.ActionResult>;

export function StartOutlookAuthorization(arg1:string):Promise<appcore.ActionResult>;

export function StartRealtimeObserve(arg1:appcore.Shop):Promise<appcore.ActionResult>;

export function StartZhanfuAPI():Promise<appcore.ActionResult>;

export function StopRealtimeObserve():Promise<appcore.ActionResult>;

export function SummarizeKnowledge():Promise<appcore.ActionResult>;

export function TestAISettings():Promise<appcore.ActionResult>;

export function TestBrowserSettings():Promise<appcore.ActionResult>;

export function TestShopMailProxy(arg1:string):Promise<appcore.ActionResult>;

export function TranslateCustomerContext(arg1:appcore.Conversation):Promise<appcore.ActionResult>;

export function TranslateReplyBoxText(arg1:string,arg2:appcore.Conversation,arg3:string):Promise<appcore.ActionResult>;

export function UpdateConversationRecordDraft(arg1:appcore.Conversation,arg2:records.ClassificationDraft):Promise<appcore.ActionResult>;
