// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddKnowledgeFromConversation(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddKnowledgeFromConversation'](arg1, arg2, arg3, arg4);
}

export function AddShopProductCard(arg1, arg2) {
  return window['go']['main']['App']['AddShopProductCard'](arg1, arg2);
}

export function AttachOpenShop(arg1) {
  return window['go']['main']['App']['AttachOpenShop'](arg1);
}

export function Bootstrap() {
  return window['go']['main']['App']['Bootstrap']();
}

export function BringSourcePageToFront(arg1) {
  return window['go']['main']['App']['BringSourcePageToFront'](arg1);
}

export function CancelRead() {
  return window['go']['main']['App']['CancelRead']();
}

export function ClassifyConversationRecord(arg1) {
  return window['go']['main']['App']['ClassifyConversationRecord'](arg1);
}

export function CompleteMailAuthorization(arg1) {
  return window['go']['main']['App']['CompleteMailAuthorization'](arg1);
}

export function CompleteOutlookAuthorization(arg1) {
  return window['go']['main']['App']['CompleteOutlookAuthorization'](arg1);
}

export function DeleteKnowledge(arg1) {
  return window['go']['main']['App']['DeleteKnowledge'](arg1);
}

export function DeleteShopProductCard(arg1, arg2) {
  return window['go']['main']['App']['DeleteShopProductCard'](arg1, arg2);
}

export function DisableKnowledge(arg1) {
  return window['go']['main']['App']['DisableKnowledge'](arg1);
}

export function DisableShopMailAPI(arg1, arg2) {
  return window['go']['main']['App']['DisableShopMailAPI'](arg1, arg2);
}

export function ExportHandledRecords(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportHandledRecords'](arg1, arg2, arg3);
}

export function ExportKnowledge(arg1) {
  return window['go']['main']['App']['ExportKnowledge'](arg1);
}

export function GenerateAIReply(arg1) {
  return window['go']['main']['App']['GenerateAIReply'](arg1);
}

export function GetLogs(arg1) {
  return window['go']['main']['App']['GetLogs'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetShopConversations(arg1) {
  return window['go']['main']['App']['GetShopConversations'](arg1);
}

export function HideToTray() {
  return window['go']['main']['App']['HideToTray']();
}

export function ImportKnowledge(arg1) {
  return window['go']['main']['App']['ImportKnowledge'](arg1);
}

export function ImportMailProxyBindings(arg1) {
  return window['go']['main']['App']['ImportMailProxyBindings'](arg1);
}

export function ListKnowledge(arg1) {
  return window['go']['main']['App']['ListKnowledge'](arg1);
}

export function ListRecordCategories() {
  return window['go']['main']['App']['ListRecordCategories']();
}

export function ListShops() {
  return window['go']['main']['App']['ListShops']();
}

export function MarkConversationHandled(arg1) {
  return window['go']['main']['App']['MarkConversationHandled'](arg1);
}

export function MarkHandled(arg1) {
  return window['go']['main']['App']['MarkHandled'](arg1);
}

export function OpenConversationLink(arg1, arg2) {
  return window['go']['main']['App']['OpenConversationLink'](arg1, arg2);
}

export function OpenLogDirectory() {
  return window['go']['main']['App']['OpenLogDirectory']();
}

export function OpenSourcePage(arg1) {
  return window['go']['main']['App']['OpenSourcePage'](arg1);
}

export function PauseRead() {
  return window['go']['main']['App']['PauseRead']();
}

export function ProbeAISettings() {
  return window['go']['main']['App']['ProbeAISettings']();
}

export function ProbeEmail() {
  return window['go']['main']['App']['ProbeEmail']();
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function ReadAllOpenShops() {
  return window['go']['main']['App']['ReadAllOpenShops']();
}

export function ReadAllOpenShopsMailDefault() {
  return window['go']['main']['App']['ReadAllOpenShopsMailDefault']();
}

export function ReadAllOpenShopsMailViaAPI() {
  return window['go']['main']['App']['ReadAllOpenShopsMailViaAPI']();
}

export function ReadAllOpenShopsViaWeb() {
  return window['go']['main']['App']['ReadAllOpenShopsViaWeb']();
}

export function ReadAllShops() {
  return window['go']['main']['App']['ReadAllShops']();
}

export function ReadAllShopsMailDefault() {
  return window['go']['main']['App']['ReadAllShopsMailDefault']();
}

export function ReadAllShopsMailViaAPI() {
  return window['go']['main']['App']['ReadAllShopsMailViaAPI']();
}

export function ReadAllShopsViaWeb() {
  return window['go']['main']['App']['ReadAllShopsViaWeb']();
}

export function ReadLocalAsset(arg1) {
  return window['go']['main']['App']['ReadLocalAsset'](arg1);
}

export function ReadShopInbox(arg1) {
  return window['go']['main']['App']['ReadShopInbox'](arg1);
}

export function ReadShopMailViaAPI(arg1, arg2) {
  return window['go']['main']['App']['ReadShopMailViaAPI'](arg1, arg2);
}

export function ReadShopMailViaWeb(arg1) {
  return window['go']['main']['App']['ReadShopMailViaWeb'](arg1);
}

export function ResumeRead() {
  return window['go']['main']['App']['ResumeRead']();
}

export function RuntimeInfo() {
  return window['go']['main']['App']['RuntimeInfo']();
}

export function SaveCuiqiuAuthorization(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveCuiqiuAuthorization'](arg1, arg2, arg3, arg4);
}

export function SaveRecordCategories(arg1) {
  return window['go']['main']['App']['SaveRecordCategories'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SaveShopServiceEmail(arg1, arg2) {
  return window['go']['main']['App']['SaveShopServiceEmail'](arg1, arg2);
}

export function SelectKnowledgeExportFile() {
  return window['go']['main']['App']['SelectKnowledgeExportFile']();
}

export function SelectKnowledgeImportFile() {
  return window['go']['main']['App']['SelectKnowledgeImportFile']();
}

export function SelectMailProxyImportFile() {
  return window['go']['main']['App']['SelectMailProxyImportFile']();
}

export function SelectRecordExportFile(arg1, arg2) {
  return window['go']['main']['App']['SelectRecordExportFile'](arg1, arg2);
}

export function SendReply(arg1, arg2) {
  return window['go']['main']['App']['SendReply'](arg1, arg2);
}

export function SetBackgroundMode(arg1) {
  return window['go']['main']['App']['SetBackgroundMode'](arg1);
}

export function ShowMainWindow() {
  return window['go']['main']['App']['ShowMainWindow']();
}

export function StartGmailAuthorization(arg1) {
  return window['go']['main']['App']['StartGmailAuthorization'](arg1);
}

export function StartMailAuthorization(arg1) {
  return window['go']['main']['App']['StartMailAuthorization'](arg1);
}

export function StartOutlookAuthorization(arg1) {
  return window['go']['main']['App']['StartOutlookAuthorization'](arg1);
}

export function StartRealtimeObserve(arg1) {
  return window['go']['main']['App']['StartRealtimeObserve'](arg1);
}

export function StartZhanfuAPI() {
  return window['go']['main']['App']['StartZhanfuAPI']();
}

export function StopRealtimeObserve() {
  return window['go']['main']['App']['StopRealtimeObserve']();
}

export function SummarizeKnowledge() {
  return window['go']['main']['App']['SummarizeKnowledge']();
}

export function TestAISettings() {
  return window['go']['main']['App']['TestAISettings']();
}

export function TestBrowserSettings() {
  return window['go']['main']['App']['TestBrowserSettings']();
}

export function TestShopMailProxy(arg1) {
  return window['go']['main']['App']['TestShopMailProxy'](arg1);
}

export function TranslateCustomerContext(arg1) {
  return window['go']['main']['App']['TranslateCustomerContext'](arg1);
}

export function TranslateReplyBoxText(arg1, arg2, arg3) {
  return window['go']['main']['App']['TranslateReplyBoxText'](arg1, arg2, arg3);
}

export function UpdateConversationRecordDraft(arg1, arg2) {
  return window['go']['main']['App']['UpdateConversationRecordDraft'](arg1, arg2);
}
