ALTER TABLE local_connector_unread_observations RENAME COLUMN browser_device_id TO local_connector_device_id;

ALTER TABLE local_connector_devices RENAME CONSTRAINT browser_companion_devices_pkey TO local_connector_devices_pkey;
ALTER TABLE local_connector_devices RENAME CONSTRAINT browser_companion_devices_token_hash_key TO local_connector_devices_token_hash_key;
ALTER TABLE local_connector_devices RENAME CONSTRAINT browser_companion_devices_boss_account_id_fkey TO local_connector_devices_boss_account_id_fkey;
ALTER TABLE local_connector_devices RENAME CONSTRAINT browser_companion_devices_paired_by_fkey TO local_connector_devices_paired_by_fkey;
ALTER TABLE local_connector_devices RENAME CONSTRAINT ck_browser_device_runtime TO ck_local_connector_device_runtime;
ALTER TABLE local_connector_devices RENAME CONSTRAINT ck_browser_device_status TO ck_local_connector_device_status;
ALTER INDEX idx_browser_device_heartbeat RENAME TO idx_local_connector_device_heartbeat;
ALTER INDEX uq_browser_active_device_per_account RENAME TO uq_local_connector_active_device_per_account;

ALTER TABLE local_connector_pairing_codes RENAME CONSTRAINT browser_pairing_codes_pkey TO local_connector_pairing_codes_pkey;
ALTER TABLE local_connector_pairing_codes RENAME CONSTRAINT browser_pairing_codes_token_hash_key TO local_connector_pairing_codes_token_hash_key;
ALTER TABLE local_connector_pairing_codes RENAME CONSTRAINT browser_pairing_codes_boss_account_id_fkey TO local_connector_pairing_codes_boss_account_id_fkey;
ALTER TABLE local_connector_pairing_codes RENAME CONSTRAINT browser_pairing_codes_created_by_fkey TO local_connector_pairing_codes_created_by_fkey;
ALTER INDEX idx_browser_pairing_expiry RENAME TO idx_local_connector_pairing_expiry;

UPDATE local_connector_unread_observations SET resolution_status='HR_REPLIED' WHERE resolution_status='HR_SENT_AFTER_DRAFT';
ALTER TABLE local_connector_unread_observations DROP CONSTRAINT ck_browser_observation_resolution_status;
ALTER TABLE local_connector_unread_observations ADD CONSTRAINT ck_local_connector_observation_resolution CHECK (resolution_status IN ('UNRESOLVED','HR_REPLIED'));
ALTER TABLE local_connector_unread_observations RENAME CONSTRAINT browser_unread_observations_pkey TO local_connector_unread_observations_pkey;
ALTER TABLE local_connector_unread_observations RENAME CONSTRAINT uk_browser_unread_account_chat TO uk_local_connector_unread_account_chat;
ALTER TABLE local_connector_unread_observations RENAME CONSTRAINT ck_browser_observation_direction TO ck_local_connector_observation_direction;
ALTER TABLE local_connector_unread_observations RENAME CONSTRAINT ck_browser_observation_review TO ck_local_connector_observation_review;
ALTER TABLE local_connector_unread_observations RENAME CONSTRAINT ck_browser_unread_count TO ck_local_connector_unread_count;
ALTER TABLE local_connector_unread_observations RENAME CONSTRAINT browser_unread_observations_boss_account_id_fkey TO local_connector_unread_boss_account_id_fkey;
ALTER TABLE local_connector_unread_observations RENAME CONSTRAINT browser_unread_observations_browser_device_id_fkey TO local_connector_unread_device_id_fkey;
ALTER TABLE local_connector_unread_observations RENAME CONSTRAINT browser_unread_observations_reviewed_by_fkey TO local_connector_unread_reviewed_by_fkey;
ALTER INDEX idx_browser_observation_eligibility RENAME TO idx_local_connector_observation_eligibility;
ALTER INDEX idx_browser_unread_account RENAME TO idx_local_connector_unread_account;
ALTER INDEX idx_browser_unread_queue RENAME TO idx_local_connector_unread_queue;
ALTER INDEX ix_browser_observation_resolution RENAME TO ix_local_connector_observation_resolution;
