import { DEFAULTS, REAL_BOSS_MONITOR_SELECTORS, validateConfig } from './shared.js'
const fields = { conversation:'会话列表项',conversationUnread:'会话未读角标',conversationIdentity:'选中会话标识节点',activeConversation:'当前会话容器',conversationIdAttribute:'会话 ID 属性',candidateName:'候选人姓名',jobTitle:'职位名称',message:'消息节点',messageIdAttribute:'消息 ID 属性（可留空并生成摘要）',directionAttribute:'方向属性（可留空）',inboundMarker:'候选人消息标记',outboundMarker:'HR 消息标记',messageTime:'消息时间节点',timeAttribute:'时间属性（可留空）',editor:'输入框',sendButton:'发送按钮'}
const form=document.querySelector('#form'),result=document.querySelector('#result'),container=document.querySelector('#selectors')
for(const [key,label] of Object.entries(fields)){const node=document.createElement('label');node.textContent=label;node.innerHTML+=`<input name="selector.${key}">`;if(!key.endsWith('Attribute')){const button=document.createElement('button');button.type='button';button.textContent='从页面选取';button.onclick=()=>pickSelector(key,label);node.append(button)}container.append(node)}
const {config:stored={}}=await chrome.storage.local.get('config');let config={...DEFAULTS,...stored,selectors:{...DEFAULTS.selectors,...stored.selectors}}
for(const element of form.elements){if(!element.name)continue;const key=element.name.replace('selector.',''),value=element.name.startsWith('selector.')?config.selectors[key]:config[element.name];if(element.type==='checkbox')element.checked=Boolean(value);else element.value=value??''}
document.querySelector('#applyBossMonitorPreset').onclick=async()=>{for(const[key,value]of Object.entries(REAL_BOSS_MONITOR_SELECTORS))form.elements[`selector.${key}`].value=value;form.elements.monitorOnly.checked=true;form.elements.emergencyStop.checked=true;config={...config,monitorOnly:true,emergencyStop:true,selectors:{...config.selectors,...REAL_BOSS_MONITOR_SELECTORS}};await chrome.storage.local.set({config});result.textContent='真实 BOSS 只监测预设已直接保存；发送与消息同步保持关闭';result.className='success'}
form.addEventListener('submit',async event=>{event.preventDefault();const next=structuredClone(config);for(const element of form.elements){if(!element.name)continue;const target=element.name.startsWith('selector.')?next.selectors:next,key=element.name.replace('selector.','');target[key]=element.type==='checkbox'?element.checked:element.type==='number'?Number(element.value):element.value.trim()}const error=validateConfig(next);if(error){result.textContent=error;result.className='error';return}if(!await requestBackendAccess(next.backendUrl)){result.textContent='未授权访问该后端地址';result.className='error';return}config=next;await chrome.storage.local.set({config});result.textContent='已保存';result.className='success'})
document.querySelector('#pair').onclick=async()=>{const token=document.querySelector('#pairingToken').value.trim(),pairResult=document.querySelector('#pairResult'),backend=form.elements.backendUrl.value.trim().replace(/\/$/,'');if(!token){pairResult.textContent='请输入配对令牌';return}try{if(!await requestBackendAccess(backend))throw new Error('未授权后端地址');const response=await fetch(`${backend}/api/browser-runtime/pair`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({pairingToken:token,deviceName:`Chrome ${navigator.platform}`})});if(!response.ok)throw new Error(await response.text());const credentials=await response.json();await chrome.storage.local.set({deviceCredentials:credentials});document.querySelector('#pairingToken').value='';pairResult.textContent=`已绑定 ${credentials.accountName}`;}catch{pairResult.textContent='配对失败，令牌可能已过期、未授权或后端不可达'}}
async function requestBackendAccess(value){try{const url=new URL(value),origin=`${url.origin}/*`;if(await chrome.permissions.contains({origins:[origin]}))return true;return chrome.permissions.request({origins:[origin]})}catch{return false}}
async function bossTab(){const tabs=await chrome.tabs.query({url:['https://*.zhipin.com/*','http://localhost:8091/*']});return tabs.find(tab=>tab.active)||tabs[0]}
async function ensureContentScript(tab){try{return await chrome.tabs.sendMessage(tab.id,{type:'PING'})}catch{await chrome.scripting.executeScript({target:{tabId:tab.id},files:['content-script.js']});return chrome.tabs.sendMessage(tab.id,{type:'PING'})}}
async function pickSelector(key,label){result.textContent=`请切换到 BOSS 会话页并点击「${label}」`;try{const target=await bossTab();if(!target)throw new Error('没有找到 zhipin.com 标签页');await ensureContentScript(target);const picked=await chrome.tabs.sendMessage(target.id,{type:'START_PICKER',label});if(picked?.selector){form.elements[`selector.${key}`].value=picked.selector;result.textContent=`已识别 ${label}，请保存设置`}else result.textContent='已取消选取'}catch(error){result.textContent=`页面连接失败：${String(error?.message||error)}。请确认页面是 BOSS 招聘端并刷新一次。`}}
const diagnosticLabels={observedAt:'观测时间',origin:'页面来源',status:'适配状态',reason:'原因',adapterDigest:'适配器摘要',conversationCount:'当前加载会话数',unreadConversationCount:'识别到未读会话数',selectedConversationUnread:'当前会话是否未读',chatDigest:'会话摘要',messageDigest:'消息摘要',direction:'最后消息方向',createdAt:'消息时间',ageMinutes:'消息年龄（分钟）',bound:'后端绑定',visible:'标签页可见'}
async function refreshDiagnostics(){const response=await chrome.runtime.sendMessage({type:'GET_DIAGNOSTICS'}),current=document.querySelector('#diagnosticCurrent'),events=document.querySelector('#diagnosticEvents');current.replaceChildren();if(!response.current){appendDiagnostic(current,'状态','尚未收到会话页诊断');events.textContent='暂无诊断记录';return}for(const[key,label]of Object.entries(diagnosticLabels))appendDiagnostic(current,label,formatDiagnostic(response.current[key]));events.replaceChildren(...response.events.slice().reverse().map(item=>{const row=document.createElement('div');row.className='diagnostic-event';row.textContent=`${formatDiagnostic(item.observedAt)} · ${item.status} · ${item.reason||'-'}`;return row}))}
function appendDiagnostic(container,label,value){const term=document.createElement('dt'),detail=document.createElement('dd');term.textContent=label;detail.textContent=value;container.append(term,detail)}
function formatDiagnostic(value){if(value===true)return'是';if(value===false)return'否';if(value===null||value===undefined||value==='')return'-';if(typeof value==='string'&&/^\d{4}-\d\d-\d\dT/.test(value)){const date=new Date(value);if(Number.isFinite(date.getTime()))return date.toLocaleString('zh-CN',{hour12:false})}return String(value)}
document.querySelector('#refreshDiagnostics').onclick=refreshDiagnostics
document.querySelector('#detectCurrentPage').onclick=async()=>{const output=document.querySelector('#pageDetectionResult');output.textContent='正在连接当前 BOSS 页面…';try{const target=await bossTab();if(!target)throw new Error('没有找到已打开的 zhipin.com 页面');await ensureContentScript(target);await chrome.tabs.sendMessage(target.id,{type:'RUN_DIAGNOSTIC'});output.textContent='页面脚本已连接，正在生成脱敏诊断…';setTimeout(refreshDiagnostics,1500)}catch(error){output.textContent=`检测失败：${String(error?.message||error)}。请刷新 BOSS 页面后重试。`}}
document.querySelector('#collectStructure').onclick=async()=>{const output=document.querySelector('#structureResult');output.textContent='正在被动扫描当前页面及子页面结构…';try{const target=await bossTab();if(!target)throw new Error('没有找到已打开的 zhipin.com 页面');const frames=await chrome.scripting.executeScript({target:{tabId:target.id,allFrames:true},func:passiveStructureScan});const report={version:2,collectedAt:new Date().toISOString(),tabOrigin:new URL(target.url).origin,frames:frames.map(item=>item.result).filter(Boolean)};await chrome.storage.local.set({passiveStructureReport:report});const candidates=report.frames.reduce((sum,frame)=>sum+frame.candidates.length,0);output.textContent=`采集完成：${report.frames.length} 个页面层级，${candidates} 个脱敏结构候选。请导出报告发给开发人员。`}catch(error){output.textContent=`采集失败：${String(error?.message||error)}。请保持 BOSS 会话页打开并刷新后重试。`}}
function passiveStructureScan(){
 const visible=element=>{const rect=element.getBoundingClientRect(),style=getComputedStyle(element);return rect.width>0&&rect.height>0&&style.display!=='none'&&style.visibility!=='hidden'&&Number(style.opacity)!==0}
 const safeClasses=element=>[...element.classList].filter(value=>/^[A-Za-z_-][A-Za-z0-9_-]{0,79}$/.test(value)&&!/[0-9]{5,}/.test(value)).slice(0,8)
 const selectorFor=(element,classes)=>classes.length?`${element.localName}.${classes.map(value=>CSS.escape(value)).join('.')}`:element.localName
 const unique=new Map()
 for(const element of [...document.querySelectorAll('*')].slice(0,12000)){
  if(!visible(element))continue
  const classes=safeClasses(element),classText=classes.join(' '),rawText=String(element.textContent||'').trim()
  const editor=element.matches('textarea,[contenteditable="true"],[role="textbox"]')
  const control=element.matches('button,[role="button"]')
  const structural=/(chat|message|conversation|dialog|geek|friend|item|bubble|unread|badge|input|editor|send|resume|file)/i.test(classText)
  const roleHint=editor?'editor':(/^(发送|send)$/i.test(rawText)&&control?'send-control':(/^(在线简历|附件简历|求简历)$/i.test(rawText)?'resume-control':(control?'button':null)))
  if(!structural&&!roleHint)continue
  const rect=element.getBoundingClientRect(),selectorCandidate=selectorFor(element,classes),attributeNames=[...element.attributes].map(attribute=>attribute.name).filter(name=>name.startsWith('data-')||['role','contenteditable','aria-label'].includes(name)).slice(0,12)
  const key=[selectorCandidate,roleHint||'',attributeNames.join(',')].join('|'),existing=unique.get(key)
  if(existing){existing.occurrences++;continue}
  const ancestorSelectors=[];for(let parent=element.parentElement;parent&&ancestorSelectors.length<4;parent=parent.parentElement){const parentClasses=safeClasses(parent);if(parentClasses.length)ancestorSelectors.push(selectorFor(parent,parentClasses))}
  const score=(roleHint==='editor'?1000:roleHint==='send-control'?950:roleHint==='resume-control'?900:roleHint==='button'?100:0)+(/message|bubble/i.test(classText)?800:0)+(/unread|badge/i.test(classText)?700:0)+(/chat|conversation/i.test(classText)?600:0)+(/editor|input|send/i.test(classText)?500:0)+(/geek|friend|item/i.test(classText)?200:0)
  unique.set(key,{tag:element.localName,classes,attributeNames,roleHint,selectorCandidate,ancestorSelectors,childCount:element.children.length,rect:{width:Math.round(rect.width),height:Math.round(rect.height)},repeatedSiblingCount:element.parentElement?[...element.parentElement.children].filter(sibling=>sibling.localName===element.localName&&safeClasses(sibling).join(' ')===classText).length:1,occurrences:1,score})
 }
 const candidates=[...unique.values()].sort((left,right)=>right.score-left.score||right.occurrences-left.occurrences).slice(0,500)
 let path='';try{path=location.pathname}catch{}
 return{origin:location.origin==='null'?'embedded':location.origin,path,candidateCount:candidates.length,candidates}
}
document.querySelector('#clearDiagnostics').onclick=async()=>{await chrome.runtime.sendMessage({type:'CLEAR_DIAGNOSTICS'});await chrome.storage.local.remove('passiveStructureReport');document.querySelector('#structureResult').textContent='';await refreshDiagnostics()}
document.querySelector('#exportDiagnostics').onclick=async()=>{const response=await chrome.runtime.sendMessage({type:'GET_DIAGNOSTICS'}),{passiveStructureReport=null}=await chrome.storage.local.get('passiveStructureReport'),blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),privacy:'No plaintext, credentials, cookies or raw external identifiers',passiveStructureReport,...response},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`boss-companion-diagnostics-${Date.now()}.json`;link.click();URL.revokeObjectURL(url)}
await refreshDiagnostics();setInterval(refreshDiagnostics,10_000)
