import { DEFAULTS, validateConfig } from './shared.js'
const fields = { activeConversation:'当前会话容器',conversationIdAttribute:'会话 ID 属性',candidateName:'候选人姓名',jobTitle:'职位名称',message:'消息节点',messageIdAttribute:'消息 ID 属性',directionAttribute:'方向属性',timeAttribute:'时间属性',editor:'输入框',sendButton:'发送按钮'}
const form=document.querySelector('#form'),result=document.querySelector('#result'),container=document.querySelector('#selectors')
for(const [key,label] of Object.entries(fields)){const node=document.createElement('label');node.textContent=label;node.innerHTML+=`<input name="selector.${key}">`;if(!key.endsWith('Attribute')){const button=document.createElement('button');button.type='button';button.textContent='从页面选取';button.onclick=()=>pickSelector(key,label);node.append(button)}container.append(node)}
const {config:stored={}}=await chrome.storage.local.get('config'),config={...DEFAULTS,...stored,selectors:{...DEFAULTS.selectors,...stored.selectors}}
for(const element of form.elements){if(!element.name)continue;const key=element.name.replace('selector.',''),value=element.name.startsWith('selector.')?config.selectors[key]:config[element.name];if(element.type==='checkbox')element.checked=Boolean(value);else element.value=value??''}
form.addEventListener('submit',async event=>{event.preventDefault();const next=structuredClone(config);for(const element of form.elements){if(!element.name)continue;const target=element.name.startsWith('selector.')?next.selectors:next,key=element.name.replace('selector.','');target[key]=element.type==='checkbox'?element.checked:element.type==='number'?Number(element.value):element.value.trim()}const error=validateConfig(next);if(error){result.textContent=error;result.className='error';return}if(!await requestBackendAccess(next.backendUrl)){result.textContent='未授权访问该后端地址';result.className='error';return}await chrome.storage.local.set({config:next});result.textContent='已保存';result.className='success'})
document.querySelector('#pair').onclick=async()=>{const token=document.querySelector('#pairingToken').value.trim(),pairResult=document.querySelector('#pairResult'),backend=form.elements.backendUrl.value.trim().replace(/\/$/,'');if(!token){pairResult.textContent='请输入配对令牌';return}try{if(!await requestBackendAccess(backend))throw new Error('未授权后端地址');const response=await fetch(`${backend}/api/browser-runtime/pair`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({pairingToken:token,deviceName:`Chrome ${navigator.platform}`})});if(!response.ok)throw new Error(await response.text());const credentials=await response.json();await chrome.storage.local.set({deviceCredentials:credentials});document.querySelector('#pairingToken').value='';pairResult.textContent=`已绑定 ${credentials.accountName}`;}catch{pairResult.textContent='配对失败，令牌可能已过期、未授权或后端不可达'}}
async function requestBackendAccess(value){try{const url=new URL(value),origin=`${url.origin}/*`;if(await chrome.permissions.contains({origins:[origin]}))return true;return chrome.permissions.request({origins:[origin]})}catch{return false}}
async function pickSelector(key,label){result.textContent=`请切换到 BOSS 会话页并点击「${label}」`;try{const tabs=await chrome.tabs.query({url:['https://*.zhipin.com/*','http://localhost:8091/*']}),target=tabs.find(tab=>tab.active)||tabs[0];if(!target)throw new Error();const picked=await chrome.tabs.sendMessage(target.id,{type:'START_PICKER',label});if(picked?.selector){form.elements[`selector.${key}`].value=picked.selector;result.textContent=`已识别 ${label}，请保存设置`}else result.textContent='已取消选取'}catch{result.textContent='未找到可识别的 BOSS 会话标签页'}}
