import { DEFAULTS, REAL_BOSS_MONITOR_SELECTORS, assessReplyEligibility, classifyUnreadObservations, diagnosticSignature, localDay, mergeUnreadObservations, sanitizeDiagnostic, unnotifiedTimedOutObservations } from './shared.js'
const POLICY_TTL=45_000,TAB_LEASE_MS=20_000
let policyCache=null

chrome.runtime.onInstalled.addListener(async()=>{const stored=await chrome.storage.local.get(['config','runtime']);if(!stored.config)await chrome.storage.local.set({config:structuredClone(DEFAULTS)});else if(stored.config.monitorOnly){let migrated=false;if(stored.config.selectors?.message==='.message-item'){stored.config.selectors.message=REAL_BOSS_MONITOR_SELECTORS.message;migrated=true}if(stored.config.selectors?.activeConversation==='.chat-conversation'){stored.config.selectors.activeConversation=REAL_BOSS_MONITOR_SELECTORS.activeConversation;migrated=true}if(migrated)await chrome.storage.local.set({config:stored.config})}if(!stored.runtime)await chrome.storage.local.set({runtime:freshRuntime()});chrome.alarms.create('health',{periodInMinutes:1})})
chrome.runtime.onMessage.addListener((message,sender,sendResponse)=>{handle(message,sender).then(sendResponse).catch(error=>sendResponse({ok:false,action:'EXTENSION_ERROR',detail:String(error?.message||error)}));return true})
chrome.alarms.onAlarm.addListener(async({name})=>{if(name!=='health')return;const{runtime=freshRuntime()}=await chrome.storage.local.get('runtime');if(runtime.lastHeartbeatAt&&Date.now()-runtime.lastHeartbeatAt>120_000){Object.assign(runtime,{state:'PAUSED',reason:'会话页超过 2 分钟无心跳',leaderTabId:null,leaderLeaseUntil:0});await chrome.storage.local.set({runtime})}})

async function handle(message,sender){
 const stored=await chrome.storage.local.get(['config','runtime']),config={...DEFAULTS,...(stored.config||{}),selectors:{...DEFAULTS.selectors,...(stored.config?.selectors||{})}},runtime=rollDay(stored.runtime||freshRuntime())
 if(config.monitorOnly&&isBossPage(sender.tab?.url))config.selectors={...config.selectors,...REAL_BOSS_MONITOR_SELECTORS}
 if(message.type==='GET_STATE'){const policy=await getPolicy(config),effective=policy.ok?{...config,...policy}:{...config,enabled:false,automaticSend:false};effective.automaticSend=Boolean(effective.automaticSend&&!config.emergencyStop&&!config.monitorOnly);if(policy.ok)Object.assign(runtime,{sentToday:policy.sentToday,lastSentAt:policy.lastSentAt?Date.parse(policy.lastSentAt):0});await chrome.storage.local.set({runtime});return{ok:true,config:effective,runtime,backendState:policy.ok?'CONNECTED':policy.action}}
 if(message.type==='DIAGNOSTIC'){const diagnostic=sanitizeDiagnostic(message.payload,sender.tab);runtime.diagnostic=diagnostic;runtime.diagnosticEvents=runtime.diagnosticEvents||[];const previous=runtime.diagnosticEvents.at(-1);if(!previous||diagnosticSignature(previous)!==diagnosticSignature(diagnostic))runtime.diagnosticEvents=[...runtime.diagnosticEvents,diagnostic].slice(-50);await chrome.storage.local.set({runtime});return{ok:true}}
 if(message.type==='GET_DIAGNOSTICS'){const unreadQueue=assessReplyEligibility(classifyUnreadObservations(runtime.unreadObservations||[],config.observationTimeoutMinutes),runtime.diagnostic);return{ok:true,current:runtime.diagnostic||null,events:runtime.diagnosticEvents||[],unreadObservations:runtime.unreadObservations||[],unreadQueue,emergencyStop:config.emergencyStop,monitorOnly:config.monitorOnly}}
 if(message.type==='OBSERVE_UNREAD_LIST'){runtime.unreadObservations=mergeUnreadObservations(runtime.unreadObservations,message.payload?.entries);if(config.timeoutNotifications)await notifyNewTimeouts(runtime,config);await chrome.storage.local.set({runtime});return{ok:true,count:runtime.unreadObservations.length}}
 if(message.type==='CLEAR_DIAGNOSTICS'){runtime.diagnostic=null;runtime.diagnosticEvents=[];runtime.unreadObservations=[];await chrome.storage.local.set({runtime});return{ok:true}}
 if(message.type==='ACQUIRE_TAB')return acquireTab(runtime,sender.tab?.id)
 if(message.type==='RELEASE_TAB'){if(runtime.leaderTabId===sender.tab?.id)Object.assign(runtime,{leaderTabId:null,leaderLeaseUntil:0});await chrome.storage.local.set({runtime});return{ok:true}}
 if(message.type==='HEARTBEAT'){const previous=runtime.state;Object.assign(runtime,{lastHeartbeatAt:Date.now(),url:sender.tab?.url||'',state:message.state,reason:message.reason||''});await chrome.storage.local.set({runtime});if(!runtime.lastRemoteHeartbeatAt||Date.now()-runtime.lastRemoteHeartbeatAt>=30_000||previous!==message.state){const result=await remote(config,'/api/browser-runtime/heartbeat',{state:message.state,reason:message.reason||''});if(result.ok){runtime.lastRemoteHeartbeatAt=Date.now();await chrome.storage.local.set({runtime})}}return{ok:true,config,runtime}}
 if(message.type==='SYNC_MESSAGE')return remote(config,'/api/browser-runtime/messages',message.payload)
 if(message.type==='CLAIM_SEND'){if(config.emergencyStop||config.monitorOnly)return{ok:true,allowed:false,action:config.monitorOnly?'MONITOR_ONLY':'EMERGENCY_STOP'};return remote(config,'/api/browser-runtime/send-claims',message.payload)}
 if(message.type==='SEND_RECEIPT'){const result=await remote(config,`/api/browser-runtime/send-claims/${encodeURIComponent(message.claimId)}/receipt`,message.payload);policyCache=null;if(result.ok&&result.status==='SENT')Object.assign(runtime,{sentToday:result.sentToday,lastSentAt:result.lastSentAt?Date.parse(result.lastSentAt):Date.now(),state:'RUNNING',reason:''});if(message.payload.status==='UNKNOWN')Object.assign(runtime,{state:'PAUSED',reason:'发送结果无法确认，已停止自动发送并禁止重试'});await chrome.storage.local.set({runtime});return result}
 if(message.type==='PAUSE'){Object.assign(runtime,{state:'PAUSED',reason:message.reason||'页面安全检查未通过'});await chrome.storage.local.set({runtime});return{ok:true}}
 if(message.type==='SET_EMERGENCY_STOP'){config.emergencyStop=Boolean(message.value);if(config.emergencyStop)Object.assign(runtime,{state:'PAUSED',reason:'本机紧急停止已开启',leaderTabId:null,leaderLeaseUntil:0});await chrome.storage.local.set({config,runtime});return{ok:true,config,runtime}}
 return{ok:false}
}
function isBossPage(value){try{return new URL(value).hostname==='zhipin.com'||new URL(value).hostname.endsWith('.zhipin.com')}catch{return false}}
async function acquireTab(runtime,tabId){if(!Number.isInteger(tabId))return{ok:false,leader:false};const now=Date.now();if(runtime.leaderTabId&&runtime.leaderTabId!==tabId&&runtime.leaderLeaseUntil>now)return{ok:true,leader:false,leaderTabId:runtime.leaderTabId};runtime.leaderTabId=tabId;runtime.leaderLeaseUntil=now+TAB_LEASE_MS;await chrome.storage.local.set({runtime});return{ok:true,leader:true,leaseUntil:runtime.leaderLeaseUntil}}
async function getPolicy(config){if(policyCache&&Date.now()-policyCache.at<POLICY_TTL)return policyCache.value;const value=await remote(config,'/api/browser-runtime/policy',undefined,'GET');policyCache={at:Date.now(),value};return value}
async function remote(config,path,body,method='POST'){const{deviceCredentials}=await chrome.storage.local.get('deviceCredentials');if(!deviceCredentials?.deviceToken)return{ok:false,bound:false,action:'DEVICE_NOT_PAIRED'};try{const response=await fetch(`${config.backendUrl.replace(/\/$/,'')}${path}`,{method,headers:{'Content-Type':'application/json',Authorization:`Device ${deviceCredentials.deviceToken}`},body:body===undefined?undefined:JSON.stringify(body)});if(!response.ok)return{ok:false,bound:false,action:response.status===401?'DEVICE_UNAUTHORIZED':'BACKEND_REJECTED'};return{ok:true,...await response.json()}}catch{return{ok:false,bound:false,action:'BACKEND_UNREACHABLE'}}}
function freshRuntime(){return{state:'DISABLED',reason:'',day:localDay(),sentToday:0,lastSentAt:0,lastHeartbeatAt:0,lastRemoteHeartbeatAt:0,leaderTabId:null,leaderLeaseUntil:0,url:''}}
function rollDay(runtime){if(runtime.day!==localDay()){runtime.day=localDay();runtime.sentToday=0}return runtime}
async function notifyNewTimeouts(runtime,config){const now=new Date();if(runtime.lastTimeoutNotificationFailureAt&&now.getTime()-Date.parse(runtime.lastTimeoutNotificationFailureAt)<15*60000)return;const items=unnotifiedTimedOutObservations(runtime.unreadObservations,config.observationTimeoutMinutes,now);if(!items.length)return;try{await chrome.notifications.create(`boss-timeout-${now.getTime()}`,{type:'basic',iconUrl:'icon.svg',title:'有未读会话等待处理',message:`${items.length} 个会话刚达到 ${config.observationTimeoutMinutes} 分钟未读阈值，请在方便时人工查看。`,priority:1});const notified=new Set(items.map(item=>item.chatDigest));runtime.unreadObservations=runtime.unreadObservations.map(item=>notified.has(item.chatDigest)?{...item,timedOutNotifiedAt:now.toISOString()}:item);runtime.lastTimeoutNotificationFailureAt=null}catch{runtime.lastTimeoutNotificationFailureAt=now.toISOString()}}
