ALTER TABLE conversations
  ADD COLUMN IF NOT EXISTS record_primary TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS record_secondary TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS record_tertiary TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS record_remark TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS record_classified BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS record_auto_filled BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS record_updated_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS record_updated_by TEXT NOT NULL DEFAULT '';

CREATE TABLE IF NOT EXISTS record_category_settings (
  id TEXT PRIMARY KEY,
  categories JSONB NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL
);
