import { type FormEvent, useEffect, useMemo, useState } from 'react'
import { useRouter, useRouterState } from '@tanstack/react-router'
import { ApiError } from '../api/client'
import { useAuth } from '../auth/AuthContext'
import { DialogCloseButton } from '../components/DialogCloseButton'
import { shippingFeeApi, type ShippingFeeEstimate, type ShippingFeePage, type ShippingFeeRegion, type ShippingFeeRule } from '../modules/shippingFeeApi'
import './WarehouseArchiveShells.css'

export type ShippingFeeView = 'REGIONS' | 'RULES' | 'ESTIMATE'
export type ShippingFeeStatus = 'ALL' | 'ENABLED' | 'DISABLED'
export type ShippingFeeWeighingMode = 'ACTUAL' | 'VOLUMETRIC' | 'MAXIMUM'
export type CustomShippingFeeQuery = { view: ShippingFeeView; status: ShippingFeeStatus; regionName: string; ruleName: string; country: string; city: string; postalCode: string; weightGrams: string; lengthMm: string; widthMm: string; heightMm: string; volumetricDivisor: string; weighingMode: ShippingFeeWeighingMode }
type ListState<T> = { status: 'loading' } | { status: 'ready'; data: ShippingFeePage<T> } | { status: 'error'; message: string }
type FormMode = 'region' | 'rule' | undefined
const currencies = ['USD', 'CNY', 'EUR', 'GBP', 'JPY'] as const

function boundedText(value: string | null, maximum = 100) { return (value ?? '').trim().slice(0, maximum) }
function boundedNumber(value: string | null, maximum = 12) { const normalized = boundedText(value, maximum); return /^\d+(?:\.\d{1,3})?$/.test(normalized) ? normalized : '' }
function feeView(value: string | null): ShippingFeeView { return value === 'RULES' || value === 'ESTIMATE' ? value : 'REGIONS' }
function feeStatus(value: string | null): ShippingFeeStatus { return value === 'ENABLED' || value === 'DISABLED' ? value : 'ALL' }
function weighingMode(value: string | null): ShippingFeeWeighingMode { return value === 'VOLUMETRIC' || value === 'MAXIMUM' ? value : 'ACTUAL' }
function integer(value: FormDataEntryValue | null, field: string, optional = false) { const text = String(value ?? '').trim(); if (optional && !text) return undefined; const parsed = Number(text); if (!Number.isSafeInteger(parsed) || parsed < 0) throw new Error(`${field}应为非负整数。`); return parsed }
function currencyDigits(code: string) { return new Intl.NumberFormat('zh-CN', { style: 'currency', currency: code }).resolvedOptions().maximumFractionDigits ?? 2 }
function moneyMinor(value: FormDataEntryValue | null, currency: string, field: string) { const text = String(value ?? '').trim(); if (!/^\d+(?:\.\d{1,2})?$/.test(text)) throw new Error(`${field}格式不正确。`); const factor = 10 ** currencyDigits(currency); const result = Math.round(Number(text) * factor); if (!Number.isSafeInteger(result) || result < 0) throw new Error(`${field}超出支持范围。`); return result }
function money(value: number, currency: string) { return new Intl.NumberFormat('zh-CN', { style: 'currency', currency }).format(value / (10 ** currencyDigits(currency))) }
function displayTime(value: string) { return new Intl.DateTimeFormat('zh-CN', { dateStyle: 'short', timeStyle: 'short' }).format(new Date(value)) }
function safeMessage(error: unknown) { if (error instanceof Error && !(error instanceof ApiError)) return error.message; if (error instanceof ApiError && error.status === 409) return '记录已变化或名称重复，请刷新后重试。'; if (error instanceof ApiError && error.status === 403) return '当前账号没有自定义运费管理权限。'; return '操作未完成，请稍后重试。' }

export function parseCustomShippingFeeQuery(search: string): CustomShippingFeeQuery {
  const params = new URLSearchParams(search)
  return { view: feeView(params.get('view')), status: feeStatus(params.get('status')), regionName: boundedText(params.get('regionName')), ruleName: boundedText(params.get('ruleName')), country: boundedText(params.get('country'), 2).toUpperCase(), city: boundedText(params.get('city')), postalCode: boundedText(params.get('postalCode'), 32), weightGrams: boundedNumber(params.get('weightGrams')), lengthMm: boundedNumber(params.get('lengthMm')), widthMm: boundedNumber(params.get('widthMm')), heightMm: boundedNumber(params.get('heightMm')), volumetricDivisor: boundedNumber(params.get('volumetricDivisor')), weighingMode: weighingMode(params.get('weighingMode')) }
}
export function toCustomShippingFeeUrl(query: Partial<CustomShippingFeeQuery>) {
  const params = new URLSearchParams()
  if (query.view && query.view !== 'REGIONS') params.set('view', query.view)
  if (query.status && query.status !== 'ALL') params.set('status', query.status)
  for (const key of ['regionName', 'ruleName', 'country', 'city'] as const) if (query[key]) params.set(key, boundedText(query[key]))
  if (query.postalCode) params.set('postalCode', boundedText(query.postalCode, 32))
  for (const key of ['weightGrams', 'lengthMm', 'widthMm', 'heightMm', 'volumetricDivisor'] as const) { const value = boundedNumber(query[key] ?? null); if (value) params.set(key, value) }
  if (query.weighingMode && query.weighingMode !== 'ACTUAL') params.set('weighingMode', query.weighingMode)
  return params.size ? `/logistics/custom-fees?${params}` : '/logistics/custom-fees'
}

export function CustomShippingFeePage() {
  const router = useRouter()
  const search = useRouterState({ select: (state) => state.location.searchStr })
  const query = useMemo(() => parseCustomShippingFeeQuery(search), [search])
  const { hasPermission } = useAuth()
  const canWrite = hasPermission('logistics.shipping_fee.write')
  const [regions, setRegions] = useState<ListState<ShippingFeeRegion>>({ status: 'loading' })
  const [rules, setRules] = useState<ListState<ShippingFeeRule>>({ status: 'loading' })
  const [activeRegions, setActiveRegions] = useState<ShippingFeeRegion[]>([])
  const [formMode, setFormMode] = useState<FormMode>()
  const [estimates, setEstimates] = useState<ShippingFeeEstimate[] | undefined>()
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState('')
  const [refreshKey, setRefreshKey] = useState(0)
  const navigate = (next: Partial<CustomShippingFeeQuery>) => router.history.push(toCustomShippingFeeUrl(next))

  useEffect(() => {
    if (query.view === 'ESTIMATE') return
    const controller = new AbortController()
    if (query.view === 'REGIONS') {
      setRegions({ status: 'loading' })
      shippingFeeApi.regions({ status: query.status, keyword: query.regionName || undefined, page: 0, size: 100, signal: controller.signal }).then((data) => setRegions({ status: 'ready', data })).catch((caught) => { if (!controller.signal.aborted) setRegions({ status: 'error', message: safeMessage(caught) }) })
    } else {
      setRules({ status: 'loading' })
      shippingFeeApi.rules({ status: query.status, regionKeyword: query.regionName || undefined, ruleKeyword: query.ruleName || undefined, page: 0, size: 100, signal: controller.signal }).then((data) => setRules({ status: 'ready', data })).catch((caught) => { if (!controller.signal.aborted) setRules({ status: 'error', message: safeMessage(caught) }) })
    }
    return () => controller.abort()
  }, [query.view, query.status, query.regionName, query.ruleName, refreshKey])

  useEffect(() => {
    if (formMode !== 'rule') return
    const controller = new AbortController()
    shippingFeeApi.regions({ status: 'ENABLED', page: 0, size: 200, signal: controller.signal }).then((data) => setActiveRegions(data.items)).catch((caught) => setError(safeMessage(caught)))
    return () => controller.abort()
  }, [formMode, refreshKey])

  const submitSearch = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); navigate({ view: query.view, status: feeStatus(String(data.get('status'))), regionName: boundedText(String(data.get('regionName'))), ruleName: boundedText(String(data.get('ruleName'))) }) }
  const createRegion = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); setBusy(true); setError(''); try { await shippingFeeApi.createRegion({ name: boundedText(String(data.get('name'))), countryCode: boundedText(String(data.get('countryCode')), 2).toUpperCase(), city: boundedText(String(data.get('city'))) || undefined, postalCodePrefix: boundedText(String(data.get('postalCodePrefix')), 32) || undefined, note: boundedText(String(data.get('note')), 500) || undefined }); setFormMode(undefined); setRefreshKey((value) => value + 1) } catch (caught) { setError(safeMessage(caught)) } finally { setBusy(false) } }
  const createRule = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); setBusy(true); setError(''); try { const currencyCode = boundedText(String(data.get('currencyCode')), 3).toUpperCase(); await shippingFeeApi.createRule({ regionId: String(data.get('regionId')), name: boundedText(String(data.get('name'))), minimumWeightGrams: integer(data.get('minimumWeightGrams'), '起始重量') as number, maximumWeightGrams: integer(data.get('maximumWeightGrams'), '截止重量', true), baseFeeMinor: moneyMinor(data.get('baseFee'), currencyCode, '基础运费'), perKilogramFeeMinor: moneyMinor(data.get('perKilogramFee'), currencyCode, '每公斤费用'), otherFeeMinor: moneyMinor(data.get('otherFee'), currencyCode, '其他费用'), currencyCode, note: boundedText(String(data.get('note')), 500) || undefined }); setFormMode(undefined); setRefreshKey((value) => value + 1) } catch (caught) { setError(safeMessage(caught)) } finally { setBusy(false) } }
  const archiveRegion = async (item: ShippingFeeRegion) => { if (!window.confirm(`停用区域“${item.name}”及其有效费用规则？`)) return; setBusy(true); setError(''); try { await shippingFeeApi.archiveRegion(item.id, item.version); setRefreshKey((value) => value + 1) } catch (caught) { setError(safeMessage(caught)) } finally { setBusy(false) } }
  const archiveRule = async (item: ShippingFeeRule) => { if (!window.confirm(`停用费用规则“${item.name}”？`)) return; setBusy(true); setError(''); try { await shippingFeeApi.archiveRule(item.id, item.version); setRefreshKey((value) => value + 1) } catch (caught) { setError(safeMessage(caught)) } finally { setBusy(false) } }
  const estimate = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); setBusy(true); setError(''); try { const mode = weighingMode(String(data.get('weighingMode'))); const result = await shippingFeeApi.estimate({ countryCode: boundedText(String(data.get('country')), 2).toUpperCase(), city: boundedText(String(data.get('city'))) || undefined, postalCode: boundedText(String(data.get('postalCode')), 32) || undefined, weightGrams: integer(data.get('weightGrams'), '重量') as number, lengthMm: integer(data.get('lengthMm'), '长度', mode === 'ACTUAL'), widthMm: integer(data.get('widthMm'), '宽度', mode === 'ACTUAL'), heightMm: integer(data.get('heightMm'), '高度', mode === 'ACTUAL'), volumetricDivisor: integer(data.get('volumetricDivisor'), '体积重系数', mode === 'ACTUAL'), weighingMode: mode }); setEstimates(result) } catch (caught) { setEstimates(undefined); setError(safeMessage(caught)) } finally { setBusy(false) } }

  return <main className="warehouse-archive-page" aria-labelledby="custom-shipping-fee-title">
    <header className="warehouse-archive-heading"><div><p className="eyebrow">物流 / 物流管理</p><h1 id="custom-shipping-fee-title">自定义运费</h1><p>维护目的地区域和重量费用规则，并按包裹数据试算运费。</p></div></header>
    <div className="warehouse-archive-tabs" role="tablist" aria-label="自定义运费视图"><button className={query.view === 'REGIONS' ? 'is-active' : ''} type="button" role="tab" aria-selected={query.view === 'REGIONS'} onClick={() => navigate({ view: 'REGIONS' })}>区域管理</button><button className={query.view === 'RULES' ? 'is-active' : ''} type="button" role="tab" aria-selected={query.view === 'RULES'} onClick={() => navigate({ view: 'RULES' })}>区域费用管理</button><button className={query.view === 'ESTIMATE' ? 'is-active' : ''} type="button" role="tab" aria-selected={query.view === 'ESTIMATE'} onClick={() => navigate({ view: 'ESTIMATE' })}>费用试算</button></div>
    <section className="warehouse-archive-card" aria-label="自定义运费配置">
      <div className="warehouse-processing-formula" role="note"><strong>计费规则</strong><span>运费 = 基础运费 + 计费重量 × 每公斤费用 + 其他费用；停用记录保留历史但不参与试算。</span></div>
      {error && <div className="inline-alert" role="alert">{error}</div>}
      {query.view !== 'ESTIMATE' ? <><form className="warehouse-archive-filters" key={toCustomShippingFeeUrl(query)} onSubmit={submitSearch}><label>状态<select name="status" defaultValue={query.status}><option value="ALL">全部状态</option><option value="ENABLED">启用</option><option value="DISABLED">停用</option></select></label><label>区域名称<input name="regionName" defaultValue={query.regionName} maxLength={100} placeholder="请输入区域名称" /></label>{query.view === 'RULES' && <label>费用规则名称<input name="ruleName" defaultValue={query.ruleName} maxLength={100} placeholder="请输入费用规则名称" /></label>}<div className="warehouse-archive-filter-actions"><button className="is-primary" type="submit">搜索</button><button type="button" onClick={() => navigate({ view: query.view })}>重置</button></div></form><div className="warehouse-archive-actions">{canWrite && <button className="is-primary" type="button" disabled={busy} onClick={() => { setError(''); setFormMode(query.view === 'REGIONS' ? 'region' : 'rule') }}>{query.view === 'REGIONS' ? '新增区域' : '新增规则'}</button>}</div>{query.view === 'REGIONS' ? <RegionTable state={regions} canWrite={canWrite} busy={busy} archive={archiveRegion} /> : <RuleTable state={rules} canWrite={canWrite} busy={busy} archive={archiveRule} />}</> : <EstimatePanel query={query} busy={busy} estimates={estimates} submit={estimate} reset={() => { setEstimates(undefined); navigate({ view: 'ESTIMATE' }) }} />}
    </section>
    {formMode === 'region' && <Dialog title="新增区域" busy={busy} close={() => setFormMode(undefined)}><form onSubmit={(event) => void createRegion(event)}><label>区域名称<input name="name" required maxLength={100} placeholder="例如：美国西部" /></label><label>国家 / 地区代码<input name="countryCode" required maxLength={2} placeholder="例如：US" /></label><label>城市（可选）<input name="city" maxLength={100} placeholder="留空表示该国家全部城市" /></label><label>邮编前缀（可选）<input name="postalCodePrefix" maxLength={32} placeholder="例如：90" /></label><label>备注（可选）<textarea name="note" maxLength={500} /></label>{error && <div className="inline-alert" role="alert">{error}</div>}<div className="form-actions"><button type="button" disabled={busy} onClick={() => setFormMode(undefined)}>取消</button><button className="is-primary" type="submit" disabled={busy}>{busy ? '正在保存…' : '保存区域'}</button></div></form></Dialog>}
    {formMode === 'rule' && <Dialog title="新增费用规则" busy={busy} close={() => setFormMode(undefined)}>{activeRegions.length === 0 ? <div className="warehouse-archive-empty" role="status"><strong>请先新增有效区域</strong><span>费用规则必须归属一个区域。</span></div> : <form onSubmit={(event) => void createRule(event)}><label>区域<select name="regionId" required>{activeRegions.map((item) => <option key={item.id} value={item.id}>{item.name} · {item.countryCode}</option>)}</select></label><label>规则名称<input name="name" required maxLength={100} placeholder="例如：标准小包" /></label><label>起始重量（g）<input name="minimumWeightGrams" type="number" min={0} defaultValue={0} required /></label><label>截止重量（g，可选）<input name="maximumWeightGrams" type="number" min={0} /></label><label>币种<select name="currencyCode" defaultValue="USD">{currencies.map((code) => <option key={code} value={code}>{code}</option>)}</select></label><label>基础运费<input name="baseFee" inputMode="decimal" required defaultValue="0.00" /></label><label>每公斤费用<input name="perKilogramFee" inputMode="decimal" required defaultValue="0.00" /></label><label>其他费用<input name="otherFee" inputMode="decimal" required defaultValue="0.00" /></label><label>备注（可选）<textarea name="note" maxLength={500} /></label>{error && <div className="inline-alert" role="alert">{error}</div>}<div className="form-actions"><button type="button" disabled={busy} onClick={() => setFormMode(undefined)}>取消</button><button className="is-primary" type="submit" disabled={busy}>{busy ? '正在保存…' : '保存费用规则'}</button></div></form>}</Dialog>}
  </main>
}

function RegionTable({ state, canWrite, busy, archive }: { state: ListState<ShippingFeeRegion>; canWrite: boolean; busy: boolean; archive: (item: ShippingFeeRegion) => Promise<void> }) { if (state.status === 'loading') return <div className="warehouse-archive-empty" role="status"><strong>正在加载区域</strong></div>; if (state.status === 'error') return <div className="inline-alert" role="alert">{state.message}</div>; return <div className="warehouse-archive-table-wrap"><table aria-label="区域列表"><thead><tr><th>区域名称</th><th>适用范围</th><th>状态</th><th>创建人</th><th>更新时间</th><th>备注</th><th>操作</th></tr></thead><tbody>{state.data.items.length === 0 ? <tr><td colSpan={7}><div className="warehouse-archive-empty" role="status"><strong>暂无区域方案</strong><span>可新增第一个目的地区域。</span></div></td></tr> : state.data.items.map((item) => <tr key={item.id}><td><strong>{item.name}</strong></td><td>{item.countryCode}{item.city ? ` / ${item.city}` : ''}{item.postalCodePrefix ? ` / 邮编 ${item.postalCodePrefix}*` : ''}</td><td>{item.status === 'ACTIVE' ? '启用' : '停用'}</td><td>{item.createdByDisplayName}</td><td>{displayTime(item.updatedAt)}</td><td>{item.note ?? '—'}</td><td>{canWrite && item.status === 'ACTIVE' ? <button className="text-button" type="button" disabled={busy} onClick={() => void archive(item)}>停用</button> : '—'}</td></tr>)}</tbody></table></div> }
function RuleTable({ state, canWrite, busy, archive }: { state: ListState<ShippingFeeRule>; canWrite: boolean; busy: boolean; archive: (item: ShippingFeeRule) => Promise<void> }) { if (state.status === 'loading') return <div className="warehouse-archive-empty" role="status"><strong>正在加载费用规则</strong></div>; if (state.status === 'error') return <div className="inline-alert" role="alert">{state.message}</div>; return <div className="warehouse-archive-table-wrap"><table aria-label="区域费用规则列表"><thead><tr><th>规则名称</th><th>区域</th><th>重量范围（g）</th><th>费用</th><th>状态</th><th>更新时间</th><th>操作</th></tr></thead><tbody>{state.data.items.length === 0 ? <tr><td colSpan={7}><div className="warehouse-archive-empty" role="status"><strong>暂无费用规则</strong><span>请先新增区域，再维护费用规则。</span></div></td></tr> : state.data.items.map((item) => <tr key={item.id}><td><strong>{item.name}</strong></td><td>{item.regionName} · {item.countryCode}</td><td>{item.minimumWeightGrams} - {item.maximumWeightGrams ?? '不限'}</td><td>基础 {money(item.baseFeeMinor, item.currencyCode)}<div>每公斤 {money(item.perKilogramFeeMinor, item.currencyCode)} · 其他 {money(item.otherFeeMinor, item.currencyCode)}</div></td><td>{item.status === 'ACTIVE' ? '启用' : '停用'}</td><td>{displayTime(item.updatedAt)}</td><td>{canWrite && item.status === 'ACTIVE' ? <button className="text-button" type="button" disabled={busy} onClick={() => void archive(item)}>停用</button> : '—'}</td></tr>)}</tbody></table></div> }
function EstimatePanel({ query, busy, estimates, submit, reset }: { query: CustomShippingFeeQuery; busy: boolean; estimates?: ShippingFeeEstimate[]; submit: (event: FormEvent<HTMLFormElement>) => Promise<void>; reset: () => void }) { return <><form className="warehouse-archive-filters" aria-label="费用试算条件" onSubmit={(event) => void submit(event)}><label>目的国代码<input name="country" defaultValue={query.country} required maxLength={2} placeholder="例如：US" /></label><label>城市（可选）<input name="city" defaultValue={query.city} maxLength={100} /></label><label>邮编（可选）<input name="postalCode" defaultValue={query.postalCode} maxLength={32} /></label><label>实际重量（g）<input name="weightGrams" type="number" min={1} required defaultValue={query.weightGrams} /></label><label>长（mm）<input name="lengthMm" type="number" min={1} defaultValue={query.lengthMm} /></label><label>宽（mm）<input name="widthMm" type="number" min={1} defaultValue={query.widthMm} /></label><label>高（mm）<input name="heightMm" type="number" min={1} defaultValue={query.heightMm} /></label><label>体积重系数<input name="volumetricDivisor" type="number" min={1} defaultValue={query.volumetricDivisor || '5000'} /></label><label>计重方式<select name="weighingMode" defaultValue={query.weighingMode}><option value="ACTUAL">实重</option><option value="VOLUMETRIC">体积重</option><option value="MAXIMUM">取较大值</option></select></label><div className="warehouse-archive-filter-actions"><button type="button" onClick={reset}>重置</button><button className="is-primary" type="submit" disabled={busy}>{busy ? '正在试算…' : '运费试算'}</button></div></form><div className="warehouse-archive-table-wrap"><table aria-label="费用试算结果"><thead><tr><th>区域方案</th><th>费用规则</th><th>实际 / 体积 / 计费重量（g）</th><th>运费</th><th>其他费用</th><th>总金额</th></tr></thead><tbody>{estimates === undefined ? <tr><td colSpan={6}><div className="warehouse-archive-empty" role="status"><strong>请输入包裹信息后试算</strong><span>系统只返回匹配目的地、重量范围且启用的规则。</span></div></td></tr> : estimates.length === 0 ? <tr><td colSpan={6}><div className="warehouse-archive-empty" role="status"><strong>没有匹配的费用规则</strong><span>请核对目的地、重量或先维护对应区域规则。</span></div></td></tr> : estimates.map((item) => <tr key={item.ruleId}><td>{item.regionName}</td><td>{item.ruleName}</td><td>{item.actualWeightGrams} / {item.volumetricWeightGrams} / {item.chargeableWeightGrams}</td><td>{money(item.shippingFeeMinor, item.currencyCode)}</td><td>{money(item.otherFeeMinor, item.currencyCode)}</td><td><strong>{money(item.totalFeeMinor, item.currencyCode)}</strong></td></tr>)}</tbody></table></div></> }
function Dialog({ title, busy, close, children }: { title: string; busy: boolean; close: () => void; children: React.ReactNode }) { return <section className="warehouse-dialog-backdrop" role="presentation"><div className="warehouse-dialog" role="dialog" aria-modal="true" aria-label={title}><div className="table-heading"><h2>{title}</h2><DialogCloseButton disabled={busy} onClick={close} /></div>{children}</div></section> }
