export type UserRole = 'SYSTEM_ADMIN' | 'RECRUITMENT_ADMIN' | 'RECRUITER'
export interface AuthenticatedUser { id: string; username: string; displayName: string; role: UserRole }
export interface GroupProfile { id: string; name: string; shortName: string; timezone: string; description?: string; version: number; updatedAt: string }
export type CompanyStatus = 'ACTIVE' | 'INACTIVE'
export interface Company { id: string; name: string; code: string; status: CompanyStatus; location?: string; notes?: string; knowledgeIndustry?: string; knowledgeScale?: string; knowledgeSummary?: string; knowledgeApproved: boolean; knowledgeVersion: number; knowledgeApprovedAt?: string; version: number; createdAt: string; updatedAt: string }
export interface CompanyFormValue { name: string; code: string; location: string; notes: string }
export interface CompanyScope { id: string; name: string; code: string; status: CompanyStatus }
export interface HrUser { id: string; username: string; displayName: string; role: Exclude<UserRole, 'SYSTEM_ADMIN'>; enabled: boolean; companies: CompanyScope[]; createdAt: string; updatedAt: string }
export type BossAccountStatus = 'ACTIVE' | 'INACTIVE'
export type BossConnectionStatus = 'UNVERIFIED' | 'CONNECTED' | 'DEGRADED' | 'UNAVAILABLE'
export type BossCapability = 'JOB_SYNC' | 'CANDIDATE_READ' | 'MESSAGE_SEND'
export type BossGatewayType='LOCAL_CDP_CONNECTOR'
export interface BossAccount { id: string; company: CompanyScope; displayName: string; externalIdentifier: string; gatewayType: BossGatewayType; status: BossAccountStatus; connectionStatus: BossConnectionStatus; capabilities: BossCapability[]; lastCheckedAt?: string; version: number; createdAt: string; updatedAt: string }
export type JobPositionStatus = 'DRAFT' | 'ACTIVE' | 'CLOSED'
export interface JobPositionBossAccount { id: string; displayName: string; externalIdentifier: string; status: BossAccountStatus; connectionStatus: BossConnectionStatus }
export interface JobPosition { id: string; company: CompanyScope; bossAccount: JobPositionBossAccount; title: string; location: string; salaryMinK: number; salaryMaxK: number; salaryMonths: number; experienceRequirement: string; educationRequirement: string; description: string; screeningRequirements?: string; captureSource: 'MANUAL' | 'VISIBLE_PAGE' | 'UNREAD_OBSERVATION'; captureCompleteness?: number; capturedAt?: string; captureVerified: boolean; captureVerifiedAt?: string; lastObservedAt?: string; observationCount: number; replySummary?: string; salaryDisplay?: string; knowledgeApproved: boolean; knowledgeVersion: number; knowledgeApprovedAt?: string; safeReplyReady: boolean; safeReplyIssues: string[]; status: JobPositionStatus; version: number; createdAt: string; updatedAt: string }
export type CandidateSource = 'BOSS' | 'MANUAL'
export type CandidatePrivacyStatus = 'ACTIVE' | 'ANONYMIZED'
export type CandidateContactStatus = 'NEW' | 'SCREENING' | 'QUALIFIED' | 'REJECTED' | 'CONTACTING'
export type ScreeningOutcome = 'PASS' | 'REJECT' | 'REVIEW'
export type ScreeningDecisionType = 'HARD_RULE' | 'AI_SUGGESTION' | 'HUMAN_OVERRIDE'
export type MessageSenderType = 'CANDIDATE' | 'AI' | 'HR' | 'SYSTEM'
export type MessageDeliveryStatus = 'RECEIVED' | 'PENDING_REVIEW' | 'SENT' | 'REJECTED' | 'FAILED'
export interface ScreeningDecision { id: string; decisionType: ScreeningDecisionType; outcome: ScreeningOutcome; engineVersion?: string; modelVersion?: string; promptVersion?: string; rationale: string; createdBy?: { id: string; displayName: string }; createdAt: string }
export interface ConversationMessage { id: string; externalMessageId: string; direction: 'INBOUND' | 'OUTBOUND'; senderType: MessageSenderType; deliveryStatus: MessageDeliveryStatus; content: string; modelVersion?: string; promptVersion?: string; createdBy?: { id: string; displayName: string }; approvedAt?: string; createdAt: string }
export interface CandidateContact { id: string; candidateId: string; company: CompanyScope; jobPosition: { id: string; title: string }; bossAccount: { id: string; displayName: string }; source: CandidateSource; sourceReference: string; displayName: string; currentTitle?: string; yearsExperience?: number; education?: string; skillsSummary?: string; privacyStatus: CandidatePrivacyStatus; status: CandidateContactStatus; humanTakenOver: boolean; assignedHr?: { id: string; displayName: string }; latestHardRule?: ScreeningDecision; latestAiSuggestion?: ScreeningDecision; latestHumanOverride?: ScreeningDecision; latestMessageAt?:string;latestMessageDirection?:'INBOUND'|'OUTBOUND';latestMessagePreview?:string;needsHrFollowUp:boolean;pendingReviewDraft:boolean;latestAutoReplyStatus?:AutoReplyAttemptStatus;latestAutoReplyAt?:string; createdAt: string; updatedAt: string }
export interface CandidateDetail { candidate: CandidateContact; decisions: ScreeningDecision[]; messages: ConversationMessage[] }
export type AwayMode='IN_OFFICE'|'TEMPORARY'|'AFTER_HOURS'
export interface AutoReplyPolicy {accountId:string;accountName:string;companyId:string;companyName:string;accountStatus:BossAccountStatus;connectionStatus:BossConnectionStatus;messageSendCapable:boolean;monitorOnly:boolean;configured:boolean;enabled:boolean;awayMode:AwayMode;awayStartedAt?:string;awayEndsAt?:string;awayActive:boolean;autoSendEnabled:boolean;responseTimeoutMinutes:number;dailyLimit:number;minimumIntervalSeconds:number;sendingWindowStart:string;sendingWindowEnd:string;timezone:string;maxConsecutiveFailures:number;consecutiveFailures:number;pausedUntil?:string;lastSentAt?:string;sentToday:number;quotaDate?:string;replyTemplate:string;version:number}
export type AutoReplyAttemptStatus='CLAIMED'|'PENDING_REVIEW'|'SENT'|'FAILED'|'SKIPPED'
export interface AutoReplyAttempt {id:string;accountId:string;accountName:string;contactId:string;candidateName:string;jobTitle:string;status:AutoReplyAttemptStatus;resultMessage?:string;outboundMessageId?:string;attemptCount:number;createdAt:string;completedAt?:string}
export interface BrowserDevice {id:string;accountId:string;accountName:string;displayName:string;status:'ACTIVE'|'REVOKED';runtimeState:'DISABLED'|'RUNNING'|'PAUSED'|'OFFLINE';stopReason?:string;lastHeartbeatAt?:string;createdAt:string;revokedAt?:string}
export interface BrowserUnreadObservation {id:string;accountId:string;accountName:string;companyName:string;anonymousKey:string;unreadCount:number;unread:boolean;jobRecognized:boolean;previewRecognized:boolean;observedJobTitle?:string;draftMode?:'GENERIC'|'KNOWLEDGE';draftContent?:string;draftReason?:string;draftGeneratedAt?:string;eligibilityStatus:'OBSERVING'|'AWAY_INACTIVE'|'DETAIL_REQUIRED'|'READY_FOR_REVIEW'|'HR_REPLIED'|'HR_HANDLED'|'APPROVED_DRAFT'|'REJECTED'|'HUMAN_TAKEOVER';latestDirection?:'INBOUND'|'OUTBOUND';latestMessageAt?:string;detailVerifiedAt?:string;reviewStatus:'PENDING'|'APPROVED'|'REJECTED'|'HUMAN_TAKEOVER';reviewedContent?:string;reviewNote?:string;reviewedAt?:string;fillStatus:'NONE'|'READY'|'CLAIMED'|'FILLED'|'UNKNOWN';filledAt?:string;resolutionStatus:'UNRESOLVED'|'HR_REPLIED'|'HR_SENT_AFTER_DRAFT';resolvedAt?:string;firstSeenAt:string;lastSeenAt:string}
export type ConnectorCapabilityName='CHAT_LIST_READ'|'CONVERSATION_DETAIL_READ'|'JOB_LIST_READ'|'SEND_MESSAGE'|'REQUEST_RESUME'|'EXCHANGE_WECHAT'|'EXCHANGE_PHONE'
export type ConnectorCapabilityStatus='UNVERIFIED'|'READ_ONLY_VERIFIED'|'READY_FOR_MANUAL_TEST'|'PRODUCTION_APPROVED'|'BLOCKED'
export interface ConnectorCapability{id:string;deviceId:string;accountId:string;accountName:string;companyName:string;capability:ConnectorCapabilityName;status:ConnectorCapabilityStatus;reason:string;verifiedAt?:string;updatedAt:string}
export interface ConnectorActionTask{id:string;accountId:string;accountName:string;companyName:string;observationId?:string;anonymousKey?:string;actionType:'SEND_MESSAGE'|'REQUEST_RESUME'|'EXCHANGE_WECHAT'|'EXCHANGE_PHONE';status:'BLOCKED_UNVERIFIED'|'WAITING_MANUAL_TEST'|'READY'|'LEASED'|'CANCELLED'|'SUCCEEDED'|'FAILED'|'UNKNOWN';reason:string;requestedBy:string;createdAt:string;updatedAt:string}
export interface ConnectorActionLease{id:string;taskId:string;accountId:string;accountName:string;actionType:ConnectorActionTask['actionType'];status:'CLAIMED'|'SUCCEEDED'|'FAILED'|'UNKNOWN'|'EXPIRED';targetDigest?:string;leasedAt:string;leaseUntil:string;resultReason?:string;completedAt?:string;updatedAt:string}
export interface ConnectorProductionApproval{id:string;deviceId:string;accountId:string;accountName:string;companyName:string;actionType:ConnectorActionTask['actionType'];status:'PENDING_SECOND_APPROVAL'|'APPROVED'|'REVOKED'|'EXPIRED';hourlyLimit:number;dailyLimit:number;requestedBy:string;requestedAt:string;approvedBy?:string;approvedAt?:string;expiresAt?:string;reason:string;updatedAt:string}
export interface ConnectorOfflineDrill{id:string;deviceId:string;accountId:string;accountName:string;actionType:ConnectorActionTask['actionType'];outcome:'PASSED'|'FAILED';evidenceSource:'FIXTURE_ONLY';beforeDigest:string;afterDigest:string;receiptDigest:string;failureReason?:string;createdAt:string}
export interface ConnectorValidationCase{id:string;deviceId:string;accountId:string;accountName:string;companyName:string;actionType:ConnectorActionTask['actionType'];status:'PREPARED'|'WAITING_REAL_PAGE'|'MANUAL_TEST_RUNNING'|'PASSED'|'FAILED'|'CANCELLED';prerequisites:string[];expectedResult:string;lastFailureReason?:string;evidenceObservedAt?:string;testStartedAt?:string;testExpiresAt?:string;completedAt?:string;resultNote?:string;preparedAt:string;updatedAt:string}
export type ResumeIntakeSource='MANUAL'|'BOSS_VISIBLE'
export type ResumeIntakeStatus='PENDING_REVIEW'|'APPROVED_FOR_AI'|'REJECTED'
export interface ResumeIntake {id:string;contactId:string;candidateName:string;jobTitle:string;accountName:string;source:ResumeIntakeSource;anonymousKey:string;displayLabel:string;status:ResumeIntakeStatus;receivedAt:string;reviewedBy?:string;reviewedAt?:string;reviewNote?:string;createdAt:string}
export type ResumeAnalysisRecommendation='PRIORITY_VIEW'|'NORMAL_VIEW'|'INFORMATION_NEEDED'
export interface ResumeAnalysisEvidence {criterion:string;finding:string;status:'FOUND'|'NOT_FOUND'|'UNCLEAR'}
export interface ResumeAnalysisResult {recommendation:ResumeAnalysisRecommendation;summary:string;evidence:ResumeAnalysisEvidence[];gaps:string[];risks:string[];followUpQuestions:string[]}
export type ResumeAnalysisFeedbackType='ADOPTED'|'AMENDED'|'NOT_USED'
export interface ResumeAnalysisFeedback {id:string;feedbackType:ResumeAnalysisFeedbackType;note:string;createdBy:string;createdAt:string}
export interface ResumeAnalysisRun {id:string;resumeIntakeId:string;candidateName:string;jobTitle:string;provider:string;modelVersion:string;status:'SUCCEEDED'|'FAILED';result?:ResumeAnalysisResult;errorMessage?:string;feedback:ResumeAnalysisFeedback[];createdBy:string;createdAt:string;resultExpiresAt?:string;resultPurgedAt?:string}
export interface OpenAiConfigurationStatus {enabled:boolean;apiKeyConfigured:boolean;modelConfigured:boolean;officialEndpoint:boolean;ready:boolean;model:string;endpointHost:string;timeoutSeconds:number;resultRetentionDays:number;requestStorageDisabled:boolean;status:'READY_FOR_TEST'|'CONFIGURATION_REQUIRED';missingConfiguration:string[]}
export interface OpenAiConnectionTest {success:boolean;model:string;requestId:string;elapsedMilliseconds:number;checkedAt:string;message:string}
export interface AuditLog { id: string; actorName: string; action: string; targetType: string; targetId?: string; targetLabel?: string; result: 'SUCCESS' | 'FAILURE'; details?: string; requestId?:string; occurredAt: string }
export interface GatewaySnapshot { operation:string;consecutiveFailures:number;circuitOpenUntil?:string;requestsInWindow:number;availablePermits:number }
export interface OperationsSummary { status:'READY';flywayVersion:string;auditAppendOnly:boolean;activeBrowserDevices:number;staleBrowserDevices:number;unreadObservations:number;unverifiedPageCaptures:number;checkedAt:string;gateways:GatewaySnapshot[] }
export interface ApiErrorBody { status: number; code: string; message: string; fieldErrors?: Record<string, string> }
