package ai.xzkj.recruitment.resumes;
import ai.xzkj.recruitment.auth.SystemUser;import ai.xzkj.recruitment.candidates.CandidateJobContact;import org.junit.jupiter.api.Test;import java.time.Instant;import static org.assertj.core.api.Assertions.assertThat;import static org.mockito.Mockito.mock;
class ResumeIntakeTest{
 @Test void staysPendingUntilAnHrExplicitlyApprovesItForAi(){ResumeIntake intake=new ResumeIntake(mock(CandidateJobContact.class),ResumeIntakeSource.MANUAL,"a".repeat(64),"候选人已提供附件简历",Instant.parse("2026-08-30T06:00:00Z"));assertThat(intake.getStatus()).isEqualTo(ResumeIntakeStatus.PENDING_REVIEW);intake.review(ResumeIntakeStatus.APPROVED_FOR_AI,"已核对来源",mock(SystemUser.class),Instant.parse("2026-08-30T06:05:00Z"));assertThat(intake.getStatus()).isEqualTo(ResumeIntakeStatus.APPROVED_FOR_AI);assertThat(intake.getReviewNote()).isEqualTo("已核对来源");}
 @Test void capsQueueAttemptsAndResetsOnlyForANewAnalysisCycle(){Instant now=Instant.parse("2026-08-30T06:00:00Z");ResumeIntake intake=new ResumeIntake(mock(CandidateJobContact.class),ResumeIntakeSource.MANUAL,"a".repeat(64),"候选人已提供附件简历",now);intake.queueAnalysis(now);for(int attempt=1;attempt<=ResumeIntake.MAX_ANALYSIS_ATTEMPTS;attempt++){assertThat(intake.claimAnalysis(now.plusSeconds(attempt))).isTrue();boolean retrying=intake.retryAnalysisQueue("上游暂时不可用",now.plusSeconds(attempt));if(attempt<ResumeIntake.MAX_ANALYSIS_ATTEMPTS){assertThat(retrying).isTrue();}else assertThat(retrying).isFalse();}assertThat(intake.getAnalysisQueueStatus()).isEqualTo("FAILED");assertThat(intake.getAnalysisQueueAttempts()).isEqualTo(ResumeIntake.MAX_ANALYSIS_ATTEMPTS);intake.queueAnalysis(now.plusSeconds(60));assertThat(intake.getAnalysisQueueStatus()).isEqualTo("QUEUED");assertThat(intake.getAnalysisQueueAttempts()).isZero();}
 @Test void yieldingToRepliesDoesNotConsumeAnalysisAttempt(){Instant now=Instant.parse("2026-08-30T06:00:00Z");ResumeIntake intake=new ResumeIntake(mock(CandidateJobContact.class),ResumeIntakeSource.MANUAL,"a".repeat(64),"候选人已提供附件简历",now);intake.queueAnalysis(now);assertThat(intake.claimAnalysis(now.plusSeconds(1))).isTrue();intake.deferAnalysisForReplyPriority(now.plusSeconds(2));assertThat(intake.getAnalysisQueueStatus()).isEqualTo("QUEUED");assertThat(intake.getAnalysisQueueAttempts()).isZero();assertThat(intake.getAnalysisQueueNextAttemptAt()).isEqualTo(now.plusSeconds(7));}
 @Test void reprocessingAResumeDoesNotQueueAiAgainWhenAnalysisAlreadySucceeded(){Instant now=Instant.parse("2026-08-30T06:00:00Z");ResumeIntake intake=new ResumeIntake(mock(CandidateJobContact.class),ResumeIntakeSource.BOSS_VISIBLE,"a".repeat(64),"BOSS 简历",now);intake.analysisSucceeded(now);intake.queueAnalysis(now.plusSeconds(5));assertThat(intake.getAnalysisQueueStatus()).isEqualTo("NONE");}
 @Test void documentProcessingUsesARecoverableBoundedQueue(){Instant now=Instant.parse("2026-08-30T06:00:00Z");ResumeIntake intake=new ResumeIntake(mock(CandidateJobContact.class),ResumeIntakeSource.BOSS_VISIBLE,"a".repeat(64),"BOSS 简历",now);intake.queueDocumentProcessing(now);assertThat(intake.getProcessingStatus()).isEqualTo("QUEUED");assertThat(intake.claimDocumentProcessing(now.plusSeconds(1))).isTrue();assertThat(intake.getProcessingStatus()).isEqualTo("PROCESSING");intake.recoverDocumentProcessingLease(now.plusSeconds(181));assertThat(intake.getProcessingStatus()).isEqualTo("QUEUED");assertThat(intake.getProcessingNextAttemptAt()).isEqualTo(now.plusSeconds(181));}
 @Test void documentProcessingStopsAfterFiveAttempts(){Instant now=Instant.parse("2026-08-30T06:00:00Z");ResumeIntake intake=new ResumeIntake(mock(CandidateJobContact.class),ResumeIntakeSource.BOSS_VISIBLE,"a".repeat(64),"BOSS 简历",now);intake.queueDocumentProcessing(now);for(int attempt=1;attempt<=ResumeIntake.MAX_DOCUMENT_PROCESSING_ATTEMPTS;attempt++){assertThat(intake.claimDocumentProcessing(now.plusSeconds(attempt))).isTrue();if(attempt<ResumeIntake.MAX_DOCUMENT_PROCESSING_ATTEMPTS){assertThat(intake.retryDocumentProcessing("暂时不可用",now.plusSeconds(attempt+1))).isTrue();}}assertThat(intake.retryDocumentProcessing("再次失败",now.plusSeconds(100))).isFalse();assertThat(intake.getProcessingStatus()).isEqualTo("FAILED");assertThat(intake.getFailureCode()).isEqualTo("RESUME_PROCESSING_RETRY_EXHAUSTED");}
}
