package ai.xzkj.recruitment.ai;

import ai.xzkj.recruitment.audit.AuditService;import ai.xzkj.recruitment.auth.*;import ai.xzkj.recruitment.candidates.*;import ai.xzkj.recruitment.common.ApiException;import ai.xzkj.recruitment.jobs.*;import ai.xzkj.recruitment.organization.Company;import ai.xzkj.recruitment.resilience.GatewayResilienceGuard;import org.springframework.http.HttpStatus;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import tools.jackson.databind.ObjectMapper;
import java.nio.charset.StandardCharsets;import java.security.MessageDigest;import java.util.*;import java.util.stream.Collectors;

@Service
public class AiAssistanceService{
 private final AiProperties properties;private final MockAiGateway mock;private final OpenAiCompatibleGateway real;private final AiAssistanceRunRepository runs;private final CandidateJobContactRepository contacts;private final ScreeningDecisionRepository decisions;private final CurrentUserService users;private final AuditService audit;private final ObjectMapper json;private final GatewayResilienceGuard guard;
 public AiAssistanceService(AiProperties properties,MockAiGateway mock,OpenAiCompatibleGateway real,AiAssistanceRunRepository runs,CandidateJobContactRepository contacts,ScreeningDecisionRepository decisions,CurrentUserService users,AuditService audit,ObjectMapper json,GatewayResilienceGuard guard){this.properties=properties;this.mock=mock;this.real=real;this.runs=runs;this.contacts=contacts;this.decisions=decisions;this.users=users;this.audit=audit;this.json=json;this.guard=guard;}
 @Transactional(noRollbackFor=ApiException.class) public JobParseResponse parseJob(String description){SystemUser user=users.requireCurrentUser();if(user.getRole()==UserRole.RECRUITER)throw new ApiException(HttpStatus.FORBIDDEN,"FORBIDDEN","当前账号没有 AI 职位解析权限");String clean=required(description,10000);String provider=properties.real()?"OPENAI_COMPATIBLE":"MOCK";try{var suggestion=guard.execute("ai.job-parse",()->gateway().parseJob(clean),Objects::nonNull,this::gatewayFailure);String result=write(suggestion);AiAssistanceRun run=runs.save(new AiAssistanceRun("JOB_PARSE",null,null,provider,properties.model(),properties.promptVersion(),hash(clean),"SUCCEEDED",null,suggestion.rationale(),result,null,user));audit.success("AI_PARSE_JOB","AI_ASSISTANCE",run.getId(),"JOB_PARSE",provider+" 生成职位结构化建议，需 HR 复核");return new JobParseResponse(run.getId(),provider,properties.model(),properties.promptVersion(),suggestion);}catch(RuntimeException e){runs.save(new AiAssistanceRun("JOB_PARSE",null,null,provider,properties.model(),properties.promptVersion(),hash(clean),"FAILED",null,null,null,limit(e.getMessage(),1000),user));throw new ApiException(HttpStatus.BAD_GATEWAY,"AI_PROVIDER_FAILED","职位解析服务暂时不可用");}}
 @Transactional(noRollbackFor=ApiException.class) public CandidateScreenResponse screen(UUID contactId){SystemUser user=users.requireCurrentUser();CandidateJobContact contact=contacts.findWithDetailsById(contactId).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"CANDIDATE_CONTACT_NOT_FOUND","候选人职位关系不存在"));if(!canAccess(contact.getCandidate().getCompany().getId(),user))throw new ApiException(HttpStatus.FORBIDDEN,"COMPANY_SCOPE_FORBIDDEN","当前账号无权访问该企业数据");if(contact.getCandidate().getPrivacyStatus()==CandidatePrivacyStatus.ANONYMIZED)throw new ApiException(HttpStatus.CONFLICT,"CANDIDATE_ANONYMIZED","已匿名候选人不能执行 AI 筛选");if(properties.real()&&!properties.allowCandidateData())throw new ApiException(HttpStatus.CONFLICT,"AI_CANDIDATE_DATA_DISABLED","预发布环境未允许向外部 AI 发送候选人事实");var profile=contact.getCandidate();var job=contact.getJobPosition();var facts=new AiGateway.CandidateFacts(profile.getCurrentTitle(),profile.getYearsExperience(),profile.getEducation(),profile.getSkillsSummary());var jobFacts=new AiGateway.JobFacts(job.getTitle(),job.getExperienceRequirement(),job.getEducationRequirement(),job.getScreeningRequirements(),job.getDescription());String input=facts+"|"+jobFacts;String provider=properties.real()?"OPENAI_COMPATIBLE":"MOCK";try{var suggestion=guard.execute("ai.candidate-screen",()->gateway().screenCandidate(facts,jobFacts),Objects::nonNull,this::gatewayFailure);ScreeningDecision decision=decisions.save(new ScreeningDecision(contact,ScreeningDecisionType.AI_SUGGESTION,suggestion.outcome(),null,properties.model(),properties.promptVersion(),limit(suggestion.rationale(),3000),user));ScreeningOutcome hard=decisions.findByContactIdOrderByCreatedAtDesc(contactId).stream().filter(d->d.getDecisionType()==ScreeningDecisionType.HARD_RULE).map(ScreeningDecision::getOutcome).findFirst().orElse(ScreeningOutcome.REVIEW);contact.applyScreening(hard,suggestion.outcome());AiAssistanceRun run=runs.save(new AiAssistanceRun("CANDIDATE_SCREEN",job,contact,provider,properties.model(),properties.promptVersion(),hash(input),"SUCCEEDED",suggestion.outcome().name(),suggestion.rationale(),null,null,user));audit.success("AI_SCREEN_CANDIDATE","CANDIDATE_CONTACT",contactId,profile.getSource()+" · "+profile.getDedupKey().substring(0,8),provider+" 辅助筛选建议 "+suggestion.outcome()+"，需 HR 复核");return new CandidateScreenResponse(run.getId(),provider,properties.model(),properties.promptVersion(),ScreeningDecisionResponse.from(decision));}catch(ApiException e){throw e;}catch(RuntimeException e){runs.save(new AiAssistanceRun("CANDIDATE_SCREEN",job,contact,provider,properties.model(),properties.promptVersion(),hash(input),"FAILED",null,null,null,limit(e.getMessage(),1000),user));throw new ApiException(HttpStatus.BAD_GATEWAY,"AI_PROVIDER_FAILED","候选人 AI 筛选服务暂时不可用");}}
 private AiGateway gateway(){return properties.real()?real:mock;}private <T>T gatewayFailure(GatewayResilienceGuard.FailureReason reason){throw new IllegalStateException("AI Gateway 保护已触发："+reason.name());}private boolean canAccess(UUID company,SystemUser user){return user.getRole()==UserRole.SYSTEM_ADMIN||user.getCompanyScopes().stream().map(Company::getId).collect(Collectors.toSet()).contains(company);}private String required(String v,int max){if(v==null||v.isBlank())throw new ApiException(HttpStatus.BAD_REQUEST,"AI_INPUT_REQUIRED","请输入职位 JD");String clean=v.trim();if(clean.length()>max)throw new ApiException(HttpStatus.BAD_REQUEST,"AI_INPUT_TOO_LONG","职位 JD 不能超过 10000 字");return clean;}private String hash(String v){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(v.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}private String write(Object value){try{return json.writeValueAsString(value);}catch(Exception e){throw new IllegalStateException(e);}}private String limit(String v,int max){if(v==null)return null;return v.length()<=max?v:v.substring(0,max);}
 public record JobParseResponse(UUID runId,String provider,String modelVersion,String promptVersion,AiGateway.JobSuggestion suggestion){}public record CandidateScreenResponse(UUID runId,String provider,String modelVersion,String promptVersion,ScreeningDecisionResponse decision){}
}
