package ai.xzkj.recruitment.ai;
import ai.xzkj.recruitment.candidates.ScreeningOutcome;import org.springframework.stereotype.Component;
import java.util.regex.*;
@Component
public class MockAiGateway implements AiGateway{
 public JobSuggestion parseJob(String text){String title=text.lines().map(String::trim).filter(s->!s.isBlank()).findFirst().orElse("待确认职位");String location=contains(text,"上海","北京","深圳","杭州","广州");Matcher salary=Pattern.compile("(\\d{1,3})\\s*[kK]?\\s*[-~至]\\s*(\\d{1,3})\\s*[kK]").matcher(text);boolean salaryFound=salary.find();int min=salaryFound?Integer.parseInt(salary.group(1)):10,max=salaryFound?Math.max(min,Integer.parseInt(salary.group(2))):20;Matcher months=Pattern.compile("(1[2-9]|2\\d)薪").matcher(text);int salaryMonths=months.find()?Integer.parseInt(months.group(1)):12;Matcher years=Pattern.compile("(\\d+)\\s*[-~至]\\s*(\\d+)\\s*年").matcher(text);String experience=years.find()?years.group(1)+"-"+years.group(2)+" 年":"待确认";String education=contains(text,"博士","硕士","本科","大专");String screening="请人工确认核心技能、工作年限和学历要求";return new JobSuggestion(limit(title,120),location,min,max,salaryMonths,experience,education,screening,"已从 JD 提取结构化字段，启用前必须由 HR 复核。");}
 public ScreeningSuggestion screenCandidate(CandidateFacts c,JobFacts j){if(c.yearsExperience()==null||blank(c.skillsSummary()))return new ScreeningSuggestion(ScreeningOutcome.REVIEW,"候选人年限或技能信息不完整，建议人工复核。");Matcher required=Pattern.compile("(\\d+)").matcher(j.experienceRequirement());if(required.find()&&c.yearsExperience()<Integer.parseInt(required.group(1)))return new ScreeningSuggestion(ScreeningOutcome.REJECT,"工作年限低于职位要求；这是 AI 建议，不会替代人工决策。");return new ScreeningSuggestion(ScreeningOutcome.PASS,"候选人基础年限和技能摘要与职位要求大致匹配，建议 HR 继续复核。");}
 private String contains(String text,String...values){for(String value:values)if(text.contains(value))return value;return"待确认";}private boolean blank(String v){return v==null||v.isBlank();}private String limit(String v,int n){return v.length()<=n?v:v.substring(0,n);}
}
