package ai.xzkj.recruitment.localconnector;
import ai.xzkj.recruitment.auth.SystemUser;import ai.xzkj.recruitment.boss.BossAccount;import jakarta.persistence.*;import java.time.Instant;import java.util.List;import java.util.Objects;import java.util.UUID;
@Entity @Table(name="local_connector_unread_observations") public class BrowserUnreadObservation{
 @Id private UUID id;@ManyToOne(fetch=FetchType.LAZY,optional=false)@JoinColumn(name="local_connector_device_id")private BrowserDevice device;@ManyToOne(fetch=FetchType.LAZY,optional=false)@JoinColumn(name="boss_account_id")private BossAccount account;@Column(name="chat_digest",nullable=false,length=64)private String chatDigest;@Column(name="preview_digest",length=64)private String previewDigest;@Column(name="job_digest",length=64)private String jobDigest;@Column(name="observed_job_title",length=120)private String observedJobTitle;@Column(name="time_digest",length=64)private String timeDigest;@Column(name="unread_count",nullable=false)private int unreadCount;@Column(nullable=false)private boolean unread;@Column(name="draft_mode",length=24)private String draftMode;@Column(name="draft_content",columnDefinition="TEXT")private String draftContent;@Column(name="draft_reason",length=200)private String draftReason;@Column(name="draft_generated_at")private Instant draftGeneratedAt;@Column(name="draft_qualification",length=32)private String draftQualification;@Column(name="matched_job_position_id")private UUID matchedJobPositionId;@Column(name="manual_match_job_position_id")private UUID manualMatchJobPositionId;@Column(name="manual_match_title_key",length=160)private String manualMatchTitleKey;@Column(name="manual_matched_at")private Instant manualMatchedAt;@Column(name="draft_blocker_codes",length=500)private String draftBlockerCodes;@Column(name="draft_company_knowledge_version")private Integer draftCompanyKnowledgeVersion;@Column(name="draft_job_knowledge_version")private Integer draftJobKnowledgeVersion;@Column(name="eligibility_status",nullable=false,length=32)private String eligibilityStatus="OBSERVING";@Column(name="latest_message_digest",length=64)private String latestMessageDigest;@Column(name="latest_direction",length=16)private String latestDirection;@Column(name="latest_message_at")private Instant latestMessageAt;@Column(name="detail_verified_at")private Instant detailVerifiedAt;@Column(name="review_status",nullable=false,length=24)private String reviewStatus="PENDING";@Column(name="reviewed_content",columnDefinition="TEXT")private String reviewedContent;@ManyToOne(fetch=FetchType.LAZY)@JoinColumn(name="reviewed_by")private SystemUser reviewedBy;@Column(name="reviewed_at")private Instant reviewedAt;@Column(name="review_note",length=300)private String reviewNote;@Column(name="resolution_status",nullable=false,length=32)private String resolutionStatus="UNRESOLVED";@Column(name="resolved_at")private Instant resolvedAt;@Column(name="first_seen_at",nullable=false)private Instant firstSeenAt;@Column(name="last_seen_at",nullable=false)private Instant lastSeenAt;@Column(name="updated_at",nullable=false)private Instant updatedAt;
 protected BrowserUnreadObservation(){}BrowserUnreadObservation(BrowserDevice d,String chat,Instant first,Instant now){id=UUID.randomUUID();device=d;account=d.getBossAccount();chatDigest=chat;firstSeenAt=first;lastSeenAt=now;updatedAt=now;unread=false;}
 void observe(UnreadObservationEntry e,Instant now){previewDigest=e.previewDigest();jobDigest=e.jobDigest();observedJobTitle=clean(e.jobTitle());timeDigest=e.timeDigest();unreadCount=e.unreadCount();if(unreadCount>0&&!unread)startNewCycle(now);unread=unreadCount>0;if(e.firstSeenAt()!=null&&e.firstSeenAt().isBefore(firstSeenAt))firstSeenAt=e.firstSeenAt();lastSeenAt=e.lastSeenAt()==null?now:e.lastSeenAt();updatedAt=now;}
 void prepareDraft(String mode,String content,String reason,String qualification,UUID matchedJobId,List<String> blockerCodes,Integer companyVersion,Integer jobVersion,Instant now){String blockers=blockerCodes==null||blockerCodes.isEmpty()?null:String.join(",",blockerCodes);boolean changed=draftGeneratedAt!=null&&(!Objects.equals(draftMode,mode)||!Objects.equals(draftContent,content)||!Objects.equals(draftQualification,qualification)||!Objects.equals(matchedJobPositionId,matchedJobId)||!Objects.equals(draftBlockerCodes,blockers)||!Objects.equals(draftCompanyKnowledgeVersion,companyVersion)||!Objects.equals(draftJobKnowledgeVersion,jobVersion));if(changed&&"APPROVED".equals(reviewStatus)){reviewStatus="PENDING";reviewedContent=null;reviewedBy=null;reviewedAt=null;reviewNote="企业或岗位资料已变化，原草稿批准已自动失效，请重新核对";}draftMode=mode;draftContent=content;draftReason=reason;draftQualification=qualification;matchedJobPositionId=matchedJobId;draftBlockerCodes=blockers;draftCompanyKnowledgeVersion=companyVersion;draftJobKnowledgeVersion=jobVersion;draftGeneratedAt=now;}
 void attachSource(BrowserDevice source){device=source;account=source.getBossAccount();}
 void manuallyMatchJob(UUID jobId,String titleKey,Instant now){manualMatchJobPositionId=jobId;manualMatchTitleKey=titleKey;manualMatchedAt=now;}
 void clearManualJobMatch(){manualMatchJobPositionId=null;manualMatchTitleKey=null;manualMatchedAt=null;}
 void verifyDetail(String digest,String direction,Instant messageAt,boolean selectedUnread,Instant now){latestMessageDigest=digest;latestDirection=direction;latestMessageAt=messageAt;detailVerifiedAt=now;if("OUTBOUND".equals(direction)){unread=false;unreadCount=0;eligibilityStatus="HR_REPLIED";resolutionStatus="HR_REPLIED";resolvedAt=now;}else{if(!unread&&!"UNRESOLVED".equals(resolutionStatus))startNewCycle(messageAt.isAfter(now)?now:messageAt);unread=true;unreadCount=Math.max(1,unreadCount);eligibilityStatus="OBSERVING";resolutionStatus="UNRESOLVED";resolvedAt=null;}updatedAt=now;}
 void evaluate(Instant now,int timeoutMinutes,boolean awayActive){if(!unread){eligibilityStatus="HR_HANDLED";return;}if(!"PENDING".equals(reviewStatus)){eligibilityStatus=switch(reviewStatus){case"APPROVED"->"APPROVED_DRAFT";case"REJECTED"->"REJECTED";default->"HUMAN_TAKEOVER";};return;}if(!awayActive){eligibilityStatus="AWAY_INACTIVE";return;}if(detailVerifiedAt==null||detailVerifiedAt.isBefore(now.minusSeconds(180))){eligibilityStatus="DETAIL_REQUIRED";return;}if(!"INBOUND".equals(latestDirection)){eligibilityStatus="HR_REPLIED";return;}eligibilityStatus=firstSeenAt.plusSeconds(timeoutMinutes*60L).isAfter(now)?"OBSERVING":"READY_FOR_REVIEW";}
 void markMissingFromLatestSnapshot(Instant now){if(!unread)return;eligibilityStatus="SNAPSHOT_CONFIRMATION_REQUIRED";latestMessageDigest=null;latestDirection=null;latestMessageAt=null;detailVerifiedAt=null;updatedAt=now;}
 void review(String decision,String content,String note,SystemUser user,Instant now){reviewStatus=decision;reviewedContent="APPROVED".equals(decision)?content:null;reviewNote=note;reviewedBy=user;reviewedAt=now;eligibilityStatus=switch(decision){case"APPROVED"->"APPROVED_DRAFT";case"REJECTED"->"REJECTED";default->"HUMAN_TAKEOVER";};updatedAt=now;}
 void archiveReplacedSource(Instant now){unread=false;unreadCount=0;eligibilityStatus="HR_HANDLED";resolutionStatus="SOURCE_REPLACED";resolvedAt=now;updatedAt=now;}
 private void startNewCycle(Instant now){unread=false;firstSeenAt=now;eligibilityStatus="OBSERVING";latestMessageDigest=null;latestDirection=null;latestMessageAt=null;detailVerifiedAt=null;reviewStatus="PENDING";reviewedContent=null;reviewedBy=null;reviewedAt=null;reviewNote=null;resolutionStatus="UNRESOLVED";resolvedAt=null;}
 private String clean(String value){if(value==null||value.isBlank())return null;String v=value.trim();return v.length()<=120?v:v.substring(0,120);}
 public UUID getId(){return id;}public BrowserDevice getDevice(){return device;}public BossAccount getAccount(){return account;}public String getChatDigest(){return chatDigest;}public String getPreviewDigest(){return previewDigest;}public String getJobDigest(){return jobDigest;}public String getObservedJobTitle(){return observedJobTitle;}public int getUnreadCount(){return unreadCount;}public boolean isUnread(){return unread;}public String getDraftMode(){return draftMode;}public String getDraftContent(){return draftContent;}public String getDraftReason(){return draftReason;}public Instant getDraftGeneratedAt(){return draftGeneratedAt;}public String getDraftQualification(){return draftQualification;}public UUID getMatchedJobPositionId(){return matchedJobPositionId;}public UUID getManualMatchJobPositionId(){return manualMatchJobPositionId;}public String getManualMatchTitleKey(){return manualMatchTitleKey;}public Instant getManualMatchedAt(){return manualMatchedAt;}public List<String> getDraftBlockerCodes(){return draftBlockerCodes==null||draftBlockerCodes.isBlank()?List.of():List.of(draftBlockerCodes.split(","));}public Integer getDraftCompanyKnowledgeVersion(){return draftCompanyKnowledgeVersion;}public Integer getDraftJobKnowledgeVersion(){return draftJobKnowledgeVersion;}public String getEligibilityStatus(){return eligibilityStatus;}public String getLatestDirection(){return latestDirection;}public Instant getLatestMessageAt(){return latestMessageAt;}public Instant getDetailVerifiedAt(){return detailVerifiedAt;}public String getReviewStatus(){return reviewStatus;}public String getReviewedContent(){return reviewedContent;}public String getReviewNote(){return reviewNote;}public Instant getReviewedAt(){return reviewedAt;}public String getResolutionStatus(){return resolutionStatus;}public Instant getResolvedAt(){return resolvedAt;}public Instant getFirstSeenAt(){return firstSeenAt;}public Instant getLastSeenAt(){return lastSeenAt;}
}
