package ai.xzkj.recruitment.localconnector;
// Internal transport records for the local connector API.
import jakarta.validation.Valid;import jakarta.validation.constraints.*;import java.time.Instant;import java.util.*;
record CreatePairingRequest(@NotNull UUID accountId){}
record PairDeviceRequest(@NotBlank@Size(max=200)String pairingToken,@NotBlank@Size(max=100)String deviceName){}
record HeartbeatRequest(@NotBlank@Pattern(regexp="DISABLED|RUNNING|PAUSED|OFFLINE")String state,@Size(max=300)String reason){}
record PairingResponse(String pairingToken,Instant expiresAt,UUID accountId,String accountName){}
record DeviceCredentialsResponse(UUID deviceId,String deviceToken,UUID accountId,String accountName){}
record DeviceResponse(UUID id,UUID accountId,String accountName,String displayName,String status,String runtimeState,String stopReason,Instant lastHeartbeatAt,Instant createdAt,Instant revokedAt){static DeviceResponse from(BrowserDevice d){return new DeviceResponse(d.getId(),d.getBossAccount().getId(),d.getBossAccount().getDisplayName(),d.getDisplayName(),d.getStatus(),d.getRuntimeState(),d.getStopReason(),d.getLastHeartbeatAt(),d.getCreatedAt(),d.getRevokedAt());}}
record UnreadObservationEntry(@NotBlank@Pattern(regexp="[a-f0-9]{64}")String chatDigest,@Pattern(regexp="[a-f0-9]{64}")String previewDigest,@Pattern(regexp="[a-f0-9]{64}")String jobDigest,@Size(max=120)String jobTitle,@Pattern(regexp="[a-f0-9]{64}")String timeDigest,@Min(0)@Max(999)int unreadCount,Instant firstSeenAt,Instant lastSeenAt){}
record UnreadObservationSnapshot(@NotNull@Size(max=200)List<@Valid UnreadObservationEntry> entries){}
record UnreadObservationSyncResponse(int activeUnread,int received,Instant serverNow){}
record SelectedConversationSnapshot(@NotBlank@Pattern(regexp="[a-f0-9]{64}")String chatDigest,@NotBlank@Pattern(regexp="[a-f0-9]{64}")String messageDigest,@NotBlank@Pattern(regexp="INBOUND|OUTBOUND")String direction,@NotNull Instant messageAt,boolean selectedUnread){}
record ObservationReviewRequest(@NotBlank@Pattern(regexp="APPROVED|REJECTED|HUMAN_TAKEOVER")String decision,@Size(max=2000)String content,@Size(max=300)String note){}
record UnreadObservationResponse(UUID id,UUID accountId,String accountName,String companyName,String anonymousKey,int unreadCount,boolean unread,boolean jobRecognized,boolean previewRecognized,String observedJobTitle,String draftMode,String draftContent,String draftReason,Instant draftGeneratedAt,String eligibilityStatus,String latestDirection,Instant latestMessageAt,Instant detailVerifiedAt,String reviewStatus,String reviewedContent,String reviewNote,Instant reviewedAt,String resolutionStatus,Instant resolvedAt,Instant firstSeenAt,Instant lastSeenAt){static UnreadObservationResponse from(BrowserUnreadObservation x){return new UnreadObservationResponse(x.getId(),x.getAccount().getId(),x.getAccount().getDisplayName(),x.getAccount().getCompany().getName(),x.getChatDigest().substring(0,12),x.getUnreadCount(),x.isUnread(),x.getJobDigest()!=null,x.getPreviewDigest()!=null,x.getObservedJobTitle(),x.getDraftMode(),x.getDraftContent(),x.getDraftReason(),x.getDraftGeneratedAt(),x.getEligibilityStatus(),x.getLatestDirection(),x.getLatestMessageAt(),x.getDetailVerifiedAt(),x.getReviewStatus(),x.getReviewedContent(),x.getReviewNote(),x.getReviewedAt(),x.getResolutionStatus(),x.getResolvedAt(),x.getFirstSeenAt(),x.getLastSeenAt());}}
record CreateActionTaskRequest(@NotNull UUID observationId,@NotBlank@Pattern(regexp="SEND_MESSAGE|REQUEST_RESUME|EXCHANGE_WECHAT|EXCHANGE_PHONE")String actionType){}
record ConnectorCapabilityResponse(UUID id,UUID deviceId,UUID accountId,String accountName,String companyName,String capability,String status,String reason,Instant verifiedAt,Instant updatedAt){static ConnectorCapabilityResponse from(LocalConnectorCapability x){return new ConnectorCapabilityResponse(x.getId(),x.getDevice().getId(),x.getDevice().getBossAccount().getId(),x.getDevice().getBossAccount().getDisplayName(),x.getDevice().getBossAccount().getCompany().getName(),x.getCapability(),x.getStatus(),x.getReason(),x.getVerifiedAt(),x.getUpdatedAt());}}
record ConnectorActionTaskResponse(UUID id,UUID accountId,String accountName,String companyName,UUID observationId,String anonymousKey,String actionType,String status,String reason,String requestedBy,Instant createdAt,Instant updatedAt){static ConnectorActionTaskResponse from(LocalConnectorActionTask x){BrowserUnreadObservation o=x.getObservation();return new ConnectorActionTaskResponse(x.getId(),x.getAccount().getId(),x.getAccount().getDisplayName(),x.getAccount().getCompany().getName(),o==null?null:o.getId(),o==null?null:o.getChatDigest().substring(0,12),x.getActionType(),x.getStatus(),x.getReason(),x.getRequestedBy().getDisplayName(),x.getCreatedAt(),x.getUpdatedAt());}}
