package ai.xzkj.recruitment.localconnector;
// Persistence ports used only by the local connector runtime.
import org.springframework.data.jpa.repository.*;import java.util.*;
interface BrowserDeviceRepository extends JpaRepository<BrowserDevice,UUID>{@EntityGraph(attributePaths={"bossAccount","bossAccount.company"})Optional<BrowserDevice> findByTokenHashAndStatus(String hash,String status);@EntityGraph(attributePaths={"bossAccount","bossAccount.company"})List<BrowserDevice> findAllByOrderByCreatedAtDesc();Optional<BrowserDevice> findFirstByBossAccountIdAndStatus(UUID id,String status);}
interface BrowserPairingCodeRepository extends JpaRepository<BrowserPairingCode,UUID>{@EntityGraph(attributePaths={"account","account.company","createdBy"})Optional<BrowserPairingCode> findByTokenHash(String hash);}
interface BrowserUnreadObservationRepository extends JpaRepository<BrowserUnreadObservation,UUID>{@EntityGraph(attributePaths={"account","account.company"})List<BrowserUnreadObservation> findAllByUnreadTrueOrderByFirstSeenAtAsc();@EntityGraph(attributePaths={"account","account.company"})List<BrowserUnreadObservation> findTop100ByOrderByLastSeenAtDesc();@EntityGraph(attributePaths={"account","account.company"})Optional<BrowserUnreadObservation> findWithAccountById(UUID id);Optional<BrowserUnreadObservation> findByAccountIdAndChatDigest(UUID accountId,String chatDigest);}
interface LocalConnectorCapabilityRepository extends JpaRepository<LocalConnectorCapability,UUID>{@EntityGraph(attributePaths={"device","device.bossAccount","device.bossAccount.company"})List<LocalConnectorCapability> findAllByOrderByUpdatedAtDesc();Optional<LocalConnectorCapability> findByDeviceIdAndCapability(UUID deviceId,String capability);}
interface LocalConnectorActionTaskRepository extends JpaRepository<LocalConnectorActionTask,UUID>{@EntityGraph(attributePaths={"account","account.company","observation","requestedBy"})List<LocalConnectorActionTask> findTop100ByOrderByCreatedAtDesc();@Lock(jakarta.persistence.LockModeType.PESSIMISTIC_WRITE)@EntityGraph(attributePaths={"account","observation"})Optional<LocalConnectorActionTask> findFirstByAccountIdAndStatusOrderByCreatedAtAsc(UUID accountId,String status);}
interface LocalConnectorActionLeaseRepository extends JpaRepository<LocalConnectorActionLease,UUID>{@EntityGraph(attributePaths={"task","task.account","task.account.company","task.observation","device","device.bossAccount"})Optional<LocalConnectorActionLease> findByLeaseTokenHash(String tokenHash);@EntityGraph(attributePaths={"task","task.account","device","device.bossAccount"})List<LocalConnectorActionLease> findByStatusAndLeaseUntilBefore(String status,java.time.Instant cutoff);@EntityGraph(attributePaths={"task","task.account","task.account.company","task.observation","device","device.bossAccount"})List<LocalConnectorActionLease> findTop100ByOrderByLeasedAtDesc();@Query("select count(l) from LocalConnectorActionLease l where l.device.id=:deviceId and l.task.actionType=:action and l.leasedAt>=:since")long countRecent(UUID deviceId,String action,java.time.Instant since);}
interface LocalConnectorValidationCaseRepository extends JpaRepository<LocalConnectorValidationCase,UUID>{@EntityGraph(attributePaths={"device","device.bossAccount","device.bossAccount.company"})List<LocalConnectorValidationCase> findAllByOrderByPreparedAtDesc();@EntityGraph(attributePaths={"device","device.bossAccount","device.bossAccount.company"})Optional<LocalConnectorValidationCase> findWithDeviceById(UUID id);@EntityGraph(attributePaths={"device","device.bossAccount","device.bossAccount.company"})List<LocalConnectorValidationCase> findByStatusAndTestExpiresAtBefore(String status,java.time.Instant cutoff);Optional<LocalConnectorValidationCase> findByDeviceIdAndActionType(UUID deviceId,String actionType);}
interface LocalConnectorProductionApprovalRepository extends JpaRepository<LocalConnectorProductionApproval,UUID>{@EntityGraph(attributePaths={"device","device.bossAccount","device.bossAccount.company","requestedBy","approvedBy"})List<LocalConnectorProductionApproval> findAllByOrderByRequestedAtDesc();@EntityGraph(attributePaths={"device","device.bossAccount","device.bossAccount.company","requestedBy","approvedBy"})Optional<LocalConnectorProductionApproval> findWithDetailsById(UUID id);@Lock(jakarta.persistence.LockModeType.PESSIMISTIC_WRITE)Optional<LocalConnectorProductionApproval> findByDeviceIdAndActionType(UUID deviceId,String actionType);@EntityGraph(attributePaths={"device","device.bossAccount"})List<LocalConnectorProductionApproval> findByStatusAndExpiresAtBefore(String status,java.time.Instant cutoff);@EntityGraph(attributePaths={"device","device.bossAccount"})List<LocalConnectorProductionApproval> findByDeviceIdAndStatus(UUID deviceId,String status);}
