package ai.xzkj.recruitment.localconnector;

import ai.xzkj.recruitment.audit.AuditService;
import ai.xzkj.recruitment.auth.*;
import ai.xzkj.recruitment.common.ApiException;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.time.Instant;
import java.util.*;

@Service
class LocalConnectorProductionApprovalService {
    private final LocalConnectorProductionApprovalRepository approvals;private final LocalConnectorValidationCaseRepository validations;private final LocalConnectorCapabilityRepository capabilities;private final BrowserDeviceRepository devices;private final CurrentUserService users;private final AuditService audit;
    LocalConnectorProductionApprovalService(LocalConnectorProductionApprovalRepository approvals,LocalConnectorValidationCaseRepository validations,LocalConnectorCapabilityRepository capabilities,BrowserDeviceRepository devices,CurrentUserService users,AuditService audit){this.approvals=approvals;this.validations=validations;this.capabilities=capabilities;this.devices=devices;this.users=users;this.audit=audit;}
    @Transactional(readOnly=true)List<ProductionApprovalResponse> list(){SystemUser user=users.requireCurrentUser();return approvals.findAllByOrderByRequestedAtDesc().stream().filter(x->canAccess(x.getDevice(),user)).map(ProductionApprovalResponse::from).toList();}
    @Transactional ProductionApprovalResponse request(ProductionApprovalRequest request){SystemUser user=requireManager();if(request.hourlyLimit()>request.dailyLimit())throw bad("APPROVAL_LIMIT_INVALID","小时额度不能高于每日额度");LocalConnectorValidationCase validation=validations.findWithDeviceById(request.validationCaseId()).orElseThrow(()->bad("VALIDATION_CASE_NOT_FOUND","人工验收项目不存在"));requireAccess(validation.getDevice(),user);if(!"PASSED".equals(validation.getStatus()))throw new ApiException(HttpStatus.CONFLICT,"VALIDATION_NOT_PASSED","必须先完成真实页面单次人工验收");Instant now=Instant.now();LocalConnectorProductionApproval approval=approvals.findByDeviceIdAndActionType(validation.getDevice().getId(),validation.getActionType()).orElse(null);if(approval==null)approval=approvals.save(new LocalConnectorProductionApproval(validation.getDevice(),validation.getActionType(),request.hourlyLimit(),request.dailyLimit(),user,clean(request.reason()),now));else try{approval.renew(request.hourlyLimit(),request.dailyLimit(),user,clean(request.reason()),now);}catch(IllegalStateException e){throw new ApiException(HttpStatus.CONFLICT,"APPROVAL_STILL_ACTIVE",e.getMessage());}audit.success("REQUEST_CONNECTOR_PRODUCTION_APPROVAL","CONNECTOR_PRODUCTION_APPROVAL",approval.getId(),validation.getDevice().getBossAccount().getDisplayName(),validation.getActionType()+" 等待第二位管理员批准；小时额度 "+request.hourlyLimit()+"，每日额度 "+request.dailyLimit());return ProductionApprovalResponse.from(approval);}
    @Transactional ProductionApprovalResponse approve(UUID id,ProductionApprovalDecision decision){SystemUser user=requireManager();LocalConnectorProductionApproval approval=require(id,user);try{approval.approve(user,decision.durationHours(),Instant.now());LocalConnectorCapability capability=capabilities.findByDeviceIdAndCapability(approval.getDevice().getId(),approval.getActionType()).orElseThrow(()->bad("CAPABILITY_NOT_FOUND","页面能力不存在"));capability.approveProduction(Instant.now());}catch(IllegalStateException e){throw new ApiException(HttpStatus.CONFLICT,"APPROVAL_REJECTED",e.getMessage());}audit.success("APPROVE_CONNECTOR_LOW_QUOTA_TRIAL","CONNECTOR_PRODUCTION_APPROVAL",id,approval.getDevice().getBossAccount().getDisplayName(),approval.getActionType()+" 已双人批准，最长 "+decision.durationHours()+" 小时；仍无页面执行器");return ProductionApprovalResponse.from(approval);}
    @Transactional ProductionApprovalResponse revoke(UUID id){SystemUser user=requireManager();LocalConnectorProductionApproval approval=require(id,user);approval.revoke(user,"管理员已撤销低配额批准",Instant.now());capabilities.findByDeviceIdAndCapability(approval.getDevice().getId(),approval.getActionType()).ifPresent(x->x.revokeProduction("低配额生产批准已撤销",Instant.now()));audit.success("REVOKE_CONNECTOR_PRODUCTION_APPROVAL","CONNECTOR_PRODUCTION_APPROVAL",id,approval.getDevice().getBossAccount().getDisplayName(),approval.getActionType()+" 批准已撤销");return ProductionApprovalResponse.from(approval);}
    @Transactional void emergencyStop(UUID deviceId){SystemUser user=requireManager();BrowserDevice device=devices.findById(deviceId).orElseThrow(()->bad("DEVICE_NOT_FOUND","本地连接器设备不存在"));requireAccess(device,user);Instant now=Instant.now();for(LocalConnectorProductionApproval approval:approvals.findByDeviceIdAndStatus(deviceId,"APPROVED")){approval.revoke(user,"账号紧急停止，全部动作批准已撤销",now);capabilities.findByDeviceIdAndCapability(deviceId,approval.getActionType()).ifPresent(x->x.revokeProduction("账号紧急停止，页面写能力已锁定",now));}device.markOffline("管理员执行紧急停止，所有页面写操作已锁定");audit.success("EMERGENCY_STOP_CONNECTOR_ACTIONS","LOCAL_CONNECTOR_DEVICE",deviceId,device.getDisplayName(),"撤销当前账号全部生产批准并停止设备");}
    private LocalConnectorProductionApproval require(UUID id,SystemUser user){LocalConnectorProductionApproval x=approvals.findWithDetailsById(id).orElseThrow(()->bad("APPROVAL_NOT_FOUND","生产批准不存在"));requireAccess(x.getDevice(),user);return x;}private SystemUser requireManager(){SystemUser u=users.requireCurrentUser();if(u.getRole()==UserRole.RECRUITER)throw new ApiException(HttpStatus.FORBIDDEN,"MANAGER_REQUIRED","需要招聘管理员权限");return u;}private boolean canAccess(BrowserDevice d,SystemUser u){return u.getRole()==UserRole.SYSTEM_ADMIN||u.getCompanyScopes().stream().anyMatch(c->c.getId().equals(d.getBossAccount().getCompany().getId()));}private void requireAccess(BrowserDevice d,SystemUser u){if(!canAccess(d,u))throw new ApiException(HttpStatus.FORBIDDEN,"COMPANY_SCOPE_FORBIDDEN","无权访问该企业数据");}private ApiException bad(String code,String message){return new ApiException(HttpStatus.BAD_REQUEST,code,message);}private String clean(String s){String v=s.trim();return v.length()<=300?v:v.substring(0,300);}
}
