package ai.xzkj.recruitment.localconnector;
// Internal transport records for the local connector API.
import jakarta.validation.Valid;import jakarta.validation.constraints.*;import java.time.Instant;import java.util.*;
record CreatePairingRequest(@NotNull UUID accountId){}
record PairDeviceRequest(@NotBlank@Size(max=200)String pairingToken,@NotBlank@Size(max=100)String deviceName,@NotBlank@Pattern(regexp="BROWSER_READONLY_BRIDGE")String clientType,@NotBlank@Pattern(regexp="[0-9]+\\.[0-9]+\\.[0-9]+(?:[-+][A-Za-z0-9.-]+)?")@Size(max=32)String clientVersion){}
record HeartbeatRequest(@NotBlank@Pattern(regexp="DISABLED|RUNNING|PAUSED|OFFLINE")String state,@Size(max=300)String reason){}
record PairingResponse(String pairingToken,Instant expiresAt,UUID accountId,String accountName){}
record DeviceCredentialsResponse(UUID deviceId,String deviceToken,UUID accountId,String accountName){}
record DeviceResponse(UUID id,UUID accountId,String accountName,String displayName,String clientType,String clientVersion,String status,String runtimeState,String stopReason,Instant lastHeartbeatAt,Instant createdAt,Instant revokedAt){static DeviceResponse from(BrowserDevice d){return new DeviceResponse(d.getId(),d.getBossAccount().getId(),d.getBossAccount().getDisplayName(),d.getDisplayName(),d.getClientType(),d.getClientVersion(),d.getStatus(),d.getRuntimeState(),d.getStopReason(),d.getLastHeartbeatAt(),d.getCreatedAt(),d.getRevokedAt());}}
record UnreadObservationEntry(@NotBlank@Pattern(regexp="[a-f0-9]{64}")String chatDigest,@Pattern(regexp="[a-f0-9]{64}")String previewDigest,@Pattern(regexp="[a-f0-9]{64}")String jobDigest,@Size(max=120)String jobTitle,@Pattern(regexp="[a-f0-9]{64}")String timeDigest,@Min(0)@Max(999)int unreadCount,Instant firstSeenAt,Instant lastSeenAt){}
record UnreadObservationSnapshot(@NotNull@Size(max=200)List<@Valid UnreadObservationEntry> entries){}
record UnreadObservationSyncResponse(int activeUnread,int received,Instant serverNow){}
record SelectedConversationSnapshot(@NotBlank@Pattern(regexp="[a-f0-9]{64}")String chatDigest,@NotBlank@Pattern(regexp="[a-f0-9]{64}")String messageDigest,@NotBlank@Pattern(regexp="INBOUND|OUTBOUND")String direction,@NotNull Instant messageAt,boolean selectedUnread){}
record ObservationReviewRequest(@NotBlank@Pattern(regexp="APPROVED|REJECTED|HUMAN_TAKEOVER")String decision,@Size(max=2000)String content,@Size(max=300)String note){}
record UnreadObservationResponse(UUID id,UUID accountId,String accountName,String companyName,String anonymousKey,int unreadCount,boolean unread,boolean jobRecognized,boolean previewRecognized,String observedJobTitle,String draftMode,String draftContent,String draftReason,Instant draftGeneratedAt,String eligibilityStatus,String latestDirection,Instant latestMessageAt,Instant detailVerifiedAt,String reviewStatus,String reviewedContent,String reviewNote,Instant reviewedAt,String resolutionStatus,Instant resolvedAt,Instant firstSeenAt,Instant lastSeenAt){static UnreadObservationResponse from(BrowserUnreadObservation x){return new UnreadObservationResponse(x.getId(),x.getAccount().getId(),x.getAccount().getDisplayName(),x.getAccount().getCompany().getName(),x.getChatDigest().substring(0,12),x.getUnreadCount(),x.isUnread(),x.getJobDigest()!=null,x.getPreviewDigest()!=null,x.getObservedJobTitle(),x.getDraftMode(),x.getDraftContent(),x.getDraftReason(),x.getDraftGeneratedAt(),x.getEligibilityStatus(),x.getLatestDirection(),x.getLatestMessageAt(),x.getDetailVerifiedAt(),x.getReviewStatus(),x.getReviewedContent(),x.getReviewNote(),x.getReviewedAt(),x.getResolutionStatus(),x.getResolvedAt(),x.getFirstSeenAt(),x.getLastSeenAt());}}
record CreateActionTaskRequest(@NotNull UUID observationId,@NotBlank@Pattern(regexp="SEND_MESSAGE|REQUEST_RESUME|EXCHANGE_WECHAT|EXCHANGE_PHONE")String actionType){}
record ConnectorCapabilityResponse(UUID id,UUID deviceId,UUID accountId,String accountName,String companyName,String capability,String status,String reason,Instant verifiedAt,Instant updatedAt){static ConnectorCapabilityResponse from(LocalConnectorCapability x){return new ConnectorCapabilityResponse(x.getId(),x.getDevice().getId(),x.getDevice().getBossAccount().getId(),x.getDevice().getBossAccount().getDisplayName(),x.getDevice().getBossAccount().getCompany().getName(),x.getCapability(),x.getStatus(),x.getReason(),x.getVerifiedAt(),x.getUpdatedAt());}}
record ConnectorActionTaskResponse(UUID id,UUID accountId,String accountName,String companyName,UUID observationId,String anonymousKey,String actionType,String status,String reason,String requestedBy,Instant createdAt,Instant updatedAt){static ConnectorActionTaskResponse from(LocalConnectorActionTask x){BrowserUnreadObservation o=x.getObservation();return new ConnectorActionTaskResponse(x.getId(),x.getAccount().getId(),x.getAccount().getDisplayName(),x.getAccount().getCompany().getName(),o==null?null:o.getId(),o==null?null:o.getChatDigest().substring(0,12),x.getActionType(),x.getStatus(),x.getReason(),x.getRequestedBy().getDisplayName(),x.getCreatedAt(),x.getUpdatedAt());}}
record ActionLeaseClaimResponse(boolean available,UUID leaseId,UUID taskId,String actionType,String targetDigest,String leaseToken,Instant leaseUntil,String mode){static ActionLeaseClaimResponse none(){return new ActionLeaseClaimResponse(false,null,null,null,null,null,null,"NO_APPROVED_TASK");}}
record ActionLeaseReceiptRequest(@NotBlank@Size(max=200)String leaseToken,@NotBlank@Pattern(regexp="SUCCEEDED|FAILED|UNKNOWN")String outcome,@NotBlank@Pattern(regexp="[a-f0-9]{64}")String receiptDigest,@NotBlank@Size(max=300)String reason){}
record ActionLeaseResponse(UUID id,UUID taskId,UUID accountId,String accountName,String actionType,String status,String targetDigest,Instant leasedAt,Instant leaseUntil,String resultReason,Instant completedAt,Instant updatedAt){static ActionLeaseResponse from(LocalConnectorActionLease x){BrowserUnreadObservation o=x.getTask().getObservation();return new ActionLeaseResponse(x.getId(),x.getTask().getId(),x.getTask().getAccount().getId(),x.getTask().getAccount().getDisplayName(),x.getTask().getActionType(),x.getStatus(),o==null?null:o.getChatDigest().substring(0,12),x.getLeasedAt(),x.getLeaseUntil(),x.getResultReason(),x.getCompletedAt(),x.getUpdatedAt());}}
record ProductionApprovalRequest(@NotNull UUID validationCaseId,@Min(1)@Max(5)int hourlyLimit,@Min(1)@Max(20)int dailyLimit,@NotBlank@Size(max=300)String reason){}
record ProductionApprovalDecision(@Min(1)@Max(168)int durationHours){}
record ProductionApprovalResponse(UUID id,UUID deviceId,UUID accountId,String accountName,String companyName,String actionType,String status,int hourlyLimit,int dailyLimit,String requestedBy,Instant requestedAt,String approvedBy,Instant approvedAt,Instant expiresAt,String reason,Instant updatedAt){static ProductionApprovalResponse from(LocalConnectorProductionApproval x){return new ProductionApprovalResponse(x.getId(),x.getDevice().getId(),x.getDevice().getBossAccount().getId(),x.getDevice().getBossAccount().getDisplayName(),x.getDevice().getBossAccount().getCompany().getName(),x.getActionType(),x.getStatus(),x.getHourlyLimit(),x.getDailyLimit(),x.getRequestedBy().getDisplayName(),x.getRequestedAt(),x.getApprovedBy()==null?null:x.getApprovedBy().getDisplayName(),x.getApprovedAt(),x.getExpiresAt(),x.getReason(),x.getUpdatedAt());}}
record OfflineDrillReport(@NotBlank@Pattern(regexp="SEND_MESSAGE|REQUEST_RESUME|EXCHANGE_WECHAT|EXCHANGE_PHONE")String actionType,@NotBlank@Pattern(regexp="PASSED|FAILED")String outcome,@NotBlank@Pattern(regexp="FIXTURE_ONLY")String evidenceSource,@NotBlank@Pattern(regexp="[a-f0-9]{64}")String beforeDigest,@NotBlank@Pattern(regexp="[a-f0-9]{64}")String afterDigest,@NotBlank@Pattern(regexp="[a-f0-9]{64}")String receiptDigest,@Size(max=300)String failureReason){}
record OfflineDrillResponse(UUID id,UUID deviceId,UUID accountId,String accountName,String actionType,String outcome,String evidenceSource,String beforeDigest,String afterDigest,String receiptDigest,String failureReason,Instant createdAt){static OfflineDrillResponse from(LocalConnectorOfflineDrill x){return new OfflineDrillResponse(x.getId(),x.getDevice().getId(),x.getDevice().getBossAccount().getId(),x.getDevice().getBossAccount().getDisplayName(),x.getActionType(),x.getOutcome(),x.getEvidenceSource(),x.getBeforeDigest().substring(0,12),x.getAfterDigest().substring(0,12),x.getReceiptDigest().substring(0,12),x.getFailureReason(),x.getCreatedAt());}}
record ValidationReadinessRequest(@NotBlank@Pattern(regexp="SEND_MESSAGE|REQUEST_RESUME|EXCHANGE_WECHAT|EXCHANGE_PHONE")String actionType,@NotBlank@Pattern(regexp="[a-f0-9]{64}")String chatDigest,@NotBlank@Pattern(regexp="[a-f0-9]{64}")String controlDigest,@NotBlank@Pattern(regexp="CHAT_PAGE_READY")String pageState,boolean selectedConversationVerified,boolean hasRiskOrVerification,@Min(3)@Max(20)int stableCycles){}
record ValidationResultRequest(@NotBlank@Pattern(regexp="PASSED|FAILED")String result,@NotBlank@Size(max=500)String note){}
record ConnectorValidationCaseResponse(UUID id,UUID deviceId,UUID accountId,String accountName,String companyName,String actionType,String status,List<String> prerequisites,String expectedResult,String lastFailureReason,Instant evidenceObservedAt,Instant testStartedAt,Instant testExpiresAt,Instant completedAt,String resultNote,Instant preparedAt,Instant updatedAt){static ConnectorValidationCaseResponse from(LocalConnectorValidationCase x){return new ConnectorValidationCaseResponse(x.getId(),x.getDevice().getId(),x.getDevice().getBossAccount().getId(),x.getDevice().getBossAccount().getDisplayName(),x.getDevice().getBossAccount().getCompany().getName(),x.getActionType(),x.getStatus(),Arrays.stream(x.getPrerequisites().split("\\n")).filter(v->!v.isBlank()).toList(),x.getExpectedResult(),x.getLastFailureReason(),x.getEvidenceObservedAt(),x.getTestStartedAt(),x.getTestExpiresAt(),x.getCompletedAt(),x.getResultNote(),x.getPreparedAt(),x.getUpdatedAt());}}
