package ai.xzkj.recruitment.localconnector;

import ai.xzkj.recruitment.audit.AuditService;
import ai.xzkj.recruitment.auth.*;
import ai.xzkj.recruitment.autoreply.*;
import ai.xzkj.recruitment.boss.*;
import ai.xzkj.recruitment.common.ApiException;
import ai.xzkj.recruitment.jobs.*;
import ai.xzkj.recruitment.organization.Company;
import org.springframework.http.HttpStatus;
import org.springframework.boot.context.event.ApplicationReadyEvent;
import org.springframework.context.event.EventListener;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.nio.charset.StandardCharsets;
import java.security.*;
import java.time.*;
import java.util.*;

@Service public class LocalConnectorService {
 private static final List<String> CAPABILITY_NAMES=List.of("CHAT_LIST_READ","CONVERSATION_DETAIL_READ","JOB_LIST_READ","SEND_MESSAGE","REQUEST_RESUME","EXCHANGE_WECHAT","EXCHANGE_PHONE");
 private final BrowserDeviceRepository devices;private final BrowserPairingCodeRepository pairings;private final BrowserUnreadObservationRepository observations;private final LocalConnectorCapabilityRepository capabilities;private final LocalConnectorActionTaskRepository actionTasks;private final AutoReplyPolicyRepository policies;private final BossAccountRepository accounts;private final JobPositionRepository jobs;private final CurrentUserService users;private final AuditService audit;private final SecureRandom random=new SecureRandom();
 public LocalConnectorService(BrowserDeviceRepository devices,BrowserPairingCodeRepository pairings,BrowserUnreadObservationRepository observations,LocalConnectorCapabilityRepository capabilities,LocalConnectorActionTaskRepository actionTasks,AutoReplyPolicyRepository policies,BossAccountRepository accounts,JobPositionRepository jobs,CurrentUserService users,AuditService audit){this.devices=devices;this.pairings=pairings;this.observations=observations;this.capabilities=capabilities;this.actionTasks=actionTasks;this.policies=policies;this.accounts=accounts;this.jobs=jobs;this.users=users;this.audit=audit;}

 @Transactional public PairingResponse createPairing(UUID accountId){SystemUser user=requireManager();BossAccount account=requireConnectorAccount(accountId,user);String token=token();BrowserPairingCode code=pairings.save(new BrowserPairingCode(account,hash(token),user));audit.success("CREATE_LOCAL_CONNECTOR_PAIRING","BOSS_ACCOUNT",accountId,account.getDisplayName(),"创建 10 分钟有效的本地连接器令牌，令牌正文不入库");return new PairingResponse(token,code.getExpiresAt(),accountId,account.getDisplayName());}
 @Transactional public DeviceCredentialsResponse pair(PairDeviceRequest request){BrowserPairingCode code=pairings.findByTokenHash(hash(request.pairingToken().trim())).orElseThrow(()->bad("PAIRING_TOKEN_INVALID","配对令牌无效"));if(!code.usable(Instant.now()))throw bad("PAIRING_TOKEN_EXPIRED","配对令牌已使用或过期");if(code.getAccount().getGatewayType()!=BossGatewayType.LOCAL_CDP_CONNECTOR||code.getAccount().getStatus()!=BossAccountStatus.ACTIVE)throw bad("PAIRING_ACCOUNT_INVALID","连接令牌不属于已启用的本地 CDP 招聘账号");devices.findFirstByBossAccountIdAndStatus(code.getAccount().getId(),"ACTIVE").ifPresent(d->{d.revoke();devices.flush();});String raw=token();BrowserDevice device=devices.save(new BrowserDevice(code.getAccount(),clean(request.deviceName(),100),hash(raw),code.getCreatedBy()));ensureCapabilities(device);code.use();code.getAccount().applyCapabilityCheck(BossConnectionStatus.CONNECTED,Set.of(BossCapability.JOB_SYNC,BossCapability.CANDIDATE_READ));audit.systemSuccess("PAIR_LOCAL_CONNECTOR","BOSS_ACCOUNT",code.getAccount().getId(),code.getAccount().getDisplayName(),"本地 CDP 连接器已配对，设备令牌正文不入库");return new DeviceCredentialsResponse(device.getId(),raw,code.getAccount().getId(),code.getAccount().getDisplayName());}
 @Transactional(readOnly=true) public List<DeviceResponse> list(){SystemUser user=users.requireCurrentUser();return devices.findAllByOrderByCreatedAtDesc().stream().filter(d->canAccess(d.getBossAccount().getCompany().getId(),user)).map(DeviceResponse::from).toList();}
 @Transactional public void revoke(UUID id){SystemUser user=requireManager();BrowserDevice device=devices.findById(id).orElseThrow(()->bad("DEVICE_NOT_FOUND","本地连接器设备不存在"));requireAccess(device.getBossAccount().getCompany().getId(),user);device.revoke();audit.success("REVOKE_LOCAL_CONNECTOR_DEVICE","LOCAL_CONNECTOR_DEVICE",id,device.getDisplayName(),"撤销本地连接器设备令牌");}
 @Transactional public DeviceResponse heartbeat(String authorization,HeartbeatRequest request){BrowserDevice device=authenticate(authorization);device.heartbeat(request.state(),cleanOptional(request.reason(),300));return DeviceResponse.from(device);}
 @Transactional public UnreadObservationSyncResponse observeUnread(String authorization,UnreadObservationSnapshot snapshot){BrowserDevice device=authenticate(authorization);Instant now=Instant.now();AutoReplyPolicy policy=policies.findByBossAccountId(device.getBossAccount().getId()).orElse(null);Set<String> observedJobKeys=new HashSet<>();for(UnreadObservationEntry entry:snapshot.entries()){Instant first=validObservationTime(entry.firstSeenAt(),now);BrowserUnreadObservation observation=observations.findByAccountIdAndChatDigest(device.getBossAccount().getId(),entry.chatDigest()).orElseGet(()->new BrowserUnreadObservation(device,entry.chatDigest(),first,now));observation.observe(entry,now);importObservedJob(device.getBossAccount(),entry.jobTitle(),observedJobKeys);prepareDraft(observation,device.getBossAccount().getId(),now);evaluate(observation,policy,now);observations.save(observation);}verifyReadCapability(device,"CHAT_LIST_READ",snapshot.entries().isEmpty()?hash("empty-chat-list"):snapshot.entries().getFirst().chatDigest(),"真实沟通页会话列表已稳定只读识别",now);if(snapshot.entries().stream().anyMatch(x->x.jobTitle()!=null&&!x.jobTitle().isBlank()))verifyReadCapability(device,"JOB_LIST_READ",hash("observed-job-title"),"已从真实未读会话识别岗位标题",now);int active=(int)observations.findAllByUnreadTrueOrderByFirstSeenAtAsc().stream().filter(x->x.getAccount().getId().equals(device.getBossAccount().getId())).count();return new UnreadObservationSyncResponse(active,snapshot.entries().size(),now);}
 @Transactional public UnreadObservationResponse verifySelectedConversation(String authorization,SelectedConversationSnapshot snapshot){BrowserDevice device=authenticate(authorization);Instant now=Instant.now();if(snapshot.messageAt().isAfter(now.plusSeconds(300))||snapshot.messageAt().isBefore(now.minus(Duration.ofDays(30))))throw bad("MESSAGE_TIME_INVALID","最新消息时间无效");BrowserUnreadObservation observation=observations.findByAccountIdAndChatDigest(device.getBossAccount().getId(),snapshot.chatDigest()).orElseThrow(()->bad("OBSERVATION_NOT_FOUND","选中会话不在当前未读观察队列"));String previous=observation.getResolutionStatus();observation.verifyDetail(snapshot.messageDigest(),snapshot.direction(),snapshot.messageAt(),snapshot.selectedUnread(),now);verifyReadCapability(device,"CONVERSATION_DETAIL_READ",snapshot.messageDigest(),"真实选中会话的最新消息方向与时间已只读复核",now);evaluate(observation,policies.findByBossAccountId(device.getBossAccount().getId()).orElse(null),now);if("UNRESOLVED".equals(previous)&&!"UNRESOLVED".equals(observation.getResolutionStatus()))audit.systemSuccess("CONFIRM_HR_CONNECTOR_REPLY","UNREAD_OBSERVATION",observation.getId(),device.getBossAccount().getDisplayName(),"页面已识别 HR 最新外发，未读任务已闭环，不记录消息正文");return UnreadObservationResponse.from(observation);}
 @Transactional(readOnly=true) public List<UnreadObservationResponse> listUnreadObservations(){SystemUser user=users.requireCurrentUser();return observations.findTop100ByOrderByLastSeenAtDesc().stream().filter(x->canAccess(x.getAccount().getCompany().getId(),user)).map(UnreadObservationResponse::from).toList();}
 @Transactional public UnreadObservationResponse reviewObservation(UUID id,ObservationReviewRequest request){SystemUser user=users.requireCurrentUser();BrowserUnreadObservation observation=observations.findWithAccountById(id).orElseThrow(()->bad("OBSERVATION_NOT_FOUND","未读观察不存在"));requireAccess(observation.getAccount().getCompany().getId(),user);if(!"READY_FOR_REVIEW".equals(observation.getEligibilityStatus())&&!"APPROVED_DRAFT".equals(observation.getEligibilityStatus()))throw new ApiException(HttpStatus.CONFLICT,"OBSERVATION_NOT_REVIEWABLE","当前会话尚未通过超时和最新消息复核");String content=cleanOptional(request.content(),2000);if("APPROVED".equals(request.decision())&&content==null)throw bad("REVIEW_CONTENT_REQUIRED","批准草稿前必须确认回复内容");observation.review(request.decision(),content,cleanOptional(request.note(),300),user,Instant.now());audit.success("REVIEW_CONNECTOR_DRAFT","UNREAD_OBSERVATION",id,observation.getAccount().getDisplayName(),"安全草稿人工处理："+request.decision());return UnreadObservationResponse.from(observation);}
 @Transactional(readOnly=true) public List<ConnectorCapabilityResponse> listCapabilities(){SystemUser user=users.requireCurrentUser();return capabilities.findAllByOrderByUpdatedAtDesc().stream().filter(x->canAccess(x.getDevice().getBossAccount().getCompany().getId(),user)).map(ConnectorCapabilityResponse::from).toList();}
 @Transactional(readOnly=true) public List<ConnectorActionTaskResponse> listActionTasks(){SystemUser user=users.requireCurrentUser();return actionTasks.findTop100ByOrderByCreatedAtDesc().stream().filter(x->canAccess(x.getAccount().getCompany().getId(),user)).map(ConnectorActionTaskResponse::from).toList();}
 @Transactional public ConnectorActionTaskResponse createActionTask(CreateActionTaskRequest request){SystemUser user=users.requireCurrentUser();BrowserUnreadObservation observation=observations.findWithAccountById(request.observationId()).orElseThrow(()->bad("OBSERVATION_NOT_FOUND","未读观察不存在"));requireAccess(observation.getAccount().getCompany().getId(),user);BrowserDevice device=devices.findFirstByBossAccountIdAndStatus(observation.getAccount().getId(),"ACTIVE").orElse(null);LocalConnectorCapability capability=device==null?null:capabilities.findByDeviceIdAndCapability(device.getId(),request.actionType()).orElse(null);String status=capability!=null&&"READY_FOR_MANUAL_TEST".equals(capability.getStatus())?"WAITING_MANUAL_TEST":"BLOCKED_UNVERIFIED";String reason="BLOCKED_UNVERIFIED".equals(status)?"真实页面写操作尚未验证，任务仅登记且不会下发到浏览器":"等待 HR 在真实页面执行单次人工测试，连接器不会自动点击";LocalConnectorActionTask task=actionTasks.save(new LocalConnectorActionTask(observation.getAccount(),observation,request.actionType(),status,user,reason));audit.success("CREATE_CONNECTOR_ACTION_TASK","LOCAL_CONNECTOR_ACTION",task.getId(),observation.getAccount().getDisplayName(),request.actionType()+" · "+reason);return ConnectorActionTaskResponse.from(task);}
 @EventListener(ApplicationReadyEvent.class) @Transactional public void backfillObservedJobs(){Map<UUID,Set<String>> keysByAccount=new HashMap<>();for(BrowserDevice device:devices.findAllByOrderByCreatedAtDesc())ensureCapabilities(device);for(BrowserUnreadObservation observation:observations.findTop100ByOrderByLastSeenAtDesc()){BossAccount account=observation.getAccount();BrowserDevice device=observation.getDevice();Instant evidenceTime=observation.getLastSeenAt();verifyReadCapability(device,"CHAT_LIST_READ",observation.getChatDigest(),"已有真实沟通页会话列表观测已回填",evidenceTime);if(observation.getObservedJobTitle()!=null)verifyReadCapability(device,"JOB_LIST_READ",observation.getJobDigest()==null?hash(observation.getObservedJobTitle()):observation.getJobDigest(),"已有真实岗位标题观测已回填",evidenceTime);if(observation.getDetailVerifiedAt()!=null)verifyReadCapability(device,"CONVERSATION_DETAIL_READ",observation.getChatDigest(),"已有真实选中会话详情观测已回填",observation.getDetailVerifiedAt());importObservedJob(account,observation.getObservedJobTitle(),keysByAccount.computeIfAbsent(account.getId(),ignored->new HashSet<>()));}}
 @Transactional(readOnly=true) public BrowserDevice authenticate(String header){if(header==null||!header.startsWith("Device "))throw unauthorized();String raw=header.substring(7).trim();if(raw.length()<20)throw unauthorized();BrowserDevice device=devices.findByTokenHashAndStatus(hash(raw),"ACTIVE").orElseThrow(this::unauthorized);if(device.getBossAccount().getGatewayType()!=BossGatewayType.LOCAL_CDP_CONNECTOR||device.getBossAccount().getStatus()!=BossAccountStatus.ACTIVE)throw unauthorized();return device;}

 private BossAccount requireConnectorAccount(UUID id,SystemUser user){BossAccount account=accounts.findWithDetailsById(id).orElseThrow(()->bad("BOSS_ACCOUNT_NOT_FOUND","BOSS 账号不存在"));requireAccess(account.getCompany().getId(),user);if(account.getGatewayType()!=BossGatewayType.LOCAL_CDP_CONNECTOR)throw bad("LOCAL_CONNECTOR_ACCOUNT_REQUIRED","只有本地 CDP 招聘账号可以连接本机 Chrome");if(account.getStatus()!=BossAccountStatus.ACTIVE)throw bad("BOSS_ACCOUNT_INACTIVE","请先启用招聘账号再连接本机 Chrome");return account;}
 private SystemUser requireManager(){SystemUser user=users.requireCurrentUser();if(user.getRole()==UserRole.RECRUITER)throw new ApiException(HttpStatus.FORBIDDEN,"FORBIDDEN","当前账号没有本地连接器管理权限");return user;}
 private void prepareDraft(BrowserUnreadObservation observation,UUID accountId,Instant now){String title=cleanOptional(observation.getObservedJobTitle(),120);JobPosition job=title==null?null:SafeReplyComposer.matchActiveJob(title,jobs.findAllByBossAccountIdAndStatus(accountId,JobPositionStatus.ACTIVE)).orElse(null);if(job==null){observation.prepareDraft("GENERIC",SafeReplyComposer.GENERIC_REPLY,title==null?"网页未识别到岗位名称":"同账号下未找到唯一匹配的启用岗位，已禁止猜测",now);return;}SafeReplyComposer.Composition result=SafeReplyComposer.compose(job);observation.prepareDraft(result.mode(),result.content(),result.reason(),now);}
 private void importObservedJob(BossAccount account,String rawTitle,Set<String> snapshotKeys){String title=cleanOptional(rawTitle,120);if(title==null||title.length()<2)return;String normalized=SafeReplyComposer.normalizePublicTitle(title);if(normalized.isBlank()||!snapshotKeys.add(normalized))return;String sourceKey=hash(account.getId()+"|"+normalized);JobPosition existing=jobs.findByBossAccountIdAndObservedSourceKey(account.getId(),sourceKey).orElse(null);if(existing==null){List<JobPosition> accountJobs=jobs.findAllByBossAccountId(account.getId());existing=accountJobs.stream().filter(job->SafeReplyComposer.normalizePublicTitle(job.getTitle()).equals(normalized)).findFirst().orElse(null);}if(existing!=null){existing.markUnreadObservation(sourceKey,false);return;}JobPosition imported=new JobPosition(account.getCompany(),account,title,"待从 BOSS 岗位页补全",1,1,12,"待从 BOSS 岗位页补全","待从 BOSS 岗位页补全","由真实未读会话识别岗位标题，其他岗位资料待 HR 核对补全。",null);imported.markUnreadObservation(sourceKey,true);jobs.save(imported);audit.systemSuccess("IMPORT_OBSERVED_JOB_TITLE","JOB_POSITION",imported.getId(),title,"从真实未读观察创建岗位草稿；已按企业、账号和规范化标题去重");}
 private void evaluate(BrowserUnreadObservation observation,AutoReplyPolicy policy,Instant now){observation.evaluate(now,policy==null?120:policy.getResponseTimeoutMinutes(),policy!=null&&policy.isAwayActive(now));}
 private void ensureCapabilities(BrowserDevice device){for(String name:CAPABILITY_NAMES)if(capabilities.findByDeviceIdAndCapability(device.getId(),name).isEmpty())capabilities.save(new LocalConnectorCapability(device,name));}
 private void verifyReadCapability(BrowserDevice device,String name,String digest,String reason,Instant now){LocalConnectorCapability capability=capabilities.findByDeviceIdAndCapability(device.getId(),name).orElseGet(()->capabilities.save(new LocalConnectorCapability(device,name)));capability.verifyReadOnly(digest,reason,now);}
 private boolean canAccess(UUID companyId,SystemUser user){return user.getRole()==UserRole.SYSTEM_ADMIN||user.getCompanyScopes().stream().map(Company::getId).anyMatch(companyId::equals);}private void requireAccess(UUID id,SystemUser user){if(!canAccess(id,user))throw new ApiException(HttpStatus.FORBIDDEN,"COMPANY_SCOPE_FORBIDDEN","当前账号无权访问该企业数据");}
 private String token(){byte[] bytes=new byte[32];random.nextBytes(bytes);return Base64.getUrlEncoder().withoutPadding().encodeToString(bytes);}private String hash(String value){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(value.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}private String clean(String value,int max){String v=value.trim();return v.length()<=max?v:v.substring(0,max);}private String cleanOptional(String value,int max){return value==null||value.isBlank()?null:clean(value,max);}private Instant validObservationTime(Instant value,Instant now){return value==null||value.isAfter(now.plusSeconds(300))||value.isBefore(now.minus(Duration.ofDays(7)))?now:value;}private ApiException bad(String code,String message){return new ApiException(HttpStatus.BAD_REQUEST,code,message);}private ApiException unauthorized(){return new ApiException(HttpStatus.UNAUTHORIZED,"DEVICE_UNAUTHORIZED","本地连接器令牌无效或已撤销");}
}
