package ai.xzkj.recruitment.localconnector;
// Internal transport records for the local connector API.
import jakarta.validation.Valid;import jakarta.validation.constraints.*;import java.time.Instant;import java.util.*;
record CreatePairingRequest(@NotNull UUID accountId){}
record PairDeviceRequest(@NotBlank@Size(max=200)String pairingToken,@NotBlank@Size(max=100)String deviceName,@NotBlank@Pattern(regexp="BROWSER_READONLY_BRIDGE")String clientType,@NotBlank@Pattern(regexp="[0-9]+\\.[0-9]+\\.[0-9]+(?:[-+][A-Za-z0-9.-]+)?")@Size(max=32)String clientVersion){}
record HeartbeatRequest(@NotBlank@Pattern(regexp="DISABLED|RUNNING|PAUSED|OFFLINE")String state,@Size(max=300)String reason,@NotBlank@Pattern(regexp="CHAT|JOB_LIST|JOB_DETAIL|OTHER_BOSS|NO_BOSS_PAGE")String pageContext){}
record PairingResponse(String pairingToken,Instant expiresAt,UUID accountId,String accountName){}
record DeviceCredentialsResponse(UUID deviceId,String deviceToken,UUID accountId,String accountName){}
record DutyAutomationControlResponse(boolean enabled,Instant endsAt,int responseTimeoutMinutes){}
record DeviceResponse(UUID id,UUID accountId,String accountName,String displayName,String clientType,String clientVersion,String status,String runtimeState,String stopReason,String pageContext,Instant lastHeartbeatAt,Instant lastSuccessfulSyncAt,String lastSuccessfulSyncType,Instant lastSuccessfulChatSyncAt,Instant lastSuccessfulJobSyncAt,Instant lastPauseAt,String lastPauseReason,Instant recoveryRequiredSince,Instant lastRecoveredAt,String recoveryStatus,Instant createdAt,Instant revokedAt){static DeviceResponse from(BrowserDevice d){String recoveryStatus=d.getRecoveryRequiredSince()!=null?"WAITING_RECOLLECTION":d.getLastSuccessfulChatSyncAt()==null?"NEVER_COLLECTED":d.getLastRecoveredAt()!=null?"RECOLLECTED":"HEALTHY";return new DeviceResponse(d.getId(),d.getBossAccount().getId(),d.getBossAccount().getDisplayName(),d.getDisplayName(),d.getClientType(),d.getClientVersion(),d.getStatus(),d.getRuntimeState(),d.getStopReason(),d.getPageContext(),d.getLastHeartbeatAt(),d.getLastSuccessfulSyncAt(),d.getLastSuccessfulSyncType(),d.getLastSuccessfulChatSyncAt(),d.getLastSuccessfulJobSyncAt(),d.getLastPauseAt(),d.getLastPauseReason(),d.getRecoveryRequiredSince(),d.getLastRecoveredAt(),recoveryStatus,d.getCreatedAt(),d.getRevokedAt());}}
record UnreadObservationEntry(@NotBlank@Pattern(regexp="[a-f0-9]{64}")String chatDigest,@Pattern(regexp="[a-f0-9]{64}")String previewDigest,@Pattern(regexp="[a-f0-9]{64}")String jobDigest,@Size(max=120)String jobTitle,@Pattern(regexp="[a-f0-9]{64}")String timeDigest,@Min(0)@Max(999)int unreadCount,Instant firstSeenAt,Instant lastSeenAt){}
record UnreadObservationSnapshot(@NotNull@Size(max=200)List<@Valid UnreadObservationEntry> entries){}
record UnreadObservationSyncResponse(int activeUnread,int received,Instant serverNow){}
record VisibleJobEntry(@NotBlank@Pattern(regexp="[a-f0-9]{64}")String sourceDigest,@NotBlank@Size(max=120)String title,@Size(max=120)String location,@Size(max=120)@Pattern(regexp="(?i).*\\d+(?:\\.\\d+)?\\s*[-–~至]\\s*\\d+(?:\\.\\d+)?\\s*k.*")String salaryDisplay,@Min(1)@Max(1000)Integer salaryMinK,@Min(1)@Max(1000)Integer salaryMaxK,@Min(12)@Max(16)Integer salaryMonths,@Size(max=80)@Pattern(regexp="经验不限|不限|应届生|在校生|\\d{1,2}(?:-\\d{1,2})?年(?:以上|以内)?")String experienceRequirement,@Size(max=80)@Pattern(regexp="(?:学历不限|不限|初中及以下|中专/中技|高中|大专|本科|硕士|博士)(?:及以上)?")String educationRequirement,@Size(max=10000)String description,@Size(max=40)String recruitmentType,@Size(max=120)String jobCategory,@Size(max=40)String overseasRequirement,@Size(max=500)String jobKeywords,@Size(max=240)String workAddress,@Min(1)@Max(12)int completeness,@Pattern(regexp="OPEN|CLOSED|UNKNOWN")String platformStatus){}
record VisibleJobSnapshot(@NotNull@Size(min=1,max=200)List<@Valid VisibleJobEntry> entries,@NotNull Instant observedAt,@Pattern(regexp="OPEN_JOBS|CLOSED_JOBS|MIXED|SINGLE_JOB")String scope,boolean authoritative){}
record VisibleJobSyncResponse(int received,int created,int updated,int unchanged,int automaticallyClosed,int reopenedForReview,Instant serverNow){}
record ConversationSignals(boolean requestResumeAvailable,boolean resumeReceived,boolean exchangeWechatAvailable,boolean exchangePhoneAvailable,boolean wechatExchanged,boolean phoneExchanged,boolean scheduleInterviewAvailable,boolean interviewScheduled){static ConversationSignals none(){return new ConversationSignals(false,false,false,false,false,false,false,false);}}
record SelectedConversationSnapshot(@NotBlank@Pattern(regexp="[a-f0-9]{64}")String chatDigest,@NotBlank@Pattern(regexp="[a-f0-9]{64}")String messageDigest,@NotBlank@Pattern(regexp="INBOUND|OUTBOUND")String direction,@NotNull Instant messageAt,boolean selectedUnread,@Valid ConversationSignals conversationSignals,@NotNull Instant observedAt){}
record InboundReplyDecisionRequest(@NotBlank@Pattern(regexp="[a-f0-9]{64}")String chatDigest,@NotBlank@Pattern(regexp="[a-f0-9]{64}")String messageDigest,@NotBlank@Size(max=1000)String messageText,@Size(max=2400)String conversationContext,@NotNull Instant observedAt){}
record InboundReplyDecisionResponse(boolean replyAllowed,@NotBlank String category,double confidence,String content,@NotBlank String reason){}
record InboundReplyTaskAcceptedResponse(UUID taskId,@NotBlank String status,InboundReplyDecisionResponse decision){}
record InboundReplyTaskStatusResponse(@NotNull UUID taskId,@NotBlank String status,InboundReplyDecisionResponse decision){}
record InboundReplyTaskDiscardRequest(@NotBlank@Pattern(regexp="[a-f0-9]{64}")String chatDigest,@NotBlank@Pattern(regexp="[a-f0-9]{64}")String messageDigest,@NotBlank@Pattern(regexp="[a-f0-9]{64}")String currentMessageDigest,@NotBlank@Size(max=300)String reason){}
record InboundReplyTaskDiscardResponse(@NotNull UUID taskId,@NotBlank String sendStatus,Instant discardedAt){}
record InboundReplySendClaimRequest(@NotNull UUID taskId,@NotBlank@Pattern(regexp="[a-f0-9]{64}")String chatDigest,@NotBlank@Pattern(regexp="[a-f0-9]{64}")String messageDigest,@NotBlank@Pattern(regexp="[a-f0-9]{64}")String beforeStateDigest){}
record InboundReplySendClaimResponse(boolean available,@NotNull UUID taskId,String leaseToken,String content,String replyDigest,Instant leaseUntil,@NotBlank String status,@NotBlank String reason){}
record InboundReplySendReceiptRequest(@NotBlank@Size(max=200)String leaseToken,@NotBlank@Pattern(regexp="SUCCEEDED|FAILED|UNKNOWN")String outcome,@NotBlank@Pattern(regexp="[a-f0-9]{64}")String beforeStateDigest,@NotBlank@Pattern(regexp="[a-f0-9]{64}")String afterStateDigest,@NotBlank@Pattern(regexp="[a-f0-9]{64}")String receiptDigest,@NotBlank@Size(max=300)String reason){}
record InboundReplySendReceiptResponse(@NotNull UUID taskId,@NotBlank String status,Instant completedAt){}
record AiDutyReplyResponse(@NotNull UUID id,@NotNull UUID observationId,@NotBlank String anonymousKey,@NotBlank String accountName,@NotBlank String jobTitle,@NotBlank String category,@NotBlank String replyContent,@NotNull Instant sentAt,boolean needsFollowUp,String followUpReason){}
record AiDutyReviewRequiredResponse(@NotNull UUID id,@NotNull UUID observationId,@NotBlank String anonymousKey,@NotBlank String accountName,@NotBlank String jobTitle,@NotBlank String category,@NotBlank String reason,@NotNull Instant decidedAt){}
record VisibleResumeTextRequest(@NotNull UUID observationId,@NotBlank@Pattern(regexp="[a-f0-9]{64}")String sourceEventDigest,@NotBlank@Size(min=100,max=30000)String resumeText){}
record ObservationReviewRequest(@NotBlank@Pattern(regexp="APPROVED|REJECTED|HUMAN_TAKEOVER")String decision,@Size(max=2000)String content,@Size(max=300)String note){}
record CycleTestStartRequest(@NotBlank@Size(max=2000)String content,@AssertTrue(message="必须明确确认只对当前已读会话启动完整周期测试")boolean confirmed){}
record CycleTestCancelRequest(@AssertTrue(message="必须明确确认取消当前完整周期测试")boolean confirmed,@Size(max=300)String note){}
record CycleResumeReviewRequest(@NotBlank@Pattern(regexp="APPROVED|REJECTED")String decision,@Size(max=300)String note){}
record UnreadObservationResponse(UUID id,UUID accountId,String accountName,String companyName,String anonymousKey,int unreadCount,boolean unread,boolean selectedConversationUnread,boolean jobRecognized,boolean previewRecognized,String observedJobTitle,String draftMode,String draftContent,String draftReason,Instant draftGeneratedAt,String draftQualification,UUID matchedJobPositionId,boolean manuallyMatched,Instant manualMatchedAt,List<String> draftBlockerCodes,Integer draftCompanyKnowledgeVersion,Integer draftJobKnowledgeVersion,String eligibilityStatus,String latestDirection,Instant latestMessageAt,Instant detailVerifiedAt,String conversationStage,ConversationSignals conversationSignals,String cycleTestStatus,String resumeReviewStatus,Instant cycleTestStartedAt,Instant cycleTestUpdatedAt,Instant resumeRequestedAt,Instant resumeApprovedAt,Instant contactExchangedAt,Instant humanTakeoverAt,String resumePipelineStatus,String resumePipelineReason,UUID resumeIntakeId,Instant resumePipelineUpdatedAt,String reviewStatus,String reviewedContent,String reviewNote,Instant reviewedAt,String fillStatus,Instant filledAt,String resolutionStatus,Instant resolvedAt,Instant firstSeenAt,Instant lastSeenAt){static UnreadObservationResponse from(BrowserUnreadObservation x){return new UnreadObservationResponse(x.getId(),x.getAccount().getId(),x.getAccount().getDisplayName(),x.getAccount().getCompany().getName(),x.getChatDigest().substring(0,12),x.getUnreadCount(),x.isUnread(),x.isSelectedConversationUnread(),x.getJobDigest()!=null,x.getPreviewDigest()!=null,x.getObservedJobTitle(),x.getDraftMode(),x.getDraftContent(),x.getDraftReason(),x.getDraftGeneratedAt(),x.getDraftQualification(),x.getMatchedJobPositionId(),x.getManualMatchJobPositionId()!=null,x.getManualMatchedAt(),x.getDraftBlockerCodes(),x.getDraftCompanyKnowledgeVersion(),x.getDraftJobKnowledgeVersion(),x.getEligibilityStatus(),x.getLatestDirection(),x.getLatestMessageAt(),x.getDetailVerifiedAt(),x.getConversationStage(),x.getConversationSignals(),x.getCycleTestStatus(),x.getResumeReviewStatus(),x.getCycleTestStartedAt(),x.getCycleTestUpdatedAt(),x.getResumeRequestedAt(),x.getResumeApprovedAt(),x.getContactExchangedAt(),x.getHumanTakeoverAt(),x.getResumePipelineStatus(),x.getResumePipelineReason(),x.getResumeIntakeId(),x.getResumePipelineUpdatedAt(),x.getReviewStatus(),x.getReviewedContent(),x.getReviewNote(),x.getReviewedAt(),x.getDraftFillStatus(),x.getDraftFilledAt(),x.getResolutionStatus(),x.getResolvedAt(),x.getFirstSeenAt(),x.getLastSeenAt());}}
record DraftRecalculationResponse(int evaluated,int knowledgeReady,int blocked,Instant evaluatedAt){}
record ManualJobMatchRequest(@NotEmpty@Size(max=100)List<@NotNull UUID> observationIds,@NotNull UUID jobPositionId,@NotBlank@Size(max=120)String observedTitle,@NotBlank@Size(max=120)String confirmedJobTitle,@AssertTrue(message="必须明确确认岗位关联")boolean confirmed){}
record JobMatchCandidateResponse(UUID id,String title,boolean knowledgeReady,List<String> blockers){}
record UnmatchedJobGroupResponse(String groupKey,UUID accountId,String accountName,String companyName,String observedTitle,List<UUID> observationIds,int conversations,int unreadCount,Instant firstSeenAt,Instant lastSeenAt,List<JobMatchCandidateResponse> candidates){}
record ManualJobMatchResponse(int matched,int knowledgeReady,UUID jobPositionId,String jobTitle,Instant matchedAt){}
record CreateActionTaskRequest(@NotNull UUID observationId,@NotBlank@Pattern(regexp="SEND_MESSAGE|REQUEST_RESUME|EXCHANGE_WECHAT|EXCHANGE_PHONE")String actionType){}
record ConnectorCapabilityResponse(UUID id,UUID deviceId,UUID accountId,String accountName,String companyName,String capability,String status,String reason,Instant verifiedAt,Instant updatedAt){static ConnectorCapabilityResponse from(LocalConnectorCapability x){return new ConnectorCapabilityResponse(x.getId(),x.getDevice().getId(),x.getDevice().getBossAccount().getId(),x.getDevice().getBossAccount().getDisplayName(),x.getDevice().getBossAccount().getCompany().getName(),x.getCapability(),x.getStatus(),x.getReason(),x.getVerifiedAt(),x.getUpdatedAt());}}
record ConnectorActionTaskResponse(UUID id,UUID accountId,String accountName,String companyName,UUID observationId,String anonymousKey,String actionType,String status,String origin,String reason,String requestedBy,Instant createdAt,Instant updatedAt){static ConnectorActionTaskResponse from(LocalConnectorActionTask x){BrowserUnreadObservation o=x.getObservation();return new ConnectorActionTaskResponse(x.getId(),x.getAccount().getId(),x.getAccount().getDisplayName(),x.getAccount().getCompany().getName(),o==null?null:o.getId(),o==null?null:o.getChatDigest().substring(0,12),x.getActionType(),x.getStatus(),x.getOrigin(),x.getReason(),x.getRequestedBy()==null?"系统自动化":x.getRequestedBy().getDisplayName(),x.getCreatedAt(),x.getUpdatedAt());}}
record ActionLeaseClaimRequest(@NotBlank@Pattern(regexp="SEND_MESSAGE|REQUEST_RESUME|EXCHANGE_WECHAT|EXCHANGE_PHONE")String actionType,@NotBlank@Pattern(regexp="[a-f0-9]{64}")String targetDigest){}
record ActionLeaseClaimResponse(boolean available,UUID leaseId,UUID taskId,String actionType,String targetDigest,String payload,String leaseToken,Instant leaseUntil,String mode){static ActionLeaseClaimResponse none(){return new ActionLeaseClaimResponse(false,null,null,null,null,null,null,null,"NO_APPROVED_TASK");}}
record ActionLeaseReceiptRequest(@NotBlank@Size(max=200)String leaseToken,@NotBlank@Pattern(regexp="SUCCEEDED|FAILED|UNKNOWN")String outcome,@NotBlank@Pattern(regexp="[a-f0-9]{64}")String beforeStateDigest,@NotBlank@Pattern(regexp="[a-f0-9]{64}")String afterStateDigest,@NotBlank@Pattern(regexp="[a-f0-9]{64}")String receiptDigest,@NotBlank@Size(max=300)String reason){}
record ActionLeaseResponse(UUID id,UUID taskId,UUID accountId,String accountName,String actionType,String status,String targetDigest,String beforeStateDigest,String afterStateDigest,Instant leasedAt,Instant leaseUntil,String resultReason,Instant completedAt,Instant updatedAt){static ActionLeaseResponse from(LocalConnectorActionLease x){BrowserUnreadObservation o=x.getTask().getObservation();return new ActionLeaseResponse(x.getId(),x.getTask().getId(),x.getTask().getAccount().getId(),x.getTask().getAccount().getDisplayName(),x.getTask().getActionType(),x.getStatus(),o==null?null:o.getChatDigest().substring(0,12),x.getBeforeStateDigest()==null?null:x.getBeforeStateDigest().substring(0,12),x.getAfterStateDigest()==null?null:x.getAfterStateDigest().substring(0,12),x.getLeasedAt(),x.getLeaseUntil(),x.getResultReason(),x.getCompletedAt(),x.getUpdatedAt());}}
record ProductionApprovalRequest(@NotNull UUID validationCaseId,@Min(1)@Max(5)int hourlyLimit,@Min(1)@Max(20)int dailyLimit,@NotBlank@Size(max=300)String reason){}
record ProductionApprovalDecision(@Min(1)@Max(168)int durationHours){}
record ProductionApprovalResponse(UUID id,UUID deviceId,UUID accountId,String accountName,String companyName,String actionType,String status,int hourlyLimit,int dailyLimit,String requestedBy,Instant requestedAt,String approvedBy,Instant approvedAt,Instant expiresAt,String reason,Instant updatedAt){static ProductionApprovalResponse from(LocalConnectorProductionApproval x){return new ProductionApprovalResponse(x.getId(),x.getDevice().getId(),x.getDevice().getBossAccount().getId(),x.getDevice().getBossAccount().getDisplayName(),x.getDevice().getBossAccount().getCompany().getName(),x.getActionType(),x.getStatus(),x.getHourlyLimit(),x.getDailyLimit(),x.getRequestedBy().getDisplayName(),x.getRequestedAt(),x.getApprovedBy()==null?null:x.getApprovedBy().getDisplayName(),x.getApprovedAt(),x.getExpiresAt(),x.getReason(),x.getUpdatedAt());}}
record OfflineDrillReport(@NotBlank@Pattern(regexp="SEND_MESSAGE|REQUEST_RESUME|EXCHANGE_WECHAT|EXCHANGE_PHONE")String actionType,@NotBlank@Pattern(regexp="PASSED|FAILED")String outcome,@NotBlank@Pattern(regexp="FIXTURE_ONLY")String evidenceSource,@NotBlank@Pattern(regexp="[a-f0-9]{64}")String beforeDigest,@NotBlank@Pattern(regexp="[a-f0-9]{64}")String afterDigest,@NotBlank@Pattern(regexp="[a-f0-9]{64}")String receiptDigest,@Size(max=300)String failureReason){}
record OfflineDrillResponse(UUID id,UUID deviceId,UUID accountId,String accountName,String actionType,String outcome,String evidenceSource,String beforeDigest,String afterDigest,String receiptDigest,String failureReason,Instant createdAt){static OfflineDrillResponse from(LocalConnectorOfflineDrill x){return new OfflineDrillResponse(x.getId(),x.getDevice().getId(),x.getDevice().getBossAccount().getId(),x.getDevice().getBossAccount().getDisplayName(),x.getActionType(),x.getOutcome(),x.getEvidenceSource(),x.getBeforeDigest().substring(0,12),x.getAfterDigest().substring(0,12),x.getReceiptDigest().substring(0,12),x.getFailureReason(),x.getCreatedAt());}}
record ValidationReadinessRequest(@NotBlank@Pattern(regexp="SEND_MESSAGE|REQUEST_RESUME|EXCHANGE_WECHAT|EXCHANGE_PHONE")String actionType,@NotBlank@Pattern(regexp="[a-f0-9]{64}")String chatDigest,@NotBlank@Pattern(regexp="[a-f0-9]{64}")String controlDigest,@NotBlank@Pattern(regexp="CHAT_PAGE_READY")String pageState,boolean selectedConversationVerified,boolean hasRiskOrVerification,@Min(3)@Max(20)int stableCycles){}
record ValidationResultRequest(@NotBlank@Pattern(regexp="PASSED|FAILED")String result,@NotBlank@Size(max=500)String note){}
record ApprovedDraftFillClaimRequest(@NotBlank@Pattern(regexp="[a-f0-9]{64}")String chatDigest){}
record ApprovedDraftFillClaimResponse(@NotBlank String claimToken,@NotBlank@Pattern(regexp="[a-f0-9]{64}")String chatDigest,@NotBlank@Pattern(regexp="[a-f0-9]{64}")String draftDigest,@NotBlank@Size(max=2000)String content,@NotNull Instant expiresAt){}
record ApprovedDraftFillReceiptRequest(@NotBlank@Pattern(regexp="[a-f0-9]{64}")String chatDigest,@NotBlank@Pattern(regexp="[a-f0-9]{64}")String draftDigest,@NotBlank@Size(max=200)String claimToken,@NotBlank@Pattern(regexp="FILLED|UNKNOWN")String outcome,@NotBlank@Pattern(regexp="[a-f0-9]{64}")String beforeStateDigest,@NotBlank@Pattern(regexp="[a-f0-9]{64}")String afterStateDigest,@NotBlank@Pattern(regexp="[a-f0-9]{64}")String controlDigest){}
record ApprovedDraftFillReceiptResponse(String status,Instant filledAt){}
record ConnectorValidationCaseResponse(UUID id,UUID deviceId,UUID accountId,String accountName,String companyName,String actionType,String status,List<String> prerequisites,String expectedResult,String lastFailureReason,Instant evidenceObservedAt,Instant testStartedAt,Instant testExpiresAt,Instant completedAt,String resultNote,Instant preparedAt,Instant updatedAt){static ConnectorValidationCaseResponse from(LocalConnectorValidationCase x){return new ConnectorValidationCaseResponse(x.getId(),x.getDevice().getId(),x.getDevice().getBossAccount().getId(),x.getDevice().getBossAccount().getDisplayName(),x.getDevice().getBossAccount().getCompany().getName(),x.getActionType(),x.getStatus(),Arrays.stream(x.getPrerequisites().split("\\n")).filter(v->!v.isBlank()).toList(),x.getExpectedResult(),x.getLastFailureReason(),x.getEvidenceObservedAt(),x.getTestStartedAt(),x.getTestExpiresAt(),x.getCompletedAt(),x.getResultNote(),x.getPreparedAt(),x.getUpdatedAt());}}
