package ai.xzkj.recruitment.localconnector;

import ai.xzkj.recruitment.audit.AuditService;
import ai.xzkj.recruitment.auth.*;
import ai.xzkj.recruitment.autoreply.*;
import ai.xzkj.recruitment.boss.*;
import ai.xzkj.recruitment.common.ApiException;
import ai.xzkj.recruitment.jobs.*;
import ai.xzkj.recruitment.organization.Company;
import org.springframework.http.HttpStatus;
import org.springframework.boot.context.event.ApplicationReadyEvent;
import org.springframework.context.event.EventListener;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.nio.charset.StandardCharsets;
import java.security.*;
import java.time.*;
import java.util.*;

@Service public class LocalConnectorService {
 private static final List<String> CAPABILITY_NAMES=List.of("CHAT_LIST_READ","CONVERSATION_DETAIL_READ","JOB_LIST_READ","SEND_MESSAGE","REQUEST_RESUME","EXCHANGE_WECHAT","EXCHANGE_PHONE");
 private final BrowserDeviceRepository devices;private final BrowserPairingCodeRepository pairings;private final BrowserUnreadObservationRepository observations;private final LocalConnectorCapabilityRepository capabilities;private final LocalConnectorActionTaskRepository actionTasks;private final LocalConnectorValidationCaseRepository validationCases;private final AutoReplyPolicyRepository policies;private final BossAccountRepository accounts;private final JobPositionRepository jobs;private final CurrentUserService users;private final AuditService audit;private final InboundAiReplyQueueService inboundReplyQueue;private final SecureRandom random=new SecureRandom();
 public LocalConnectorService(BrowserDeviceRepository devices,BrowserPairingCodeRepository pairings,BrowserUnreadObservationRepository observations,LocalConnectorCapabilityRepository capabilities,LocalConnectorActionTaskRepository actionTasks,LocalConnectorValidationCaseRepository validationCases,AutoReplyPolicyRepository policies,BossAccountRepository accounts,JobPositionRepository jobs,CurrentUserService users,AuditService audit,InboundAiReplyQueueService inboundReplyQueue){this.devices=devices;this.pairings=pairings;this.observations=observations;this.capabilities=capabilities;this.actionTasks=actionTasks;this.validationCases=validationCases;this.policies=policies;this.accounts=accounts;this.jobs=jobs;this.users=users;this.audit=audit;this.inboundReplyQueue=inboundReplyQueue;}

 @Transactional public PairingResponse createPairing(UUID accountId){SystemUser user=requireManager();BossAccount account=requireConnectorAccount(accountId,user);String token=token();BrowserPairingCode code=pairings.save(new BrowserPairingCode(account,hash(token),user));audit.success("CREATE_LOCAL_CONNECTOR_PAIRING","BOSS_ACCOUNT",accountId,account.getDisplayName(),"创建 10 分钟有效的本地连接器令牌，令牌正文不入库");return new PairingResponse(token,code.getExpiresAt(),accountId,account.getDisplayName());}
 @Transactional public DeviceCredentialsResponse pair(PairDeviceRequest request){BrowserPairingCode code=pairings.findByTokenHash(hash(request.pairingToken().trim())).orElseThrow(()->bad("PAIRING_TOKEN_INVALID","配对令牌无效"));if(!code.usable(Instant.now()))throw bad("PAIRING_TOKEN_EXPIRED","配对令牌已使用或过期");if(code.getAccount().getGatewayType()!=BossGatewayType.LOCAL_CDP_CONNECTOR||code.getAccount().getStatus()!=BossAccountStatus.ACTIVE)throw bad("PAIRING_ACCOUNT_INVALID","连接令牌不属于已启用的本地浏览器招聘账号");devices.findFirstByBossAccountIdAndStatus(code.getAccount().getId(),"ACTIVE").ifPresent(d->{d.revoke();devices.flush();});String raw=token();BrowserDevice device=devices.save(new BrowserDevice(code.getAccount(),clean(request.deviceName(),100),hash(raw),request.clientType(),request.clientVersion(),code.getCreatedBy()));ensureCapabilities(device);ensureValidationCases(device);code.use();code.getAccount().applyCapabilityCheck(BossConnectionStatus.CONNECTED,Set.of(BossCapability.JOB_SYNC,BossCapability.CANDIDATE_READ));audit.systemSuccess("PAIR_LOCAL_CONNECTOR","BOSS_ACCOUNT",code.getAccount().getId(),code.getAccount().getDisplayName(),"本地浏览器桥接 "+request.clientVersion()+" 已配对，设备令牌正文不入库");return new DeviceCredentialsResponse(device.getId(),raw,code.getAccount().getId(),code.getAccount().getDisplayName());}
 @Transactional(readOnly=true) public List<DeviceResponse> list(){SystemUser user=users.requireCurrentUser();return devices.findAllByOrderByCreatedAtDesc().stream().filter(d->canAccess(d.getBossAccount().getCompany().getId(),user)).map(DeviceResponse::from).toList();}
 @Transactional public void revoke(UUID id){SystemUser user=requireManager();BrowserDevice device=devices.findById(id).orElseThrow(()->bad("DEVICE_NOT_FOUND","本地连接器设备不存在"));requireAccess(device.getBossAccount().getCompany().getId(),user);device.revoke();audit.success("REVOKE_LOCAL_CONNECTOR_DEVICE","LOCAL_CONNECTOR_DEVICE",id,device.getDisplayName(),"撤销本地连接器设备令牌");}
 @Transactional public DeviceResponse heartbeat(String authorization,HeartbeatRequest request){BrowserDevice device=authenticate(authorization);device.heartbeat(request.state(),cleanOptional(request.reason(),300),request.pageContext());return DeviceResponse.from(device);}
 @Transactional(readOnly=true) public DutyAutomationControlResponse dutyAutomation(String authorization){BrowserDevice device=authenticate(authorization);Instant now=Instant.now();AutoReplyPolicy policy=policies.findByBossAccountId(device.getBossAccount().getId()).orElse(null);boolean enabled=policy!=null&&policy.isAwayActive(now)&&policy.isAutoSendEnabled();return new DutyAutomationControlResponse(enabled,policy==null?null:policy.getAwayEndsAt(),policy==null?0:policy.getResponseTimeoutMinutes());}
 @Transactional public UnreadObservationSyncResponse observeUnread(String authorization,UnreadObservationSnapshot snapshot){BrowserDevice device=authenticate(authorization);Instant now=Instant.now();AutoReplyPolicy policy=policies.findByBossAccountId(device.getBossAccount().getId()).orElse(null);Set<String> snapshotChats=snapshot.entries().stream().map(UnreadObservationEntry::chatDigest).collect(java.util.stream.Collectors.toSet());for(BrowserUnreadObservation stale:observations.findAllByAccountIdAndUnreadTrue(device.getBossAccount().getId())){if(!stale.getDevice().getId().equals(device.getId()))stale.archiveReplacedSource(now);else if(snapshot.authoritative()&&!snapshotChats.contains(stale.getChatDigest()))stale.markMissingFromLatestSnapshot(now);}for(UnreadObservationEntry entry:snapshot.entries()){Instant first=validObservationTime(entry.firstSeenAt(),now);BrowserUnreadObservation observation=observations.findByAccountIdAndChatDigest(device.getBossAccount().getId(),entry.chatDigest()).orElseGet(()->new BrowserUnreadObservation(device,entry.chatDigest(),first,now));observation.attachSource(device);observation.observe(entry,now);prepareDraft(observation,device.getBossAccount().getId(),now);evaluate(observation,policy,now);observations.save(observation);}verifyReadCapability(device,"CHAT_LIST_READ",snapshot.entries().isEmpty()?hash("empty-chat-list"):snapshot.entries().getFirst().chatDigest(),"真实沟通页会话列表已稳定只读识别",now);if(snapshot.entries().stream().anyMatch(x->x.jobTitle()!=null&&!x.jobTitle().isBlank()))verifyReadCapability(device,"JOB_LIST_READ",hash("observed-job-title"),"已从真实未读会话识别岗位标题，仅用于匹配职位页同步的真实岗位",now);boolean recovered=device.recordSuccessfulSync("CHAT",now);if(recovered)audit.systemSuccess("LOCAL_CONNECTOR_RECOVERED","LOCAL_CONNECTOR_DEVICE",device.getId(),device.getDisplayName(),"暂停或离线后已收到新的沟通页稳定快照，恢复状态已确认");int active=observations.findAllByAccountIdAndUnreadTrue(device.getBossAccount().getId()).size();return new UnreadObservationSyncResponse(active,snapshot.entries().size(),now);}
 @Transactional public VisibleJobSyncResponse observeVisibleJobs(String authorization,VisibleJobSnapshot snapshot){
  BrowserDevice device=authenticate(authorization);Instant now=Instant.now();
  if(snapshot.observedAt().isAfter(now.plusSeconds(30))||snapshot.observedAt().isBefore(now.minusSeconds(120)))throw bad("JOB_SNAPSHOT_STALE","职位页面快照已过期");
  boolean refreshRequested=Boolean.TRUE.equals(snapshot.refreshRequested());
  boolean authoritative=snapshot.authoritative()&&"OPEN_JOBS".equals(snapshot.scope());
  if(snapshot.authoritative()&&!authoritative)throw bad("JOB_SNAPSHOT_SCOPE_INVALID","只有完整的在招职位清单可以作为自动下架依据");
  if(authoritative&&snapshot.entries().stream().anyMatch(entry->!"OPEN".equals(entry.platformStatus())))throw bad("JOB_SNAPSHOT_STATUS_INVALID","完整在招职位清单包含非在招状态");
  BossAccount account=device.getBossAccount();
  List<JobPosition> accountJobs=jobs.findAllByBossAccountId(account.getId());
  Map<String,JobPosition> byTitle=new LinkedHashMap<>();for(JobPosition job:accountJobs)byTitle.putIfAbsent(SafeReplyComposer.normalizePublicTitle(job.getTitle()),job);
  Set<String> snapshotSources=new HashSet<>();Set<UUID> observedIds=new HashSet<>();int created=0,updated=0,unchanged=0,automaticallyClosed=0,reopenedForReview=0;
  for(VisibleJobEntry entry:snapshot.entries()){
   if(!snapshotSources.add(entry.sourceDigest()))throw bad("DUPLICATE_JOB_SOURCE","职位页面快照中存在重复来源");
   String title=cleanOptional(entry.title(),120);String normalized=SafeReplyComposer.normalizePublicTitle(title);if(normalized.isBlank())throw bad("JOB_TITLE_INVALID","职位标题无效");
   String sourceKey=hash(account.getId()+"|visible|"+entry.sourceDigest());JobPosition existing=jobs.findByBossAccountIdAndObservedSourceKey(account.getId(),sourceKey).orElse(byTitle.get(normalized));
   if(existing==null){
    JobPosition imported=new JobPosition(account.getCompany(),account,title,valueOrPlaceholder(entry.location()),entry.salaryMinK()==null?1:entry.salaryMinK(),entry.salaryMaxK()==null?entry.salaryMinK()==null?1:entry.salaryMinK():entry.salaryMaxK(),entry.salaryMonths()==null?12:entry.salaryMonths(),valueOrPlaceholder(entry.experienceRequirement()),valueOrPlaceholder(entry.educationRequirement()),entry.description()==null||entry.description().isBlank()?"由真实 BOSS 职位管理页只读采集，职位描述待 HR 核对补全。":clean(entry.description(),10000),null);
    imported.applyVisiblePageObservation(sourceKey,title,entry.location(),entry.salaryMinK(),entry.salaryMaxK(),entry.salaryMonths(),entry.experienceRequirement(),entry.educationRequirement(),entry.description(),entry.salaryDisplay(),entry.recruitmentType(),entry.jobCategory(),entry.overseasRequirement(),entry.jobKeywords(),entry.workAddress(),entry.completeness(),now);
    if(imported.reconcilePlatformStatus(entry.platformStatus()))automaticallyClosed++;
    jobs.save(imported);observedIds.add(imported.getId());byTitle.put(normalized,imported);created++;
    audit.systemSuccess("IMPORT_VISIBLE_JOB","JOB_POSITION",imported.getId(),title,"从真实 BOSS 职位管理页创建待审核草稿；原始平台 ID、URL 和 Cookie 均未记录");
   }else{
    JobPositionStatus before=existing.getStatus();
    boolean changed=refreshRequested
      ? existing.applyVisiblePageObservation(sourceKey,title,entry.location(),entry.salaryMinK(),entry.salaryMaxK(),entry.salaryMonths(),entry.experienceRequirement(),entry.educationRequirement(),entry.description(),entry.salaryDisplay(),entry.recruitmentType(),entry.jobCategory(),entry.overseasRequirement(),entry.jobKeywords(),entry.workAddress(),entry.completeness(),now,true)
      : existing.recordVisiblePageObservation(sourceKey,now);
    boolean lifecycleChanged=existing.reconcilePlatformStatus(entry.platformStatus(),refreshRequested);observedIds.add(existing.getId());
    if(before==JobPositionStatus.ACTIVE&&existing.getStatus()==JobPositionStatus.DRAFT){audit.systemSuccess("REVIEW_JOB_CHANGED_ON_BOSS","JOB_POSITION",existing.getId(),existing.getTitle(),"BOSS 页面岗位资料发生变化，值守台已暂停该岗位并恢复为待核对草稿");}
    if(before!=JobPositionStatus.CLOSED&&existing.getStatus()==JobPositionStatus.CLOSED){automaticallyClosed++;audit.systemSuccess("CLOSE_JOB_FROM_BOSS","JOB_POSITION",existing.getId(),existing.getTitle(),"BOSS 页面明确显示职位已关闭，值守台已同步下架");}
    if(before==JobPositionStatus.CLOSED&&existing.getStatus()==JobPositionStatus.DRAFT){reopenedForReview++;audit.systemSuccess("REOPEN_JOB_FROM_BOSS","JOB_POSITION",existing.getId(),existing.getTitle(),"BOSS 页面显示职位重新开放，值守台恢复为待核对草稿");}
    if(changed||lifecycleChanged)updated++;else unchanged++;
   }
  }
  if(authoritative){
   for(JobPosition job:accountJobs){
    if(observedIds.contains(job.getId()))continue;
    if(job.markMissingFromCompleteOpenSnapshot()){automaticallyClosed++;audit.systemSuccess("CLOSE_JOB_MISSING_FROM_BOSS","JOB_POSITION",job.getId(),job.getTitle(),"连续两次未出现在完整的 BOSS 在招职位清单中，值守台已同步下架");}
   }
  }
  verifyReadCapability(device,"JOB_LIST_READ",hash(snapshot.entries().stream().map(VisibleJobEntry::sourceDigest).sorted().reduce("",String::concat)),"真实 BOSS 职位管理页已稳定只读识别并去重入库",now);
  device.recordSuccessfulSync("JOB",now);
  audit.systemSuccess("SYNC_VISIBLE_JOBS","BOSS_ACCOUNT",account.getId(),account.getDisplayName(),(refreshRequested?"主动重新识别":"后台巡检")+"接收 "+snapshot.entries().size()+" 个职位：新增 "+created+"，更新 "+updated+"，未改动 "+unchanged+"，自动关闭 "+automaticallyClosed+"，恢复待核对 "+reopenedForReview+"；未执行页面操作");
  return new VisibleJobSyncResponse(snapshot.entries().size(),created,updated,unchanged,automaticallyClosed,reopenedForReview,now);
 }
 @Transactional public UnreadObservationResponse verifySelectedConversation(String authorization,SelectedConversationSnapshot snapshot){BrowserDevice device=authenticate(authorization);Instant now=Instant.now();if(snapshot.observedAt().isAfter(now.plusSeconds(30))||snapshot.observedAt().isBefore(now.minusSeconds(120)))throw bad("DETAIL_SNAPSHOT_STALE","会话详情快照已过期");if(snapshot.messageAt().isAfter(now.plusSeconds(300))||snapshot.messageAt().isBefore(now.minus(Duration.ofDays(30))))throw bad("MESSAGE_TIME_INVALID","最新消息时间无效");BrowserUnreadObservation observation=observations.findByAccountIdAndChatDigest(device.getBossAccount().getId(),snapshot.chatDigest()).orElseThrow(()->bad("OBSERVATION_NOT_FOUND","选中会话不在当前未读观察队列"));if(!observation.getDevice().getId().equals(device.getId())||observation.getLastSeenAt().isBefore(now.minusSeconds(120))||"SNAPSHOT_CONFIRMATION_REQUIRED".equals(observation.getEligibilityStatus()))throw bad("DETAIL_NOT_IN_LATEST_SNAPSHOT","选中会话不属于当前设备的最新稳定列表");String previous=observation.getResolutionStatus();observation.verifyDetail(snapshot.messageDigest(),snapshot.direction(),snapshot.messageAt(),snapshot.selectedUnread(),snapshot.conversationSignals(),now);verifyReadCapability(device,"CONVERSATION_DETAIL_READ",snapshot.messageDigest(),"真实选中会话的最新消息方向、时间与阶段信号已只读复核",now);evaluate(observation,policies.findByBossAccountId(device.getBossAccount().getId()).orElse(null),now);if("UNRESOLVED".equals(previous)&&!"UNRESOLVED".equals(observation.getResolutionStatus()))audit.systemSuccess("CONFIRM_HR_CONNECTOR_REPLY","UNREAD_OBSERVATION",observation.getId(),device.getBossAccount().getDisplayName(),"页面已识别 HR 最新外发，未读任务已闭环，不记录消息正文");return UnreadObservationResponse.from(observation);}

 @Transactional(readOnly=true) public InboundReplyDecisionResponse decideInboundReply(String authorization,InboundReplyDecisionRequest request){BrowserDevice device=authenticate(authorization);Instant now=Instant.now();if(request.observedAt().isAfter(now.plusSeconds(30))||request.observedAt().isBefore(now.minusSeconds(120)))throw bad("INBOUND_REPLY_SNAPSHOT_STALE","候选人消息快照已过期");BrowserUnreadObservation observation=observations.findByAccountIdAndChatDigest(device.getBossAccount().getId(),request.chatDigest()).orElseThrow(()->bad("OBSERVATION_NOT_FOUND","当前会话尚未进入值守观察队列"));if(!observation.getDevice().getId().equals(device.getId())||observation.getDetailVerifiedAt()==null||observation.getDetailVerifiedAt().isBefore(now.minusSeconds(120)))throw bad("INBOUND_REPLY_DETAIL_REQUIRED","当前会话尚未完成稳定复核");if(!"INBOUND".equals(observation.getLatestDirection())||!request.messageDigest().equals(observation.getLatestMessageDigest()))throw new ApiException(HttpStatus.CONFLICT,"INBOUND_REPLY_TARGET_CHANGED","最后一条求职者消息已经变化，已停止回复");if("INTERVIEW_SCHEDULED".equals(observation.getConversationStage())||observation.getConversationSignals().interviewScheduled())return new InboundReplyDecisionResponse(false,"INTERVIEW_COMPLETED",1,null,"该会话已约面试，后续消息交由 HR 跟进，不再自动回复");if(observation.getMatchedJobPositionId()==null)return new InboundReplyDecisionResponse(false,"UNCERTAIN",0,null,"当前会话未唯一匹配已启用岗位");JobPosition job=jobs.findWithDetailsById(observation.getMatchedJobPositionId()).orElse(null);if(job==null||job.getStatus()!=JobPositionStatus.ACTIVE||!device.getBossAccount().getId().equals(job.getBossAccount().getId()))return new InboundReplyDecisionResponse(false,"UNCERTAIN",0,null,"当前会话对应岗位不可用");InboundJobReplyService.Decision decision=inboundReplyQueue.enqueueAndAwait(device.getBossAccount().getId(),observation.getId(),job.getId(),request.chatDigest(),request.messageDigest(),request.messageText(),request.conversationContext());return new InboundReplyDecisionResponse(decision.replyAllowed(),decision.category(),decision.confidence(),decision.content(),decision.reason());}
 @Transactional(readOnly=true) public InboundReplyTaskAcceptedResponse submitInboundReply(String authorization,InboundReplyDecisionRequest request){BrowserDevice device=authenticate(authorization);Instant now=Instant.now();if(request.observedAt().isAfter(now.plusSeconds(30))||request.observedAt().isBefore(now.minusSeconds(120)))throw bad("INBOUND_REPLY_SNAPSHOT_STALE","候选人消息快照已过期");BrowserUnreadObservation observation=observations.findByAccountIdAndChatDigest(device.getBossAccount().getId(),request.chatDigest()).orElseThrow(()->bad("OBSERVATION_NOT_FOUND","当前会话尚未进入值守观察队列"));if(!observation.getDevice().getId().equals(device.getId())||observation.getDetailVerifiedAt()==null||observation.getDetailVerifiedAt().isBefore(now.minusSeconds(120)))throw bad("INBOUND_REPLY_DETAIL_REQUIRED","当前会话尚未完成稳定复核");if(!"INBOUND".equals(observation.getLatestDirection())||!request.messageDigest().equals(observation.getLatestMessageDigest()))throw new ApiException(HttpStatus.CONFLICT,"INBOUND_REPLY_TARGET_CHANGED","最后一条求职者消息已经变化，已停止回复");if("INTERVIEW_SCHEDULED".equals(observation.getConversationStage())||observation.getConversationSignals().interviewScheduled())return completedSubmission("INTERVIEW_COMPLETED","该会话已约面试，后续消息交由 HR 跟进，不再自动回复");if(observation.getMatchedJobPositionId()==null)return completedSubmission("UNCERTAIN","当前会话未唯一匹配已启用岗位");JobPosition job=jobs.findWithDetailsById(observation.getMatchedJobPositionId()).orElse(null);if(job==null||job.getStatus()!=JobPositionStatus.ACTIVE||!device.getBossAccount().getId().equals(job.getBossAccount().getId()))return completedSubmission("UNCERTAIN","当前会话对应岗位不可用");UUID taskId=inboundReplyQueue.submit(device.getBossAccount().getId(),observation.getId(),job.getId(),request.chatDigest(),request.messageDigest(),request.messageText(),request.conversationContext());return new InboundReplyTaskAcceptedResponse(taskId,"QUEUED",null);}
 private InboundReplyTaskAcceptedResponse completedSubmission(String category,String reason){return new InboundReplyTaskAcceptedResponse(null,"COMPLETED",new InboundReplyDecisionResponse(false,category,1,null,reason));}
 @Transactional(readOnly=true) public InboundReplyTaskStatusResponse inboundReplyTaskStatus(String authorization,UUID taskId){BrowserDevice device=authenticate(authorization);return inboundReplyQueue.status(device.getBossAccount().getId(),taskId);}
 @Transactional(readOnly=true) public InboundReplyTaskDiscardResponse discardStaleInboundReply(String authorization,UUID taskId,InboundReplyTaskDiscardRequest request){BrowserDevice device=authenticate(authorization);BrowserUnreadObservation observation=observations.findByAccountIdAndChatDigest(device.getBossAccount().getId(),request.chatDigest()).orElseThrow(()->bad("OBSERVATION_NOT_FOUND","当前会话已不在观察队列"));if(!device.getId().equals(observation.getDevice().getId())||!request.currentMessageDigest().equals(observation.getLatestMessageDigest()))throw new ApiException(HttpStatus.CONFLICT,"AI_REPLY_DISCARD_CURRENT_MESSAGE_MISMATCH","当前消息状态尚未通过后端复核");return inboundReplyQueue.discardStale(device.getBossAccount().getId(),taskId,request);}
 @Transactional(readOnly=true) public InboundReplySendClaimResponse claimInboundReplySend(String authorization,InboundReplySendClaimRequest request){BrowserDevice device=authenticate(authorization);Instant now=Instant.now();BrowserUnreadObservation observation=observations.findByAccountIdAndChatDigest(device.getBossAccount().getId(),request.chatDigest()).orElseThrow(()->bad("OBSERVATION_NOT_FOUND","当前会话已不在观察队列"));if(!device.getId().equals(observation.getDevice().getId())||observation.getDetailVerifiedAt()==null||observation.getDetailVerifiedAt().isBefore(now.minusSeconds(120)))throw new ApiException(HttpStatus.CONFLICT,"AI_REPLY_SEND_DETAIL_STALE","发送前会话详情必须重新稳定复核");if(!"INBOUND".equals(observation.getLatestDirection())||!request.messageDigest().equals(observation.getLatestMessageDigest()))throw new ApiException(HttpStatus.CONFLICT,"AI_REPLY_SEND_MESSAGE_CHANGED","候选人最后一条消息已变化，旧回复禁止发送");if("INTERVIEW_SCHEDULED".equals(observation.getConversationStage())||observation.getConversationSignals().interviewScheduled())throw new ApiException(HttpStatus.CONFLICT,"INTERVIEW_COMPLETED","该会话已约面试，禁止继续自动回复");return inboundReplyQueue.claimSend(device.getBossAccount().getId(),device.getId(),request);}
 @Transactional(readOnly=true) public InboundReplySendReceiptResponse receiptInboundReplySend(String authorization,InboundReplySendReceiptRequest request){BrowserDevice device=authenticate(authorization);return inboundReplyQueue.receiptSend(device.getBossAccount().getId(),device.getId(),request);}
 @Transactional public ApprovedDraftFillClaimResponse claimApprovedDraftFill(String authorization,ApprovedDraftFillClaimRequest request){BrowserDevice device=authenticate(authorization);Instant now=Instant.now();if(!"RUNNING".equals(device.getRuntimeState())||!"CHAT".equals(device.getPageContext()))throw new ApiException(HttpStatus.CONFLICT,"DRAFT_FILL_PAGE_NOT_READY","桥接必须正在稳定观测当前沟通页");BrowserUnreadObservation observation=observations.findByAccountIdAndChatDigest(device.getBossAccount().getId(),request.chatDigest()).orElseThrow(()->bad("OBSERVATION_NOT_FOUND","当前会话没有可用的后台草稿"));prepareDraft(observation,device.getBossAccount().getId(),now);if(!"APPROVED".equals(observation.getReviewStatus())||!"KNOWLEDGE_READY".equals(observation.getDraftQualification())||observation.getReviewedContent()==null||!"INBOUND".equals(observation.getLatestDirection())||observation.getDetailVerifiedAt()==null||observation.getDetailVerifiedAt().isBefore(now.minusSeconds(180)))throw new ApiException(HttpStatus.CONFLICT,"APPROVED_DRAFT_FILL_REQUIRED","当前会话必须具有最新详情复核和当前知识版本下的已审核安全草稿");String content=observation.getReviewedContent().trim();String digest=hash(content);String raw=token();Instant expiresAt=now.plusSeconds(60);try{observation.claimDraftFill(hash(raw),digest,device.getId(),expiresAt,now);}catch(IllegalStateException e){throw new ApiException(HttpStatus.CONFLICT,"DRAFT_FILL_NOT_READY",e.getMessage());}audit.systemSuccess("CLAIM_APPROVED_DRAFT_FILL","UNREAD_OBSERVATION",observation.getId(),device.getBossAccount().getDisplayName(),"HR 手动触发 60 秒单次草稿填入；只返回已审核内容，不授权发送");return new ApprovedDraftFillClaimResponse(raw,observation.getChatDigest(),digest,content,expiresAt);}
 @Transactional public ApprovedDraftFillReceiptResponse receiptApprovedDraftFill(String authorization,ApprovedDraftFillReceiptRequest request){BrowserDevice device=authenticate(authorization);BrowserUnreadObservation observation=observations.findByAccountIdAndChatDigest(device.getBossAccount().getId(),request.chatDigest()).orElseThrow(()->bad("OBSERVATION_NOT_FOUND","草稿填入会话不存在"));if(!device.getId().equals(observation.getDraftFillDeviceId()))throw new ApiException(HttpStatus.FORBIDDEN,"DRAFT_FILL_DEVICE_MISMATCH","草稿填入凭据不属于当前设备");if("FILLED".equals(request.outcome())&&request.beforeStateDigest().equals(request.afterStateDigest()))throw new ApiException(HttpStatus.CONFLICT,"DRAFT_FILL_STATE_UNCHANGED","草稿填入成功必须包含明确的输入框状态变化");Instant now=Instant.now();try{observation.completeDraftFill(hash(request.claimToken().trim()),request.draftDigest(),request.outcome(),now);}catch(IllegalStateException e){throw new ApiException(HttpStatus.CONFLICT,"DRAFT_FILL_RECEIPT_REJECTED",e.getMessage());}audit.systemSuccess("RECEIVE_APPROVED_DRAFT_FILL_RECEIPT","UNREAD_OBSERVATION",observation.getId(),device.getBossAccount().getDisplayName(),"草稿填入 "+observation.getDraftFillStatus()+"；仅保存摘要证据，未执行发送");return new ApprovedDraftFillReceiptResponse(observation.getDraftFillStatus(),observation.getDraftFilledAt());}
 @Transactional(readOnly=true) public List<UnreadObservationResponse> listUnreadObservations(){SystemUser user=users.requireCurrentUser();return observations.findTop100ByOrderByLastSeenAtDesc().stream().filter(x->canAccess(x.getAccount().getCompany().getId(),user)).map(UnreadObservationResponse::from).toList();}
 @Transactional(readOnly=true) public List<AiDutyReplyResponse> listRecentAiDutyReplies(){SystemUser user=users.requireCurrentUser();Instant since=Instant.now().minus(Duration.ofHours(24));List<AiDutyReplyResponse> result=new ArrayList<>();for(InboundAiReplyTask task:inboundReplyQueue.recentSuccessfulSends()){if(task.getSendCompletedAt()==null||task.getSendCompletedAt().isBefore(since)||task.getReplyContent()==null)continue;BossAccount account=accounts.findWithDetailsById(task.getAccountId()).orElse(null);JobPosition job=jobs.findById(task.getJobPositionId()).orElse(null);BrowserUnreadObservation observation=observations.findWithAccountById(task.getObservationId()).orElse(null);if(account==null||job==null||observation==null||!canAccess(account.getCompany().getId(),user))continue;boolean hasNewInbound=observation.isUnread()&&"INBOUND".equals(observation.getLatestDirection());boolean needsFollowUp=task.isPartialReply()||hasNewInbound;String followUpReason=task.isPartialReply()?task.getResultReason():hasNewInbound?"候选人已发送新消息，待 HR 跟进":null;result.add(new AiDutyReplyResponse(task.getId(),observation.getId(),task.getChatDigest().substring(0,12),account.getDisplayName(),job.getTitle(),task.getCategory()==null?"岗位咨询":task.getCategory(),task.getReplyContent(),task.getSendCompletedAt(),needsFollowUp,followUpReason));}return result;}
 @Transactional(readOnly=true) public List<AiDutyReviewRequiredResponse> listRecentAiDutyReviewRequired(){SystemUser user=users.requireCurrentUser();Instant since=Instant.now().minus(Duration.ofHours(24));List<AiDutyReviewRequiredResponse> result=new ArrayList<>();for(InboundAiReplyTask task:inboundReplyQueue.recentSkippedReplies()){if(task.getCompletedAt()==null||task.getCompletedAt().isBefore(since)||task.getCategory()==null||task.isExpectedSilence()||task.isShadowEvaluation())continue;BossAccount account=accounts.findWithDetailsById(task.getAccountId()).orElse(null);JobPosition job=jobs.findById(task.getJobPositionId()).orElse(null);BrowserUnreadObservation observation=observations.findWithAccountById(task.getObservationId()).orElse(null);if(account==null||job==null||observation==null||!canAccess(account.getCompany().getId(),user))continue;if(!observation.isUnread()||!"INBOUND".equals(observation.getLatestDirection()))continue;result.add(new AiDutyReviewRequiredResponse(task.getId(),observation.getId(),task.getChatDigest().substring(0,12),account.getDisplayName(),job.getTitle(),task.getCategory(),task.getResultReason()==null?"AI 已安全跳过自动回复，请 HR 人工复核":task.getResultReason(),task.getCompletedAt()));}return result;}
 @Transactional(readOnly=true) public InboundReplyQualitySummaryResponse inboundReplyQualitySummary(){
  SystemUser user=users.requireCurrentUser();Instant now=Instant.now();List<InboundAiReplyTask> visible=new ArrayList<>();
  for(InboundAiReplyTask task:inboundReplyQueue.recentDecisions(now.minus(Duration.ofHours(24)))){BossAccount account=accounts.findWithDetailsById(task.getAccountId()).orElse(null);if(account!=null&&canAccess(account.getCompany().getId(),user))visible.add(task);}
  int approved=0,sent=0,silence=0,review=0,shadow=0,failed=0;double confidence=0;Map<String,Long> categories=new TreeMap<>();Map<String,Long> outcomes=new LinkedHashMap<>();
  for(InboundAiReplyTask task:visible){if(task.wasReplyApproved())approved++;if("SUCCEEDED".equals(task.getSendStatus()))sent++;if(task.isExpectedSilence())silence++;if(task.isShadowEvaluation())shadow++;if("FAILED".equals(task.getStatus()))failed++;if("SKIPPED".equals(task.getSendStatus())&&!task.isExpectedSilence()&&!task.isShadowEvaluation()&&!"FAILED".equals(task.getStatus()))review++;confidence+=task.getConfidence()==null?0:task.getConfidence();categories.merge(task.getCategory()==null?"UNKNOWN":task.getCategory(),1L,Long::sum);String outcome=task.isShadowEvaluation()?"SHADOW":task.isExpectedSilence()?"EXPECTED_SILENCE":"FAILED".equals(task.getStatus())?"FAILED":"SUCCEEDED".equals(task.getSendStatus())?"SENT":"READY".equals(task.getSendStatus())?"READY":"SKIPPED".equals(task.getSendStatus())?"REVIEW_REQUIRED":"OTHER";outcomes.merge(outcome,1L,Long::sum);}
  double average=visible.isEmpty()?0:Math.round(confidence/visible.size()*1000d)/1000d;
  return new InboundReplyQualitySummaryResponse(visible.size(),approved,sent,silence,review,shadow,failed,average,categories,outcomes,now);
 }
 @Transactional(readOnly=true) public List<UnmatchedJobGroupResponse> listUnmatchedJobGroups(){SystemUser user=users.requireCurrentUser();Map<String,List<BrowserUnreadObservation>> grouped=new LinkedHashMap<>();for(BrowserUnreadObservation observation:observations.findTop100ByOrderByLastSeenAtDesc()){String titleKey=SafeReplyComposer.normalizePublicTitle(observation.getObservedJobTitle());if(!observation.isUnread()||!"JOB_UNMATCHED".equals(observation.getDraftQualification())||titleKey.isBlank()||!canAccess(observation.getAccount().getCompany().getId(),user))continue;grouped.computeIfAbsent(observation.getAccount().getId()+"|"+titleKey,ignored->new ArrayList<>()).add(observation);}List<UnmatchedJobGroupResponse> result=new ArrayList<>();for(var entry:grouped.entrySet()){List<BrowserUnreadObservation> items=entry.getValue();BrowserUnreadObservation first=items.getFirst();List<JobMatchCandidateResponse> candidates=jobs.findAllByBossAccountIdAndStatus(first.getAccount().getId(),JobPositionStatus.ACTIVE).stream().map(job->{SafeReplyComposer.Composition composition=SafeReplyComposer.compose(job);return new JobMatchCandidateResponse(job.getId(),job.getTitle(),"KNOWLEDGE".equals(composition.mode()),composition.blockerCodes());}).sorted(Comparator.comparing(JobMatchCandidateResponse::knowledgeReady).reversed().thenComparing(JobMatchCandidateResponse::title)).toList();result.add(new UnmatchedJobGroupResponse(hash(entry.getKey()).substring(0,12),first.getAccount().getId(),first.getAccount().getDisplayName(),first.getAccount().getCompany().getName(),first.getObservedJobTitle(),items.stream().map(BrowserUnreadObservation::getId).toList(),items.size(),items.stream().mapToInt(BrowserUnreadObservation::getUnreadCount).sum(),items.stream().map(BrowserUnreadObservation::getFirstSeenAt).min(Instant::compareTo).orElse(first.getFirstSeenAt()),items.stream().map(BrowserUnreadObservation::getLastSeenAt).max(Instant::compareTo).orElse(first.getLastSeenAt()),candidates));}return result.stream().sorted(Comparator.comparing(UnmatchedJobGroupResponse::conversations).reversed().thenComparing(UnmatchedJobGroupResponse::observedTitle)).toList();}
 @Transactional public ManualJobMatchResponse manualJobMatch(ManualJobMatchRequest request){SystemUser user=users.requireCurrentUser();LinkedHashSet<UUID> ids=new LinkedHashSet<>(request.observationIds());if(ids.size()!=request.observationIds().size())throw bad("DUPLICATE_OBSERVATION_ID","待关联会话中存在重复记录");List<BrowserUnreadObservation> items=observations.findAllById(ids);if(items.size()!=ids.size())throw bad("OBSERVATION_NOT_FOUND","部分未读观察已不存在，请刷新后重试");BrowserUnreadObservation first=items.getFirst();UUID accountId=first.getAccount().getId();String titleKey=SafeReplyComposer.normalizePublicTitle(request.observedTitle());if(titleKey.isBlank())throw bad("OBSERVED_JOB_TITLE_REQUIRED","观测岗位标题不能为空");for(BrowserUnreadObservation item:items){requireAccess(item.getAccount().getCompany().getId(),user);if(!item.isUnread()||!"JOB_UNMATCHED".equals(item.getDraftQualification()))throw new ApiException(HttpStatus.CONFLICT,"OBSERVATION_MATCH_STATE_CHANGED","部分会话已处理或岗位资格已变化，请刷新后重试");if(!accountId.equals(item.getAccount().getId())||!titleKey.equals(SafeReplyComposer.normalizePublicTitle(item.getObservedJobTitle())))throw bad("OBSERVATION_GROUP_MISMATCH","只能批量关联同一招聘账号、同一观测岗位标题的会话");}JobPosition job=jobs.findWithDetailsById(request.jobPositionId()).orElseThrow(()->bad("JOB_POSITION_NOT_FOUND","目标岗位不存在"));if(job.getStatus()!=JobPositionStatus.ACTIVE||!accountId.equals(job.getBossAccount().getId()))throw bad("ACTIVE_ACCOUNT_JOB_REQUIRED","只能关联同一招聘账号下的启用岗位");if(!job.getTitle().equals(request.confirmedJobTitle().trim()))throw bad("CONFIRMED_JOB_TITLE_MISMATCH","确认的目标岗位标题与当前岗位资料不一致，请刷新后重试");SafeReplyComposer.Composition composition=SafeReplyComposer.compose(job);if(!"KNOWLEDGE".equals(composition.mode()))throw new ApiException(HttpStatus.CONFLICT,"TARGET_JOB_KNOWLEDGE_BLOCKED","目标岗位的企业或岗位知识尚未完整审核");Instant now=Instant.now();int ready=0;for(BrowserUnreadObservation item:items){item.manuallyMatchJob(job.getId(),titleKey,now);prepareDraft(item,accountId,now);evaluate(item,policies.findByBossAccountId(accountId).orElse(null),now);if("KNOWLEDGE_READY".equals(item.getDraftQualification()))ready++;}observations.saveAll(items);audit.success("MANUALLY_MATCH_UNREAD_JOB","JOB_POSITION",job.getId(),job.getTitle(),"HR 明确确认将观测岗位「"+request.observedTitle().trim()+"」关联到「"+job.getTitle()+"」，共 "+items.size()+" 条匿名未读；只重算后台草稿，不操作 BOSS 页面");return new ManualJobMatchResponse(items.size(),ready,job.getId(),job.getTitle(),now);}
 @Transactional public DraftRecalculationResponse recalculateDrafts(){SystemUser user=users.requireCurrentUser();Instant now=Instant.now();List<BrowserUnreadObservation> accessible=observations.findTop100ByOrderByLastSeenAtDesc().stream().filter(BrowserUnreadObservation::isUnread).filter(x->canAccess(x.getAccount().getCompany().getId(),user)).toList();int ready=0;for(BrowserUnreadObservation observation:accessible){prepareDraft(observation,observation.getAccount().getId(),now);if("KNOWLEDGE_READY".equals(observation.getDraftQualification()))ready++;}observations.saveAll(accessible);audit.success("RECALCULATE_SAFE_DRAFTS","SYSTEM_USER",user.getId(),user.getDisplayName(),"重新评估 "+accessible.size()+" 条未读安全草稿，其中知识草稿 "+ready+" 条；未执行页面发送");return new DraftRecalculationResponse(accessible.size(),ready,accessible.size()-ready,now);}
 @Transactional public UnreadObservationResponse reviewObservation(UUID id,ObservationReviewRequest request){SystemUser user=users.requireCurrentUser();BrowserUnreadObservation observation=observations.findWithAccountById(id).orElseThrow(()->bad("OBSERVATION_NOT_FOUND","未读观察不存在"));requireAccess(observation.getAccount().getCompany().getId(),user);Instant now=Instant.now();prepareDraft(observation,observation.getAccount().getId(),now);evaluate(observation,policies.findByBossAccountId(observation.getAccount().getId()).orElse(null),now);if(!"READY_FOR_REVIEW".equals(observation.getEligibilityStatus())&&!"APPROVED_DRAFT".equals(observation.getEligibilityStatus()))throw new ApiException(HttpStatus.CONFLICT,"OBSERVATION_NOT_REVIEWABLE","当前会话尚未通过超时、最新消息和资料版本复核");String content=cleanOptional(request.content(),2000);if("APPROVED".equals(request.decision())){if(!"KNOWLEDGE_READY".equals(observation.getDraftQualification()))throw new ApiException(HttpStatus.CONFLICT,"SAFE_DRAFT_KNOWLEDGE_REQUIRED","只有严格匹配已审核企业与岗位资料的知识草稿才可批准");if(content==null)throw bad("REVIEW_CONTENT_REQUIRED","批准草稿前必须确认回复内容");}observation.review(request.decision(),content,cleanOptional(request.note(),300),user,now);audit.success("REVIEW_CONNECTOR_DRAFT","UNREAD_OBSERVATION",id,observation.getAccount().getDisplayName(),"安全草稿人工处理："+request.decision()+"；企业知识版本 "+observation.getDraftCompanyKnowledgeVersion()+"，岗位知识版本 "+observation.getDraftJobKnowledgeVersion());return UnreadObservationResponse.from(observation);}
 @Transactional public UnreadObservationResponse startCycleTest(UUID id,CycleTestStartRequest request){SystemUser user=users.requireCurrentUser();BrowserUnreadObservation observation=observations.findWithAccountById(id).orElseThrow(()->bad("OBSERVATION_NOT_FOUND","会话观测不存在"));requireAccess(observation.getAccount().getCompany().getId(),user);for(BrowserUnreadObservation active:observations.findActiveCycleTests())if(!active.getId().equals(id))throw new ApiException(HttpStatus.CONFLICT,"ANOTHER_CYCLE_TEST_ACTIVE","已有另一条会话正在进行完整周期测试，请先完成或人工接管该周期");Instant now=Instant.now();prepareDraft(observation,observation.getAccount().getId(),now);try{observation.startCycleTest(cleanOptional(request.content(),2000),user,now);}catch(IllegalStateException e){throw new ApiException(HttpStatus.CONFLICT,"CYCLE_TEST_NOT_READY",e.getMessage());}audit.success("START_SINGLE_CONVERSATION_CYCLE_TEST","UNREAD_OBSERVATION",id,observation.getAccount().getDisplayName(),"HR 已明确确认对当前匿名已读会话启动单次完整周期测试；测试免能力与生产批准，动作仍严格绑定当前会话与单次租约");return UnreadObservationResponse.from(observation);}
 @Transactional public UnreadObservationResponse cancelCycleTest(UUID id,CycleTestCancelRequest request){SystemUser user=users.requireCurrentUser();BrowserUnreadObservation observation=observations.findWithAccountById(id).orElseThrow(()->bad("OBSERVATION_NOT_FOUND","会话观测不存在"));requireAccess(observation.getAccount().getCompany().getId(),user);Instant now=Instant.now();List<LocalConnectorActionTask> cycleTasks=actionTasks.findCycleTasksForUpdate(observation.getId(),observation.getFirstSeenAt());if(cycleTasks.stream().anyMatch(task->"LEASED".equals(task.getStatus())))throw new ApiException(HttpStatus.CONFLICT,"CYCLE_ACTION_IN_PROGRESS","当前页面动作正在执行，请等待回执后再取消");for(LocalConnectorActionTask task:cycleTasks)task.cancelIfPending("HR 已取消当前完整周期测试",now);try{observation.cancelCycleTest(user,cleanOptional(request.note(),300),now);}catch(IllegalStateException e){throw new ApiException(HttpStatus.CONFLICT,"CYCLE_TEST_NOT_ACTIVE",e.getMessage());}audit.success("CANCEL_SINGLE_CONVERSATION_CYCLE_TEST","UNREAD_OBSERVATION",id,observation.getAccount().getDisplayName(),"HR 已取消当前单会话完整周期测试；所有尚未执行的周期动作均已取消");return UnreadObservationResponse.from(observation);}
 @Transactional public UnreadObservationResponse reviewCycleResume(UUID id,CycleResumeReviewRequest request){SystemUser user=users.requireCurrentUser();BrowserUnreadObservation observation=observations.findWithAccountById(id).orElseThrow(()->bad("OBSERVATION_NOT_FOUND","会话观测不存在"));requireAccess(observation.getAccount().getCompany().getId(),user);Instant now=Instant.now();try{observation.reviewCycleResume(request.decision(),user,cleanOptional(request.note(),300),now);}catch(IllegalStateException e){throw new ApiException(HttpStatus.CONFLICT,"CYCLE_RESUME_NOT_REVIEWABLE",e.getMessage());}audit.success("REVIEW_CYCLE_RESUME","UNREAD_OBSERVATION",id,observation.getAccount().getDisplayName(),"完整周期测试的简历人工复核结果："+request.decision()+"；未自动安排面试");return UnreadObservationResponse.from(observation);}
 @Transactional(readOnly=true) public List<ConnectorCapabilityResponse> listCapabilities(){SystemUser user=users.requireCurrentUser();return capabilities.findAllByOrderByUpdatedAtDesc().stream().filter(x->canAccess(x.getDevice().getBossAccount().getCompany().getId(),user)).map(ConnectorCapabilityResponse::from).toList();}
 @Transactional(readOnly=true) public List<ConnectorActionTaskResponse> listActionTasks(){SystemUser user=users.requireCurrentUser();return actionTasks.findTop100ByOrderByCreatedAtDesc().stream().filter(x->canAccess(x.getAccount().getCompany().getId(),user)).map(ConnectorActionTaskResponse::from).toList();}
 @Transactional(readOnly=true) public List<ConnectorValidationCaseResponse> listValidationCases(){SystemUser user=users.requireCurrentUser();return validationCases.findAllByOrderByPreparedAtDesc().stream().filter(x->canAccess(x.getDevice().getBossAccount().getCompany().getId(),user)).map(ConnectorValidationCaseResponse::from).toList();}
 @Transactional public ConnectorValidationCaseResponse reportValidationReadiness(String authorization,ValidationReadinessRequest request){BrowserDevice device=authenticate(authorization);if(!request.selectedConversationVerified()||request.hasRiskOrVerification()||request.stableCycles()<3)throw new ApiException(HttpStatus.CONFLICT,"VALIDATION_PAGE_NOT_READY","页面、会话或操作入口尚未满足人工验收条件");LocalConnectorValidationCase validation=validationCases.findByDeviceIdAndActionType(device.getId(),request.actionType()).orElseThrow(()->bad("VALIDATION_CASE_NOT_FOUND","人工验收项目不存在"));Instant now=Instant.now();validation.prepare(request.chatDigest(),request.controlDigest(),now);LocalConnectorCapability capability=capabilities.findByDeviceIdAndCapability(device.getId(),request.actionType()).orElseThrow(()->bad("CAPABILITY_NOT_FOUND","页面能力不存在"));capability.readyForManualTest(hash(request.chatDigest()+"|"+request.controlDigest()),now);audit.systemSuccess("PREPARE_CONNECTOR_MANUAL_VALIDATION","LOCAL_CONNECTOR_VALIDATION",validation.getId(),device.getBossAccount().getDisplayName(),request.actionType()+" 页面入口已稳定识别；仅开放人工验收窗口，不执行页面动作");return ConnectorValidationCaseResponse.from(validation);}
 @Transactional public ConnectorValidationCaseResponse startValidation(UUID id){SystemUser user=requireManager();LocalConnectorValidationCase validation=requireValidation(id,user);try{validation.start(user,Instant.now());}catch(IllegalStateException e){throw new ApiException(HttpStatus.CONFLICT,"VALIDATION_NOT_READY",e.getMessage());}audit.success("START_CONNECTOR_MANUAL_VALIDATION","LOCAL_CONNECTOR_VALIDATION",id,validation.getDevice().getBossAccount().getDisplayName(),validation.getActionType()+" 开启 10 分钟人工验收窗口；系统不会自动点击");return ConnectorValidationCaseResponse.from(validation);}
 @Transactional public ConnectorValidationCaseResponse completeValidation(UUID id,ValidationResultRequest request){SystemUser user=requireManager();LocalConnectorValidationCase validation=requireValidation(id,user);boolean passed="PASSED".equals(request.result());try{validation.complete(passed,clean(request.note(),500),user,Instant.now());}catch(IllegalStateException e){throw new ApiException(HttpStatus.CONFLICT,"VALIDATION_NOT_RUNNING",e.getMessage());}boolean actuallyPassed="PASSED".equals(validation.getStatus());LocalConnectorCapability capability=capabilities.findByDeviceIdAndCapability(validation.getDevice().getId(),validation.getActionType()).orElseThrow(()->bad("CAPABILITY_NOT_FOUND","页面能力不存在"));capability.recordManualResult(actuallyPassed,validation.getPageEvidenceDigest(),Instant.now());audit.success("COMPLETE_CONNECTOR_MANUAL_VALIDATION","LOCAL_CONNECTOR_VALIDATION",id,validation.getDevice().getBossAccount().getDisplayName(),validation.getActionType()+" · "+validation.getStatus()+"；仍未批准生产自动化");return ConnectorValidationCaseResponse.from(validation);}
 @Transactional public ConnectorActionTaskResponse createActionTask(CreateActionTaskRequest request){SystemUser user=users.requireCurrentUser();BrowserUnreadObservation observation=observations.findWithAccountById(request.observationId()).orElseThrow(()->bad("OBSERVATION_NOT_FOUND","未读观察不存在"));requireAccess(observation.getAccount().getCompany().getId(),user);if("SEND_MESSAGE".equals(request.actionType())){Instant now=Instant.now();prepareDraft(observation,observation.getAccount().getId(),now);evaluate(observation,policies.findByBossAccountId(observation.getAccount().getId()).orElse(null),now);if(!"APPROVED".equals(observation.getReviewStatus())||!"KNOWLEDGE_READY".equals(observation.getDraftQualification()))throw new ApiException(HttpStatus.CONFLICT,"CURRENT_APPROVED_DRAFT_REQUIRED","登记发送动作前必须重新确认当前企业与岗位知识版本下的安全草稿");}BrowserDevice device=devices.findFirstByBossAccountIdAndStatus(observation.getAccount().getId(),"ACTIVE").orElse(null);LocalConnectorCapability capability=device==null?null:capabilities.findByDeviceIdAndCapability(device.getId(),request.actionType()).orElse(null);String status=capability!=null&&"READY_FOR_MANUAL_TEST".equals(capability.getStatus())?"WAITING_MANUAL_TEST":"BLOCKED_UNVERIFIED";String reason="BLOCKED_UNVERIFIED".equals(status)?"真实页面写操作尚未验证，任务仅登记且不会下发到浏览器":"等待 HR 在真实页面执行单次人工测试，连接器不会自动点击";LocalConnectorActionTask task=actionTasks.save(new LocalConnectorActionTask(observation.getAccount(),observation,request.actionType(),status,user,reason));audit.success("CREATE_CONNECTOR_ACTION_TASK","LOCAL_CONNECTOR_ACTION",task.getId(),observation.getAccount().getDisplayName(),request.actionType()+" · "+reason);return ConnectorActionTaskResponse.from(task);}
 @EventListener(ApplicationReadyEvent.class) @Transactional public void backfillObservedJobs(){for(BrowserDevice device:devices.findAllByOrderByCreatedAtDesc()){ensureCapabilities(device);ensureValidationCases(device);}for(BrowserUnreadObservation observation:observations.findTop100ByOrderByLastSeenAtDesc()){BrowserDevice device=observation.getDevice();Instant evidenceTime=observation.getLastSeenAt();verifyReadCapability(device,"CHAT_LIST_READ",observation.getChatDigest(),"已有真实沟通页会话列表观测已回填",evidenceTime);if(observation.getObservedJobTitle()!=null)verifyReadCapability(device,"JOB_LIST_READ",observation.getJobDigest()==null?hash(observation.getObservedJobTitle()):observation.getJobDigest(),"已有真实岗位标题观测已回填，不创建岗位资料",evidenceTime);if(observation.getDetailVerifiedAt()!=null)verifyReadCapability(device,"CONVERSATION_DETAIL_READ",observation.getChatDigest(),"已有真实选中会话详情观测已回填",observation.getDetailVerifiedAt());}}
 @Transactional(readOnly=true) public BrowserDevice authenticate(String header){if(header==null||!header.startsWith("Device "))throw unauthorized();String raw=header.substring(7).trim();if(raw.length()<20)throw unauthorized();BrowserDevice device=devices.findByTokenHashAndStatus(hash(raw),"ACTIVE").orElseThrow(this::unauthorized);if(device.getBossAccount().getGatewayType()!=BossGatewayType.LOCAL_CDP_CONNECTOR||device.getBossAccount().getStatus()!=BossAccountStatus.ACTIVE||!"BROWSER_READONLY_BRIDGE".equals(device.getClientType()))throw unauthorized();return device;}

 private BossAccount requireConnectorAccount(UUID id,SystemUser user){BossAccount account=accounts.findWithDetailsById(id).orElseThrow(()->bad("BOSS_ACCOUNT_NOT_FOUND","BOSS 账号不存在"));requireAccess(account.getCompany().getId(),user);if(account.getGatewayType()!=BossGatewayType.LOCAL_CDP_CONNECTOR)throw bad("LOCAL_CONNECTOR_ACCOUNT_REQUIRED","只有本地浏览器招聘账号可以连接 Chrome 只读桥接器");if(account.getStatus()!=BossAccountStatus.ACTIVE)throw bad("BOSS_ACCOUNT_INACTIVE","请先启用招聘账号再连接本机 Chrome");return account;}
 private SystemUser requireManager(){SystemUser user=users.requireCurrentUser();if(user.getRole()==UserRole.RECRUITER)throw new ApiException(HttpStatus.FORBIDDEN,"FORBIDDEN","当前账号没有本地连接器管理权限");return user;}
 private void prepareDraft(BrowserUnreadObservation observation,UUID accountId,Instant now){String title=cleanOptional(observation.getObservedJobTitle(),120);String titleKey=SafeReplyComposer.normalizePublicTitle(title);if(observation.getManualMatchJobPositionId()!=null){JobPosition manual=titleKey.equals(observation.getManualMatchTitleKey())?jobs.findWithDetailsById(observation.getManualMatchJobPositionId()).orElse(null):null;if(manual!=null&&manual.getStatus()==JobPositionStatus.ACTIVE&&accountId.equals(manual.getBossAccount().getId())){SafeReplyComposer.Composition result=SafeReplyComposer.compose(manual);observation.prepareDraft(result.mode(),result.content(),"HR 已人工确认岗位关联；"+result.reason(),"KNOWLEDGE".equals(result.mode())?"KNOWLEDGE_READY":"KNOWLEDGE_BLOCKED",manual.getId(),result.blockerCodes(),manual.getCompany().getKnowledgeVersion(),manual.getKnowledgeVersion(),now);return;}observation.clearManualJobMatch();}SafeReplyComposer.JobMatch match=SafeReplyComposer.matchActiveJobDetailed(title,jobs.findAllByBossAccountIdAndStatus(accountId,JobPositionStatus.ACTIVE));if(match.job().isEmpty()){String blocker=switch(match.status()){case"TITLE_MISSING"->"JOB_TITLE_MISSING";case"AMBIGUOUS"->"ACTIVE_JOB_AMBIGUOUS";default->"ACTIVE_JOB_NOT_FOUND";};String reason=switch(match.status()){case"TITLE_MISSING"->"网页未识别到岗位名称";case"AMBIGUOUS"->"同账号下存在多个规范化标题相同的启用岗位，已禁止猜测";default->"同账号下未找到标题严格匹配的启用岗位，已禁止猜测";};observation.prepareDraft("GENERIC",SafeReplyComposer.GENERIC_REPLY,reason,"JOB_UNMATCHED",null,List.of(blocker),null,null,now);return;}JobPosition job=match.job().get();SafeReplyComposer.Composition result=SafeReplyComposer.compose(job);observation.prepareDraft(result.mode(),result.content(),result.reason(),"KNOWLEDGE".equals(result.mode())?"KNOWLEDGE_READY":"KNOWLEDGE_BLOCKED",job.getId(),result.blockerCodes(),job.getCompany().getKnowledgeVersion(),job.getKnowledgeVersion(),now);}
 private void evaluate(BrowserUnreadObservation observation,AutoReplyPolicy policy,Instant now){observation.evaluate(now,policy==null?120:policy.getResponseTimeoutMinutes(),policy!=null&&policy.isAwayActive(now));}
 private void ensureCapabilities(BrowserDevice device){for(String name:CAPABILITY_NAMES)if(capabilities.findByDeviceIdAndCapability(device.getId(),name).isEmpty())capabilities.save(new LocalConnectorCapability(device,name));}
 private void ensureValidationCases(BrowserDevice device){for(String action:List.of("SEND_MESSAGE","REQUEST_RESUME","EXCHANGE_WECHAT","EXCHANGE_PHONE"))if(validationCases.findByDeviceIdAndActionType(device.getId(),action).isEmpty())validationCases.save(new LocalConnectorValidationCase(device,action,validationPrerequisites(action),validationExpectedResult(action)));}
 private LocalConnectorValidationCase requireValidation(UUID id,SystemUser user){LocalConnectorValidationCase validation=validationCases.findWithDeviceById(id).orElseThrow(()->bad("VALIDATION_CASE_NOT_FOUND","人工验收项目不存在"));requireAccess(validation.getDevice().getBossAccount().getCompany().getId(),user);return validation;}
 private String validationPrerequisites(String action){String common="独立 Chrome Profile 已人工登录\n当前停留在一个允许测试的已读会话\n页面无验证码、风险提示或登录失效\nHR 明确确认本次单次测试";return switch(action){case"SEND_MESSAGE"->common+"\n使用无承诺的固定测试文本\n发送前再次核对输入框和目标会话";case"REQUEST_RESUME"->common+"\n确认当前候选人尚未提供简历\n确认按钮文本和弹窗含义";case"EXCHANGE_WECHAT"->common+"\n确认公司允许交换微信\n确认候选人尚未完成该交换";default->common+"\n确认公司允许交换电话\n确认候选人尚未完成该交换";};}
 private String validationExpectedResult(String action){return switch(action){case"SEND_MESSAGE"->"页面仅出现一条与测试文本摘要对应的新 HR 外发消息，并可读取明确成功状态";case"REQUEST_RESUME"->"页面明确显示已向当前候选人发出一次简历请求，重复操作被识别并阻断";case"EXCHANGE_WECHAT"->"页面明确进入微信交换流程或显示已完成状态，不记录联系方式正文";default->"页面明确进入电话交换流程或显示已完成状态，不记录联系方式正文";};}
 private void verifyReadCapability(BrowserDevice device,String name,String digest,String reason,Instant now){LocalConnectorCapability capability=capabilities.findByDeviceIdAndCapability(device.getId(),name).orElseGet(()->capabilities.save(new LocalConnectorCapability(device,name)));capability.verifyReadOnly(digest,reason,now);}
 private boolean canAccess(UUID companyId,SystemUser user){return user.getRole()==UserRole.SYSTEM_ADMIN||user.getCompanyScopes().stream().map(Company::getId).anyMatch(companyId::equals);}private void requireAccess(UUID id,SystemUser user){if(!canAccess(id,user))throw new ApiException(HttpStatus.FORBIDDEN,"COMPANY_SCOPE_FORBIDDEN","当前账号无权访问该企业数据");}
 private String token(){byte[] bytes=new byte[32];random.nextBytes(bytes);return Base64.getUrlEncoder().withoutPadding().encodeToString(bytes);}private String hash(String value){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(value.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}private String clean(String value,int max){String v=value.trim();return v.length()<=max?v:v.substring(0,max);}private String cleanOptional(String value,int max){return value==null||value.isBlank()?null:clean(value,max);}private Instant validObservationTime(Instant value,Instant now){return value==null||value.isAfter(now.plusSeconds(300))||value.isBefore(now.minus(Duration.ofDays(7)))?now:value;}private ApiException bad(String code,String message){return new ApiException(HttpStatus.BAD_REQUEST,code,message);}private ApiException unauthorized(){return new ApiException(HttpStatus.UNAUTHORIZED,"DEVICE_UNAUTHORIZED","本地连接器令牌无效或已撤销");}
 private String valueOrPlaceholder(String value){String clean=cleanOptional(value,120);return clean==null?"待从 BOSS 岗位页补全":clean;}
}
