<script setup lang="ts">
import { computed,onMounted,ref } from 'vue';import { ElMessage } from 'element-plus';import { MagicStick } from '@element-plus/icons-vue';import { api,apiErrorMessage,ensureCsrf } from '../services/api';import { authStore } from '../stores/auth';import type { AiCandidateScreenResponse,AiJobParseResponse,CandidateContact } from '../types'
const description=ref('Java 后端开发工程师\n工作地点：上海\n薪资：20K-35K·14薪\n要求 3-5 年经验，本科学历，熟悉 Java、Spring Boot 和 PostgreSQL。'),jobResult=ref<AiJobParseResponse>(),parsing=ref(false),candidates=ref<CandidateContact[]>([]),contactId=ref(''),screenResult=ref<AiCandidateScreenResponse>(),screening=ref(false),error=ref('')
const canParse=computed(()=>authStore.state.user?.role!=='RECRUITER');const activeCandidates=computed(()=>candidates.value.filter(c=>c.privacyStatus==='ACTIVE'))
async function load(){try{candidates.value=(await api.get<CandidateContact[]>('/candidate-contacts')).data;contactId.value=activeCandidates.value[0]?.id??''}catch(e){error.value=apiErrorMessage(e,'候选人加载失败')}}
async function parse(){parsing.value=true;error.value='';try{await ensureCsrf();jobResult.value=(await api.post<AiJobParseResponse>('/ai/job-parse',{description:description.value})).data;ElMessage.success('AI 职位解析建议已生成')}catch(e){error.value=apiErrorMessage(e,'AI 职位解析失败')}finally{parsing.value=false}}
async function screen(){if(!contactId.value)return;screening.value=true;error.value='';try{await ensureCsrf();screenResult.value=(await api.post<AiCandidateScreenResponse>(`/ai/candidate-screen/${contactId.value}`)).data;ElMessage.success('AI 筛选建议已写入候选人时间线');await load()}catch(e){error.value=apiErrorMessage(e,'AI 候选人筛选失败')}finally{screening.value=false}}
function outcome(value:string){return value==='PASS'?'建议通过':value==='REJECT'?'建议淘汰':'建议复核'}
onMounted(load)
</script>
<template><div class="page-shell"><header class="page-heading"><div><h1>AI 招聘辅助</h1><p>解析职位 JD 并生成可追溯的候选人筛选建议，最终决策始终由 HR 确认。</p></div></header><el-alert title="默认使用可复现 Mock AI；外部 Provider 与候选人数据传输必须由预发布环境显式开启。" type="warning" :closable="false" show-icon class="ai-alert"/><el-alert v-if="error" :title="error" type="error" :closable="false" class="ai-alert"/><div class="ai-grid"><section v-if="canParse" class="surface-panel"><div class="section-title-row"><div><h2>AI 岗位解析</h2><p>输入原始 JD，生成待人工复核的结构化建议</p></div></div><div class="ai-form"><el-input v-model="description" type="textarea" :rows="10" maxlength="10000" show-word-limit/><el-button type="primary" :icon="MagicStick" :loading="parsing" @click="parse">生成解析建议</el-button></div><dl v-if="jobResult" class="result-grid"><div><dt>职位</dt><dd>{{jobResult.suggestion.title}}</dd></div><div><dt>地点</dt><dd>{{jobResult.suggestion.location}}</dd></div><div><dt>薪资</dt><dd>{{jobResult.suggestion.salaryMinK}}-{{jobResult.suggestion.salaryMaxK}}K · {{jobResult.suggestion.salaryMonths}}薪</dd></div><div><dt>经验</dt><dd>{{jobResult.suggestion.experienceRequirement}}</dd></div><div><dt>学历</dt><dd>{{jobResult.suggestion.educationRequirement}}</dd></div><div class="wide"><dt>筛选要求</dt><dd>{{jobResult.suggestion.screeningRequirements}}</dd></div><div class="wide rationale"><dt>生成说明</dt><dd>{{jobResult.suggestion.rationale}}</dd></div></dl></section><section class="surface-panel"><div class="section-title-row"><div><h2>AI 辅助筛选</h2><p>仅使用职业经历、学历和技能事实</p></div></div><div class="ai-form"><el-select v-model="contactId" filterable placeholder="选择候选人"><el-option v-for="candidate in activeCandidates" :key="candidate.id" :label="`${candidate.displayName} · ${candidate.jobPosition.title}`" :value="candidate.id"/></el-select><el-button type="primary" :icon="MagicStick" :loading="screening" :disabled="!contactId" @click="screen">生成筛选建议</el-button></div><article v-if="screenResult" class="screen-result"><el-tag :type="screenResult.decision.outcome==='PASS'?'success':screenResult.decision.outcome==='REJECT'?'danger':'warning'">{{outcome(screenResult.decision.outcome)}}</el-tag><p>{{screenResult.decision.rationale}}</p><span>{{screenResult.provider}} · {{screenResult.modelVersion}} · {{screenResult.promptVersion}}</span></article></section></div></div></template>
<style scoped>.ai-alert{margin-bottom:20px}.ai-grid{display:grid;grid-template-columns:1.2fr .8fr;gap:20px}.ai-form{display:grid;gap:14px;padding:20px 24px}.ai-form .el-select{width:100%}.result-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:0;margin:0;padding:0 24px 24px}.result-grid div{padding:14px;border:1px solid var(--border)}.result-grid .wide{grid-column:1/-1}.result-grid dt{color:var(--text-secondary);font-size:12px}.result-grid dd{margin:6px 0 0;line-height:1.55}.rationale{background:var(--brand-50)}.screen-result{margin:0 24px 24px;padding:18px;border:1px solid var(--border);border-radius:10px}.screen-result p{line-height:1.7}.screen-result span{color:var(--text-secondary);font-size:12px}@media(max-width:980px){.ai-grid{grid-template-columns:1fr}}@media(max-width:520px){.ai-form{padding:16px}.result-grid{grid-template-columns:1fr;padding:0 16px 16px}.result-grid .wide{grid-column:auto}.screen-result{margin:0 16px 16px}}</style>
