<script setup lang="ts">
import { computed,onMounted,ref } from 'vue'
import type { UploadFile } from 'element-plus'
import { ElMessage } from 'element-plus'
import { Download,UploadFilled } from '@element-plus/icons-vue'
import { api,apiErrorMessage,ensureCsrf } from '../services/api'
import type { CandidateImportBatch,CandidateImportRowStatus,JobPosition } from '../types'
const jobs=ref<JobPosition[]>([]),history=ref<CandidateImportBatch[]>([]),jobId=ref(''),selectedFile=ref<File>(),preview=ref<CandidateImportBatch>(),loading=ref(true),uploading=ref(false),confirming=ref(false),error=ref('')
const activeJobs=computed(()=>jobs.value.filter(j=>j.status==='ACTIVE'))
const statusLabels:Record<CandidateImportRowStatus,string>={VALID:'可导入',INVALID:'数据错误',DUPLICATE_FILE:'文件内重复',DUPLICATE_EXISTING:'已存在',IMPORTED:'已导入'}
async function load(){loading.value=true;try{const [jr,hr]=await Promise.all([api.get<JobPosition[]>('/job-positions'),api.get<CandidateImportBatch[]>('/candidate-imports')]);jobs.value=jr.data;history.value=hr.data;if(!jobId.value)jobId.value=activeJobs.value[0]?.id??''}catch(e){error.value=apiErrorMessage(e,'导入页加载失败')}finally{loading.value=false}}
function choose(file:UploadFile){selectedFile.value=file.raw;preview.value=undefined;error.value=''}
async function parse(){if(!jobId.value||!selectedFile.value){error.value='请选择职位和 CSV/XLSX 文件';return}uploading.value=true;error.value='';try{await ensureCsrf();const body=new FormData();body.append('jobPositionId',jobId.value);body.append('file',selectedFile.value);preview.value=(await api.post<CandidateImportBatch>('/candidate-imports/preview',body)).data;ElMessage.success('文件解析完成，请确认预览结果')}catch(e){error.value=apiErrorMessage(e,'文件解析失败')}finally{uploading.value=false}}
async function confirm(){if(!preview.value)return;confirming.value=true;try{await ensureCsrf();preview.value=(await api.post<CandidateImportBatch>(`/candidate-imports/${preview.value.id}/confirm`)).data;ElMessage.success(`已导入 ${preview.value.importedRows} 个候选人`);await load()}catch(e){error.value=apiErrorMessage(e,'确认导入失败')}finally{confirming.value=false}}
function downloadTemplate(){const content='externalCandidateId,displayName,currentTitle,yearsExperience,education,skillsSummary\nexample-001,张三,Java开发,5,本科,"Java,Spring Boot,PostgreSQL"\n';const link=document.createElement('a');link.href=URL.createObjectURL(new Blob(['\uFEFF'+content],{type:'text/csv;charset=utf-8'}));link.download='candidate-import-template.csv';link.click();URL.revokeObjectURL(link.href)}
function type(status:CandidateImportRowStatus){return status==='VALID'||status==='IMPORTED'?'success':status==='INVALID'?'danger':'warning'}
function formatDate(value:string){return new Intl.DateTimeFormat('zh-CN',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value))}
onMounted(load)
</script>

<template><div class="page-shell"><header class="page-heading"><div><h1>候选人批量导入</h1><p>支持 UTF-8 CSV 和 XLSX，先预览校验与去重，再确认入库。</p></div><el-button :icon="Download" @click="downloadTemplate">下载 CSV 模板</el-button></header><el-alert title="外部候选人 ID 仅用于生成不可逆去重摘要；确认后会清理批次预览中的个人字段。" type="info" :closable="false" show-icon class="import-alert"/><div v-if="loading" class="surface-panel skeleton-stack"><el-skeleton :rows="7" animated/></div><template v-else><section class="surface-panel import-panel"><div class="section-title-row"><div><h2>1. 选择职位和文件</h2><p>单次最多 1000 行、5 MB</p></div></div><div class="import-controls"><el-select v-model="jobId" filterable placeholder="选择已启用职位"><el-option v-for="job in activeJobs" :key="job.id" :label="`${job.title}（${job.company.name}）`" :value="job.id"/></el-select><el-upload :auto-upload="false" :limit="1" accept=".csv,.xlsx" :on-change="choose" :on-remove="()=>selectedFile=undefined"><el-button :icon="UploadFilled">选择 CSV/XLSX</el-button></el-upload><el-button type="primary" :loading="uploading" @click="parse">解析并预览</el-button></div><el-alert v-if="error" :title="error" type="error" :closable="false"/></section>
<section v-if="preview" class="surface-panel preview-panel"><div class="section-title-row"><div><h2>2. 确认预览</h2><p>{{preview.sourceFilename}} · {{preview.jobTitle}}</p></div><el-button v-if="preview.status==='PREVIEWED'" type="success" :disabled="preview.validRows===0" :loading="confirming" @click="confirm">确认导入 {{preview.validRows}} 行</el-button></div><div class="import-metrics"><div><span>总行数</span><strong>{{preview.totalRows}}</strong></div><div><span>可导入</span><strong>{{preview.validRows}}</strong></div><div><span>错误</span><strong>{{preview.invalidRows}}</strong></div><div><span>重复</span><strong>{{preview.duplicateRows}}</strong></div></div><el-table :data="preview.rows" class="preview-table"><el-table-column prop="rowNumber" label="行" width="65"/><el-table-column prop="displayName" label="姓名" min-width="120"/><el-table-column prop="currentTitle" label="当前职位" min-width="150"/><el-table-column prop="yearsExperience" label="年限" width="70"/><el-table-column label="结果" min-width="210"><template #default="{row}"><el-tag :type="type(row.status)">{{statusLabels[row.status as CandidateImportRowStatus]}}</el-tag><span class="row-message">{{row.validationMessage}}</span></template></el-table-column></el-table></section>
<section class="surface-panel history-panel"><div class="section-title-row"><div><h2>最近导入</h2><p>仅展示当前账号企业权限内的批次</p></div></div><el-empty v-if="!history.length" description="暂无导入记录"/><div v-else class="history-list"><article v-for="item in history" :key="item.id"><div><strong>{{item.sourceFilename}}</strong><span>{{item.jobTitle}} · {{formatDate(item.createdAt)}}</span></div><el-tag :type="item.status==='COMPLETED'?'success':'warning'">{{item.status==='COMPLETED'?`已导入 ${item.importedRows}`:'待确认'}}</el-tag></article></div></section></template></div></template>

<style scoped>.import-alert,.import-panel,.preview-panel{margin-bottom:20px}.import-controls{display:grid;grid-template-columns:minmax(260px,1fr) auto auto;gap:12px;align-items:start;padding:20px 24px}.import-controls .el-select{width:100%}.import-metrics{display:grid;grid-template-columns:repeat(4,1fr);border-bottom:1px solid var(--border)}.import-metrics div{padding:16px 24px;border-right:1px solid var(--border)}.import-metrics span,.import-metrics strong{display:block}.import-metrics span,.row-message,.history-list span{color:var(--text-secondary);font-size:12px}.import-metrics strong{margin-top:4px;font-size:22px}.preview-table{width:100%}.row-message{margin-left:8px}.history-list{display:grid;gap:0}.history-list article{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:16px 24px;border-top:1px solid var(--border)}.history-list article:first-child{border-top:0}.history-list strong,.history-list span{display:block}.history-list span{margin-top:5px}@media(max-width:720px){.import-controls{grid-template-columns:1fr;padding:16px}.import-controls .el-button{width:100%;min-height:42px}.import-metrics{grid-template-columns:repeat(2,1fr)}.import-metrics div:nth-child(2){border-right:0}.preview-panel{overflow-x:auto}.preview-table{min-width:720px}.history-list article{padding:14px}}</style>
