<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import { ChatDotRound, Refresh, Right, Warning } from '@element-plus/icons-vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { api, apiErrorMessage, ensureCsrf } from '../services/api'
import { authStore } from '../stores/auth'
import type { AutoReplyAttempt, AutoReplyPolicy, BossAccount, BrowserDevice, CandidateContact } from '../types'

const router=useRouter(),loading=ref(true),actionId=ref(''),updatedAt=ref<Date|null>(null)
const accounts=ref<BossAccount[]>([]),candidates=ref<CandidateContact[]>([]),policies=ref<AutoReplyPolicy[]>([]),devices=ref<BrowserDevice[]>([]),attempts=ref<AutoReplyAttempt[]>([])
const displayName=computed(()=>authStore.state.user?.displayName||'HR')
const activePolicies=computed(()=>policies.value.filter(x=>x.awayActive))
const followUps=computed(()=>candidates.value.filter(x=>x.needsHrFollowUp))
const sentToday=computed(()=>policies.value.reduce((n,x)=>n+x.sentToday,0))
const connectionIssues=computed(()=>policies.value.filter(x=>{const d=devices.value.find(d=>d.accountId===x.accountId&&d.status==='ACTIVE');return x.accountStatus!=='ACTIVE'||!x.messageSendCapable||!d||d.runtimeState!=='RUNNING'}))
const recentAttempts=computed(()=>attempts.value.slice(0,5))
const overallState=computed(()=>activePolicies.value.length?`${activePolicies.value.length} 个账号正在托管`:'你当前在岗')
const subtitle=computed(()=>activePolicies.value.length?'候选人新消息将在超时且满足安全条件后获得接待回复。':'离开前选择账号和返回时间，系统会在你不在时接待未回复消息。')
async function load(){loading.value=true;const results=await Promise.allSettled([api.get<BossAccount[]>('/boss-accounts'),api.get<CandidateContact[]>('/candidate-contacts'),api.get<AutoReplyPolicy[]>('/auto-replies/policies'),api.get<BrowserDevice[]>('/browser-devices'),api.get<AutoReplyAttempt[]>('/auto-replies/attempts')]);const targets=[accounts,candidates,policies,devices,attempts];results.forEach((r,i)=>{if(r.status==='fulfilled')targets[i]!.value=r.value.data as never});updatedAt.value=new Date();loading.value=false}
async function setAway(x:AutoReplyPolicy,mode:'IN_OFFICE'|'TEMPORARY'|'AFTER_HOURS',hours=0){if(!x.configured){ElMessage.warning('请先由管理员配置该账号托管策略');return}actionId.value=x.accountId;try{await ensureCsrf();await api.put(`/auto-replies/policies/${x.accountId}/away-mode`,{mode,endsAt:mode==='IN_OFFICE'?null:new Date(Date.now()+hours*3600000).toISOString()});ElMessage.success(mode==='IN_OFFICE'?'已结束该账号托管':'离开托管已开启');await load()}catch(e){ElMessage.error(apiErrorMessage(e,'托管状态更新失败'))}finally{actionId.value=''}}
async function endAll(){if(!activePolicies.value.length)return;try{await ElMessageBox.confirm(`确认结束 ${activePolicies.value.length} 个账号的离开托管？`,'我已返回',{confirmButtonText:'结束全部托管'});for(const x of activePolicies.value)await setAway(x,'IN_OFFICE');ElMessage.success('全部托管已结束，欢迎回来')}catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error('结束全部托管失败，请检查账号状态')}}
function open(path:string){void router.push(path)}
function formatTime(v?:string){return v?new Intl.DateTimeFormat('zh-CN',{hour:'2-digit',minute:'2-digit',month:'numeric',day:'numeric'}).format(new Date(v)):'—'}
function statusLabel(s:string){return {SENT:'已接待',FAILED:'发送失败',SKIPPED:'已跳过',PENDING_REVIEW:'待审核',CLAIMED:'处理中'}[s]||s}
onMounted(load)
</script>

<template><div class="page-shell dashboard-page">
 <header class="hero"><div><span class="eyebrow">AWAY ASSISTANT</span><h1>{{overallState}}</h1><p>{{subtitle}}</p></div><div class="hero-actions"><el-button :icon="Refresh" :loading="loading" @click="load">刷新</el-button><el-button v-if="activePolicies.length" type="success" @click="endAll">我已返回，结束全部托管</el-button></div></header>
 <div v-if="loading" class="surface-panel skeleton-stack"><el-skeleton :rows="8" animated/></div>
 <template v-else>
  <section class="metric-grid"><button @click="open('/auto-replies')"><span>正在托管</span><strong>{{activePolicies.length}}</strong><small>共 {{policies.length}} 个账号</small></button><button @click="open('/candidates')"><span>待 HR 跟进</span><strong>{{followUps.length}}</strong><small>返回后优先处理</small></button><button @click="open('/auto-replies')"><span>今日自动接待</span><strong>{{sentToday}}</strong><small>已发送与待审核</small></button><button @click="open('/boss-accounts')"><span>连接异常</span><strong :class="{danger:connectionIssues.length}">{{connectionIssues.length}}</strong><small>异常时不会发送</small></button></section>

  <div class="main-grid"><section class="surface-panel away-panel"><div class="section-title-row"><div><h2>离开托管</h2><p>为每个账号选择离开时长，到期自动停止。</p></div><small>你好，{{displayName}}</small></div><div v-if="!policies.length" class="empty"><strong>还没有可托管的账号</strong><el-button type="primary" @click="open('/boss-accounts')">连接 BOSS 账号</el-button></div><div v-else class="account-list"><article v-for="x in policies" :key="x.accountId"><div class="account-status" :class="{active:x.awayActive}"><span></span><div><strong>{{x.accountName}}</strong><small v-if="x.awayActive">{{x.awayMode==='AFTER_HOURS'?'下班托管':'临时离开'}} · 至 {{formatTime(x.awayEndsAt)}}</small><small v-else>当前在岗，不会自动接待</small></div></div><div class="account-actions"><el-button v-if="x.awayActive" type="success" plain :loading="actionId===x.accountId" @click="setAway(x,'IN_OFFICE')">我已返回</el-button><template v-else><el-button :loading="actionId===x.accountId" @click="setAway(x,'TEMPORARY',1)">离开 1 小时</el-button><el-button type="primary" :loading="actionId===x.accountId" @click="setAway(x,'TEMPORARY',2)">离开 2 小时</el-button><el-button @click="setAway(x,'AFTER_HOURS',12)">下班托管</el-button></template></div></article></div></section>

   <aside class="surface-panel attention-panel"><div class="section-title-row"><div><h2>需要处理</h2><p>先处理异常，再开启托管。</p></div></div><div v-if="!connectionIssues.length&&!followUps.length" class="all-clear"><span>✓</span><strong>当前没有阻断事项</strong><small>账号连接和待跟进队列状态正常</small></div><button v-for="x in connectionIssues" :key="`issue-${x.accountId}`" @click="open('/boss-accounts')"><Warning/><span><strong>{{x.accountName}} 连接需要检查</strong><small>登录、页面识别或设备心跳异常</small></span><Right/></button><button v-if="followUps.length" @click="open('/candidates')"><ChatDotRound/><span><strong>{{followUps.length}} 个会话等待 HR 跟进</strong><small>自动接待不代表沟通已完成</small></span><Right/></button></aside>
  </div>

  <section class="surface-panel recent-panel"><div class="section-title-row"><div><h2>最近自动接待</h2><p>快速确认离开期间发生了什么。</p></div><el-button text @click="open('/auto-replies')">查看全部</el-button></div><div v-if="!recentAttempts.length" class="empty">暂无自动接待记录</div><div v-else class="attempt-list"><article v-for="x in recentAttempts" :key="x.id"><span class="avatar">{{x.candidateName.slice(0,1)}}</span><div><strong>{{x.candidateName}}</strong><small>{{x.jobTitle}} · {{x.accountName}}</small></div><el-tag :type="x.status==='SENT'?'success':x.status==='FAILED'?'danger':'info'">{{statusLabel(x.status)}}</el-tag><span class="result">{{x.resultMessage||'等待处理结果'}}</span><time>{{formatTime(x.completedAt||x.createdAt)}}</time></article></div></section>
 </template>
</div></template>

<style scoped>
.dashboard-page{padding-top:32px}.hero{display:flex;align-items:flex-end;justify-content:space-between;gap:24px;margin-bottom:24px;padding:8px 4px}.eyebrow{color:var(--brand-700);font-size:12px;font-weight:800;letter-spacing:.1em}.hero h1{margin:8px 0 7px;font-size:clamp(28px,3vw,40px);letter-spacing:-.035em}.hero p{max-width:720px;margin:0;color:var(--text-secondary);line-height:1.6}.hero-actions{display:flex;gap:10px}.metric-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-bottom:20px}.metric-grid button{padding:20px 22px;border:1px solid var(--border);border-radius:16px;background:#fff;color:var(--text);text-align:left;cursor:pointer;box-shadow:var(--shadow-sm)}.metric-grid button:hover{border-color:#a9c9c4}.metric-grid span,.metric-grid small{display:block;color:var(--text-secondary)}.metric-grid strong{display:block;margin:10px 0 5px;font-size:30px}.metric-grid small{font-size:12px}.danger{color:var(--danger)}.main-grid{display:grid;grid-template-columns:minmax(0,1.6fr) minmax(310px,.8fr);gap:20px;margin-bottom:20px}.away-panel,.attention-panel,.recent-panel{overflow:hidden}.section-title-row>small{color:var(--text-secondary)}.account-list{padding:0 20px 20px}.account-list article{display:flex;align-items:center;justify-content:space-between;gap:18px;padding:16px 0;border-top:1px solid var(--border)}.account-status{display:flex;align-items:center;gap:12px}.account-status>span{width:10px;height:10px;border-radius:50%;background:#98a2b3}.account-status.active>span{background:#12b76a;box-shadow:0 0 0 5px #d1fadf}.account-status small{display:block;margin-top:5px;color:var(--text-secondary)}.account-actions{display:flex;gap:8px}.attention-panel>button{display:grid;width:100%;grid-template-columns:28px 1fr auto;align-items:center;gap:10px;padding:15px 20px;border:0;border-top:1px solid var(--border);background:#fff;color:var(--text);text-align:left;cursor:pointer}.attention-panel>button>svg{width:20px;color:var(--warning)}.attention-panel button small{display:block;margin-top:4px;color:var(--text-secondary)}.all-clear{display:grid;justify-items:center;gap:6px;padding:38px 20px}.all-clear>span{display:grid;width:42px;height:42px;place-items:center;border-radius:50%;background:#ecfdf3;color:var(--success);font-size:22px}.all-clear small{color:var(--text-secondary)}.attempt-list{padding:0 20px 20px}.attempt-list article{display:grid;grid-template-columns:38px minmax(180px,1fr) 100px minmax(220px,1.3fr) 110px;align-items:center;gap:14px;padding:14px 0;border-top:1px solid var(--border)}.avatar{display:grid;width:38px;height:38px;place-items:center;border-radius:10px;background:var(--brand-100);color:var(--brand-700);font-weight:700}.attempt-list small{display:block;margin-top:4px;color:var(--text-secondary)}.result,time{color:var(--text-secondary);font-size:12px}.empty{display:grid;justify-items:center;gap:12px;padding:40px;color:var(--text-secondary)}
@media(max-width:1000px){.metric-grid{grid-template-columns:repeat(2,1fr)}.main-grid{grid-template-columns:1fr}}@media(max-width:700px){.hero{align-items:flex-start;flex-direction:column}.hero-actions{width:100%;flex-direction:column}.metric-grid{grid-template-columns:1fr 1fr}.account-list article{align-items:flex-start;flex-direction:column}.account-actions{flex-wrap:wrap}.attempt-list article{grid-template-columns:38px 1fr auto}.result,time{grid-column:2/4}}@media(max-width:440px){.metric-grid{grid-template-columns:1fr}}
</style>
